// Code generated by "stringer -type=policy -linecomment"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[policyFIFO-1]
	_ = x[policyShortestJobFirst-2]
}

const _policy_name = "fifosjf"

var _policy_index = [...]uint8{0, 4, 7}

func (i policy) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_policy_index)-1 {
		return "policy(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _policy_name[_policy_index[idx]:_policy_index[idx+1]]
}
