// Code generated by "stringer -type=sched -linecomment"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[schedFIFO-1]
	_ = x[schedShortestJobFirst-2]
}

const _sched_name = "fifosjf"

var _sched_index = [...]uint8{0, 4, 7}

func (i sched) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_sched_index)-1 {
		return "sched(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _sched_name[_sched_index[idx]:_sched_index[idx+1]]
}
