# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
- name: "Restart network"
  listen: "restart_network"
  become: true
  ansible.builtin.service:
    name: netif
    state: restarted
  async: 30
  poll: 0
  register: netif_restart_network_task

- name: "Wait for network to restart"
  listen: "restart_network"
  ansible.builtin.async_status:
    jid: "{{ netif_restart_network_task.ansible_job_id }}"
  retries: 10
  register: netif_wait_restart_network_task
  until: netif_wait_restart_network_task is finished
