# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
# doas_conf is a list of configuration lines. Each item has the following
# structure:
#
#   rule        string  doas(1) rule (see doas.conf(5))
#   description string  rule description
doas_conf: "{{ undef(hint='doas rules') }}"
