# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
- name: Setup timezone to {{ timezone_name }}
  ansible.builtin.command:
    cmd: tzsetup -s {{ timezone_name }}
  register: timezone_setup_task
  changed_when: timezone_setup_task.rc == 0

- name: Install timezone
  ansible.builtin.command:
    cmd: tzsetup -r
  register: timezone_install_task
  changed_when: timezone_install_task.rc == 0
