# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
# routing_defaultrouter sets the default route.
routing_defaultrouter: ""

# routing_enable_gateway enables IP forwarding between interfaces (see sysctl
# net.inet.ip.forwarding).
routing_enable_gateway: false
