# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
# keep-sorted start
ansible_jexec_over_ssh_jail_name: bsd
doas_conf:
  - rule: permit nopass :wheel
    description: Permit members of the wheel group to perform actions as root without password.
  - rule: permit skhalatyan as root cmd poudriere
    description: Permit user skhalatyan to run poudriere.
  - rule: permit setenv { PORTSDIR } skhalatyan as root  cmd make args makesum
    description: Permit user skhalatyan to generate distinfo for ports.
openssl_gen_rsa:
  path: /usr/local/etc/poudriere/ssl/pkg.pub
  owner: root
  group: wheel
openssl_gen_rsa_fetch:
  source: pkg.lab.net:/usr/local/etc/poudriere/ssl/pkg.pub
  target: /usr/local/etc/pkg/ssl/lab-ports.pub
ssh_allow_groups:
  - ssh
ssh_listen_addresses:
  - 10.0.0.101
# keep-sorted end
