# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
# keep-sorted start
bind_acl:
  name: jails
  subnets:
    - 10.0.0.0/24
bind_forwarders:
  - 192.168.1.1
bind_listen_on:
  - 127.0.0.1
  - 10.0.0.2
pkg_install:
  - neovim
  - FreeBSD-libexecinfo # for /usr/lib/libexecinfo.so.1
ssh_allow_users:
  - op
ssh_listen_addresses:
  - 10.0.0.2
user_list:
  # keep-sorted start
  - name: op
    shell: /bin/tcsh
  - name: root
    group: wheel
    home: /root
    shell: /bin/tcsh
  # keep-sorted end
# keep-sorted end
