# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
# keep-sorted start
bind_listen_on:
  port: 5353
  addr: 10.0.0.2
bind_zones:
  - lab.net
local_unbound_forward_zones:
  - name: "."
    addr: 192.168.10.1
local_unbound_stub_zones:
  - name: "lab.net"
    addr: 10.0.0.2@5353
  - name: "10.in-addr.arpa."
    addr: 10.0.0.2@5353
    type: always_transparent
pkg_install:
  - neovim
  - FreeBSD-libexecinfo # for /usr/lib/libexecinfo.so.1
ssh_allow_users:
  - op
ssh_listen_addresses:
  - 10.0.0.2
user_list:
  # keep-sorted start
  - name: op
    shell: /bin/tcsh
  - name: root
    group: wheel
    home: /root
    shell: /bin/tcsh
  # keep-sorted end
# keep-sorted end
