# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
# keep-sorted start
ansible_jexec_over_ssh_jail_name: ldap
local_unbound_forward_zones:
  - name: "."
    addr: 192.168.10.1
local_unbound_stub_zones:
  - name: "lab.net"
    addr: 10.0.0.2@853
    tls_upstream: true
  - name: "10.in-addr.arpa."
    addr: 10.0.0.2@853
    tls_upstream: true
    type: always_transparent
openldap_server_addr: 10.0.0.3
openldap_server_entries:
  - name: root node
    dn: dc=lab,dc=net
    dc: lab
    objectClass:
      - dcObject
      - organization
    description: Research & Development lab
    o: Research Lab
  - name: people tree
    dn: ou=people,dc=lab,dc=net
    ou: people
    objectClass: organizationalUnit
    description: people in the lab
  - name: groups tree
    dn: ou=groups,dc=lab,dc=net
    ou: groups
    objectClass: organizationalUnit
    description: groups in the lab
  - name: op group
    dn: cn=op,ou=groups,dc=lab,dc=net
    cn: op
    objectClass:
      - top
      - posixGroup
    gidNumber: 1001
    memberUid: op
  - name: op user
    dn: uid=op,ou=people,dc=lab,dc=net
    cn: op
    objectClass:
      - top
      - account
      - posixAccount
    uid: op
    uidNumber: 1001
    gidNumber: 1001
    homeDirectory: /home/op
    loginShell: /bin/tcsh
    gecos: Operator
    description: Operator
  - name: skhalatyan group
    dn: cn=skhalatyan,ou=groups,dc=lab,dc=net
    cn: skhalatyan
    objectClass:
      - top
      - posixGroup
    gidNumber: 10001
    memberUid: skhalatyan
  - name: skhalatyan user
    dn: uid=skhalatyan,ou=people,dc=lab,dc=net
    cn: skhalatyan
    objectClass:
      - top
      - account
      - posixAccount
    uid: skhalatyan
    uidNumber: 10001
    gidNumber: 10001
    homeDirectory: /home/skhalatyan
    loginShell: /bin/tcsh
    description: Samvel Khalatyan account
openssl_gen_common_name: ldap.lab.net
openssl_gen_crt: "/usr/local/etc/openldap/ssl/ldap.crt"
openssl_gen_group: ldap
openssl_gen_owner: ldap
pkg_install:
  - neovim
ssh_allow_users:
  - op
ssh_listen_addresses:
  - 10.0.0.3
user_list:
  # keep-sorted start
  - name: op
    shell: /bin/tcsh
  - name: root
    group: wheel
    home: /root
    shell: /bin/tcsh
  # keep-sorted end
# keep-sorted end
