# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
# keep-sorted start
hostname_name: "nuc.lab.net"
jail_skel_packages:
  # keep-sorted start
  - FreeBSD-csh # for /bin/tcsh
  - FreeBSD-runtime # for /etc/os-release
  - doas
  - neovim
  # keep-sorted end
netif_clones:
  # keep-sorted start
  - name: bridge0
    cidr: 192.168.10.101/24
    addm:
      - igc0
    desc: jail:ext
  - name: bridge1
    cidr: 10.0.0.1/24
    desc: jail:int
  # keep-sorted end
netif_ethernet_if: igc0
pflog_enable: true
pkg_install:
  - neovim
rc_migrate:
  # keep-sorted start
  - name: moused_nondefault_enable
    value: false
    path: /etc/rc.conf.d/moused
  - name: powerd_enable
    value: true
    path: /etc/rc.conf.d/powerd
  # keep-sorted end
rc_remove:
  - dumpdev
rc_update:
  # keep-sorted start
  - name: autoboot_delay
    value: 0
    path: /boot/loader.conf
  - name: rc_debug
    value: true
  - name: rc_info
    value: true
  # keep-sorted end
routing_defaultrouter: 192.168.10.1
ssh_allow_users:
  - op
user_list:
  # keep-sorted start
  - name: op
    shell: /bin/tcsh
  - name: root
    group: wheel
    home: /root
    shell: /bin/tcsh
  # keep-sorted end
# keep-sorted end
