# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
# keep-sorted start
ansible_jexec_over_ssh_jail_name: pkg
local_pkg_listen_on: 10.0.0.5
openssl_gen_common_name: pkg.lab.net
openssl_gen_crt: "/usr/local/etc/nginx/ssl/pkg.crt"
openssl_gen_group: www
openssl_gen_owner: www
openssl_gen_rsa:
  path: /usr/local/etc/poudriere/ssl/pkg.pub
  owner: root
  group: wheel
ssh_listen_addresses:
  - 10.0.0.5
# keep-sorted end
