# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
# keep-sorted start
# bind_listen_on restricts binding parameters to listen on. It must have the
# following structure:
#
#   port  integer?  port number to listen on (defaults to 53 - see bind doc)
#   addr  string    IPv4 address to listen on
bind_listen_on:
# bind_package is the package name with bind DNS server.
bind_package: bind920
# bind_zones lists zone names to configure.
bind_zones:
  -
# keep-sorted end
