# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
- name: "Start bind"
  listen: "bind_start"
  become: true
  ansible.builtin.service:
    name: named
    state: started

- name: "Restart bind"
  listen: "bind_restart"
  become: true
  ansible.builtin.service:
    name: named
    state: restarted
