// Code generated by "stringer -type=Action -linecomment"; DO NOT EDIT.

package test

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ActionBenchmark-1]
	_ = x[ActionContinue-2]
	_ = x[ActionFail-3]
	_ = x[ActionOutput-4]
	_ = x[ActionPass-5]
	_ = x[ActionPause-6]
	_ = x[ActionRun-7]
	_ = x[ActionSkip-8]
	_ = x[ActionStart-9]
}

const _Action_name = "benchcontfailoutputpasspauserunskipstart"

var _Action_index = [...]uint8{0, 5, 9, 13, 19, 23, 28, 31, 35, 40}

func (i Action) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_Action_index)-1 {
		return "Action(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Action_name[_Action_index[idx]:_Action_index[idx+1]]
}
