// Code generated by "stringer -type Direction -linecomment"; DO NOT EDIT.

package mem

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DirPositive-0]
	_ = x[DirNegative-1]
}

const _Direction_name = "positivenegative"

var _Direction_index = [...]uint8{0, 8, 16}

func (i Direction) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Direction_index)-1 {
		return "Direction(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Direction_name[_Direction_index[idx]:_Direction_index[idx+1]]
}
