// Copyright 2026 Samvel Khalatyan. All rights reserved.
//
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package errors

import "io"

// WriterWithError wraps an io.Writer and stores the error from last failed
// operation. It allows to avoid systematic Write/if-error checks.
//
// Ref: https://go.dev/blog/errors-are-values
type WriterWithError struct {
	w   io.Writer
	err error
}

// NewWriterWithError creates a [WriterWithError].
func NewWriterWithError(w io.Writer) *WriterWithError {
	return &WriterWithError{w: w}
}

// Err returns the last error generated by wrapped writer.
func (w *WriterWithError) Err() error {
	return w.err
}

// Write implement [io.Writer] interface.
func (w *WriterWithError) Write(p []byte) (n int, err error) {
	if w.err != nil {
		return 0, w.err
	}
	n, w.err = w.w.Write(p)
	return n, w.err
}
