# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
- name: "Bootstrap jails"
  ansible.builtin.import_tasks: "sub_bootstrap.yml"
  tags: bootstrap

- name: "Create a template"
  ansible.builtin.import_tasks: "sub_template.yml"
  tags: template
