# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
# openldap_server_addr is the ip-address to listen to.
openldap_server_addr: ""
