#!/bin/sh
#
# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

# make-lint runs make(1) in noop mode to validate Makefile.
#
# SYNOPSIS
#
#   make-lint file

set -e

case $(uname) in
  Darwin)
    MAKE_CMD=bmake
    ;;
  FreeBSD)
    MAKE_CMD=make
    ;;
  *)
    echo >&2 "unsupported OS: $(uname)"
    exit 1
    ;;
esac

for f in "$@"; do
  name=$(basename ${f})
  dir=$(dirname ${f})
  ${MAKE_CMD} -N -C ${dir} -f ${name}
done
