#!/bin/sh
#
# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

# Yaml-lint runs different linters and formatter for ordinary ans Ansible YAML
# files. A YAML file is Ansible YAML if it resides in an Ansible project, i.e.
# a folder with ansible.cfg file.
set -e

# ansible_project detects Ansible project and returns path to it, else empty
# string.
ansible_project() {
  local p=${1:?'ansible_project: missing file'}
  for _ in $(seq 1 5); do
    if [ ${p} == "." ]; then
      break
    fi
    p=$(dirname ${p})
    if [ -e ${p}/ansible.cfg ]; then
      echo "${p}"
    fi
  done
}

yaml_files=
yaml_ansible_files=
ansible_project_dir=
for f; do
  # assuming all files belong to the same project
  project_dir=$(ansible_project "${f}")
  if [ -n "${project_dir}" ]; then
    ansible_project_dir="${project_dir}"
    yaml_ansible_files="${yaml_ansible_files} ${f}"
  else
    yaml_files="${yaml_files} ${f}"
  fi
done

rc=0
if [ -n "${yaml_ansible_files}" ]; then
  if ! ansible-lint --project-dir "${ansible_project_dir}" -f brief -qq --fix=all ${yaml_ansible_files}; then
    rc=1
  fi
fi

if [ -n "${yaml_files}" ]; then
  if ! yamlfmt ${yaml_files}; then
    rc=1
  fi
fi

exit ${rc}
