# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
- name: "Migrate sshd_enable"
  ansible.builtin.include_role:
    name: sysrc
  vars:
    sysrc_migrate:
      name: sshd_enable
      value: true
      path: /etc/rc.conf.d/sshd

- name: "Update configuration"
  vars:
    _conf_file: "{{ ssh_server_config }}"
  block:
    # noqa name[template]
    - name: "Update {{ _conf_file }} - listen on cloned interfaces"
      ansible.builtin.lineinfile:
        path: "{{ _conf_file }}"
        line: "ListenAddress={{ item }}"
      loop: "{{ ssh_listen_addresses }}"
      notify: "restart_sshd"

    - name: "Update {{ _conf_file }} - allow op user" # noqa name[template]
      ansible.builtin.lineinfile:
        path: "{{ _conf_file }}"
        line: "AllowUsers={{ ssh_allow_users | join(' ') }}"
      notify: "restart_sshd"
