# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
# keep-sorted start
ansible_connection: jexec_over_ssh
ansible_jexec_over_ssh_escalator: doas
ansible_ssh_host: nuc.lab.net
# keep-sorted end
