// Code generated by "stringer -type TokenType -linecomment"; DO NOT EDIT.

package lex

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TokenComma-1]
	_ = x[TokenDivide-2]
	_ = x[TokenEqual-3]
	_ = x[TokenError-4]
	_ = x[TokenGreater-5]
	_ = x[TokenGreaterOrEqual-6]
	_ = x[TokenIdent-7]
	_ = x[TokenLess-8]
	_ = x[TokenLessOrEqual-9]
	_ = x[TokenLpar-10]
	_ = x[TokenMinus-11]
	_ = x[TokenMultiply-12]
	_ = x[TokenNotEqual-13]
	_ = x[TokenNumber-14]
	_ = x[TokenPlus-15]
	_ = x[TokenRange-16]
	_ = x[TokenRpar-17]
}

const _TokenType_name = "commadivideequalerrorgreatergreaterorequalidentifierlesslessorequalrparminusmultiplynotequalnumberplusrangelpar"

var _TokenType_index = [...]uint8{0, 5, 11, 16, 21, 28, 42, 52, 56, 67, 71, 76, 84, 92, 98, 102, 107, 111}

func (i TokenType) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_TokenType_index)-1 {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[idx]:_TokenType_index[idx+1]]
}
