// Code generated by "stringer -type tokenType -linecomment"; DO NOT EDIT.

package lex

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TokenComma-1]
	_ = x[TokenDivide-2]
	_ = x[TokenError-3]
	_ = x[TokenIdent-4]
	_ = x[TokenLpar-5]
	_ = x[TokenMinus-6]
	_ = x[TokenMultiply-7]
	_ = x[TokenNumber-8]
	_ = x[TokenPlus-9]
	_ = x[TokenRange-10]
	_ = x[TokenRpar-11]
}

const _tokenType_name = "commadivideerroridentifierrparminusmultiplynumberplusrangelpar"

var _tokenType_index = [...]uint8{0, 5, 11, 16, 26, 30, 35, 43, 49, 53, 58, 62}

func (i tokenType) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_tokenType_index)-1 {
		return "tokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _tokenType_name[_tokenType_index[idx]:_tokenType_index[idx+1]]
}
