// Code generated by "stringer -type tokenType -linecomment"; DO NOT EDIT.

package lex

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TokenError-1]
	_ = x[TokenNumber-2]
	_ = x[TokenPlus-3]
	_ = x[TokenMinus-4]
	_ = x[TokenLpar-5]
	_ = x[TokenRpar-6]
}

const _tokenType_name = "errornumberplusminusrparlpar"

var _tokenType_index = [...]uint8{0, 5, 11, 15, 20, 24, 28}

func (i tokenType) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_tokenType_index)-1 {
		return "tokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _tokenType_name[_tokenType_index[idx]:_tokenType_index[idx+1]]
}
