# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

# Flavor: FreeBSD

install: .PHONY
	@echo ".. compile typescript; \
		tsgo

watch: .NOTMAIN .PHONY
	@echo ".. monitor ${.CURDIR} for changes"; \
		tsgo -w
