# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
- name: Upgrade packages
  ansible.builtin.service:
    name: "*"
    state: latest
  listen: "upgrade_packages"

- name: Restart syslogd
  ansible.builtin.service:
    name: syslogd
    state: restarted
  listen: "restart_syslogd"

- name: Restart ntpd
  ansible.builtin.service:
    name: ntpd
    state: restarted
  listen: "restart_ntpd"

- name: Restart sshd
  ansible.builtin.service:
    name: sshd
    state: restarted
  listen: "restart_sshd"

- name: Restart routing
  ansible.builtin.service:
    name: routing
    state: restarted
  listen: "restart_routing"

- name: Start pf
  ansible.builtin.service:
    name: pf
    state: started
  listen: "start_pf"

- name: Reload pf.conf
  ansible.builtin.service:
    name: pf
    state: reloaded
  listen: "reload_pf_conf"

- name: Start pflog
  ansible.builtin.service:
    name: pflog
    state: started
  listen: "start_pflog"

- name: Restart network
  ansible.builtin.service:
    name: network
    state: restarted
  listen: "restart_network"
