# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
- name: Restart sshd
  ansible.builtin.service:
    name: sshd
    state: restarted
  listen: "restart_sshd"
