# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
- name: "Start pf"
  listen: "start_pf"
  ansible.builtin.service:
    name: pf
    state: started

- name: "Reload pf.conf"
  listen: "reload_pf_conf"
  ansible.builtin.service:
    name: pf
    state: reloaded
  async: 10
  poll: 0
  register: base_reload_pf_conf_job

- name: "Wait for pf to reload"
  listen: "reload_pf_conf"
  ansible.builtin.async_status:
    jid: "{{ base_reload_pf_conf_job.ansible_job_id }}"
  retries: 10
  register: base_reload_pf_conf_result
  until: base_reload_pf_conf_result is finished

- name: "Start pflog"
  listen: "start_pflog"
  ansible.builtin.service:
    name: pflog
    state: started
