# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
- name: Restart routing
  ansible.builtin.service:
    name: routing
    state: restarted
  listen: "restart_routing"

- name: Restart network
  ansible.builtin.service:
    name: network
    state: restarted
  listen: "restart_network"
