# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
# Warning: do not use ansible.builtin.service to manager PF as it affects SSH
# connections. Instead, run async tasks with command.
#
# Ref: https://superuser.com/a/1777486
# noqa command-instead-of-module command-instead-of-shell
- name: "Start pf"
  listen: "start_pf"
  ansible.builtin.shell:
    cmd: ((sleep 1; nohup service pf start ) & )
  async: 10
  poll: 0
  register: base_start_pf_job

- name: "Wait for pf to start"
  listen: "start_pf"
  ansible.builtin.async_status:
    jid: "{{ base_start_pf_job.ansible_job_id }}"
  retries: 10
  register: base_start_pf_result
  until: base_start_pf_result is finished

# noqa command-instead-of-module command-instead-of-shell
- name: "Reload pf"
  listen: "reload_pf_conf"
  ansible.builtin.shell:
    cmd: ((sleep 1; nohup service pf reload ) & )
  async: 10
  poll: 0
  register: base_reload_pf_conf_job

- name: "Wait for pf to reload"
  listen: "reload_pf_conf"
  ansible.builtin.async_status:
    jid: "{{ base_reload_pf_conf_job.ansible_job_id }}"
  retries: 10
  register: base_reload_pf_conf_result
  until: base_reload_pf_conf_result is finished

- name: "Start pflog"
  listen: "start_pflog"
  ansible.builtin.service:
    name: pflog
    state: started
