# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
- name: "Configure ZFS"
  block:
    - name: "ZFS create parent dataset {{ jail_skel_zfs_dataset | dirname }}"
      community.general.zfs:
        name: "{{ jail_skel_zfs_dataset | dirname }}"
        state: present
        extra_zfs_properties:
          # keep-sorted start
          canmount: "off"
          readonly: "on"
          # keep-sorted end
      when: >-
        jail_skel_zfs_dataset
          | dirname
          | split('/')
          | count > 1

    - name: "ZFS create skeleton dataset {{ jail_skel_zfs_dataset }}"
      community.general.zfs:
        name: "{{ jail_skel_zfs_dataset }}"
        state: present
        extra_zfs_properties:
          # keep-sorted start
          canmount: "on"
          readonly: "off"
          # keep-sorted end

    - name: "ZFS sekeleton dataset get properties"
      community.general.zfs_facts:
        name: "{{ jail_skel_zfs_dataset }}"
        type: filesystem
        properties: "name,mounted,mountpoint"
      register: jail_skel_zfs_dataset_facts

    - name: "ZFS skeleton dataset must be mounted"
      ansible.builtin.assert:
        that: >-
          jail_skel_zfs_dataset_facts.ansible_facts.ansible_zfs_datasets
            | selectattr("name", "equalto", jail_skel_zfs_dataset)
            | selectattr("mounted", "equalto", "yes")
            | count == 1
        fail_msg: "{{ jail_skel_zfs_dataset }} is not mounted"
        quiet: true

    - name: "ZFS skeleton dataset get mountpoint"
      ansible.builtin.set_fact:
        jail_skel_path: >-
          {{
            jail_skel_zfs_dataset_facts.ansible_facts.ansible_zfs_datasets
              | selectattr('name', 'equalto', jail_skel_zfs_dataset)
              | map(attribute='mountpoint')
              | first
              | default(omit)
          }}

- name: "Configure jail service"
  block:
    - name: "Create /etc/jail.conf"
      ansible.builtin.template:
        src: etc/jail.conf.j2
        dest: /etc/jail.conf
        owner: root
        group: wheel
        mode: u=rw,g=r,o=r
        validate: /usr/sbin/jail -f %s -e ' '

    - name: "Enable jail service in /etc/rc.conf.d/jail"
      community.general.sysrc:
        path: /etc/rc.conf.d/jail
        name: jail_enable
        value: true
      notify: "start_jail"

    - name: "Stop jails in reverse order in /etc/rc.conf.d/jail"
      community.general.sysrc:
        path: /etc/rc.conf.d/jail
        name: jail_reverse_stop
        value: true

- name: "Install packages"
  block:
    - name: "Install pkg keys"
      vars:
        keys_path: "{{ jail_skel_path }}/usr/share"
      block:
        - name: "Create keys folder {{ keys_path }}"
          ansible.builtin.file:
            path: "{{ keys_path }}"
            state: directory
            owner: root
            group: wheel
            mode: u=rwx,g=rx,o=rx

        - name: "Copy keys from /usr/share/keys"
          ansible.builtin.copy:
            src: /usr/share/keys
            dest: "{{ keys_path }}/"
            owner: root
            group: wheel
            mode: u=rwx,g=rx,o=rx
            remote_src: true

    - name: "Install with pkg database"
      vars:
        db_path: "{{ jail_skel_path }}/var/db/pkg/repos"
      block:
        - name: "Create pkg db at {{ db_path }}"
          ansible.builtin.file:
            path: "{{ db_path }}"
            state: directory
            owner: root
            group: wheel
            mode: u=rwx,g=rx,o=rx

        - name: "Mount metadata cache at {{ db_path }}"
          ansible.posix.mount:
            path: "{{ db_path }}"
            src: tmpfs
            fstype: tmpfs
            state: present

        - name: "Install packages to {{ jail_skel_path }}"
          community.general.pkgng:
            rootdir: "{{ jail_skel_path }}"
            name: "{{ jail_skel_default_packages | union(jail_skel_packages) | join(' ') }}"
            state: latest

        - name: "Get installed packages at {{ jail_skel_path }}"
          ansible.builtin.command:
            cmd: pkg -r {{ jail_skel_path }} leaf
          register: jail_skel_packages
          changed_when: false

        - name: "Installed packages at {{ jail_skel_path }}"
          ansible.builtin.debug:
            var: jail_skel_packages.stdout_lines

        - name: "Get template version at {{ jail_skel_path }}"
          ansible.builtin.command:
            cmd: chroot {{ jail_skel_path }} freebsd-version -u
          register: jail_skel_os_version
          changed_when: false

        - name: "Template version at {{ jail_skel_path }}"
          ansible.builtin.debug:
            msg: "userland: {{ jail_skel_os_version.stdout }}"

        # want to reuse server user_list but limit to some users, e.g. root,
        # then pass the filtered list to included user-role.
        # We can't set user_list var in include_role that would filter user_list
        # host variable since it leads to recursion.
        # Move users filter into a separate task to break the recursion:
        # 1. filter users
        # 2. set user_list equal to the filtered user list
        - name: "Collect users"
          ansible.builtin.set_fact:
            jail_skel_users: >-
              {{ user_list | selectattr('name', 'equalto', 'root') }}
            jail_skel_timezone_name: "{{ timezone_name }}"

        - name: "Configure users"
          ansible.builtin.include_role:
            name: user
          vars:
            user_chroot: "{{ jail_skel_path }}"
            user_list: "{{ jail_skel_users }}"

        - name: "Migrate syslog"
          ansible.builtin.include_role:
            name: sysrc
          vars:
            sysrc_migrate:
              name: syslogd_flags
              value: "-ss"
              from: "{{ jail_skel_path }}/etc/rc.conf"
              path: "{{ jail_skel_path }}/etc/rc.conf.d/syslogd"

        - name: "Configure timezone"
          ansible.builtin.include_role:
            name: timezone
          vars:
            timezone_chroot: "{{ jail_skel_path }}"
            timezone_name: "{{ jail_skel_timezone_name }}"

      always:
        - name: "Unmount metadata cache at {{ db_path }}"
          ansible.posix.mount:
            path: "{{ db_path }}"
            state: unmounted
