# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
- name: "Create a dataset"
  vars:
    dset: "{{ jail_skel_zfs_dataset }}/{{ jail_skel_template_name }}"
  block:
    - name: "Create dataset {{ dset }}"
      community.general.zfs:
        name: "{{ dset }}"
        state: present
        extra_zfs_properties:
          # keep-sorted start
          canmount: "on"
          readonly: "off"
          # keep-sorted end

    - name: "Get dataset {{ dset }} mount properties" # noqa name[template]
      community.general.zfs_facts:
        name: "{{ dset }}"
        type: filesystem
        properties: "name,mounted,mountpoint"
      register: jail_skel_zfs_dataset_facts

    - name: "Install packages"
      ansible.builtin.include_tasks: "create_template.yml"
      vars:
        path: >-
          {{
            jail_skel_zfs_dataset_facts.ansible_facts.ansible_zfs_datasets
              | selectattr('name', 'equalto', dset)
              | map(attribute='mountpoint')
              | first
              | default(omit)
          }}
      when: >-
        jail_skel_zfs_dataset_facts.ansible_facts.ansible_zfs_datasets
          | selectattr("name", "equalto", dset)
          | selectattr("mounted", "equalto", "yes")
          | count == 1
