" Copyright 2025 Samvel Khalatyan. All rights reserved.

" -- BASIC
syntax on
set number

" -- COLORS
set bg=dark
set colorcolumn=80
set cursorline

" -- SPACING
set tabstop=2
set softtabstop=2
set shiftwidth=2
set smartindent
set autoindent
set expandtab
au FileType go,make setlocal noexpandtab

" -- SEARCH
set hlsearch
set incsearch

" -- INVISIBLES
set listchars=eol:¬,extends:›,precedes:‹,space:░,tab:«–»,trail:•
nmap <leader>l <esc>:set list!<cr>

" -- FORMAT BUFFER.
" Set format tool
au FileType go set equalprg=goimports
" Shortcuts: entire buffer `=G`, selection `=`.
au FileType go map <leader>fc gg=G<c-o><c-o>
au FileType go imap <leader>fc <esc>gg=G<c-o><c-o>
