#!/bin/sh
#
# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

set -e

last_date=
while read prefix sha cur_date subject; do
  if [ "${last_date}" != "${cur_date}" ]; then
    echo "${cur_date}"
    last_date="${cur_date}"
  fi
  echo "$prefix $sha $subject"
done
