#!/bin/sh
#
# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

# log-bydate groups log messages by date. It skips grouping if the output is
# the output is piped. Use GITGROUP environment variable to override grouping
# decision.
#
# ENVIRONMENT
#
#   GITGROUP  disabled grouping if set to "no" or "false"
#
set -e

# nogroup removes dates from standard input and passes it ungrouped.
nogroup() {
  exec cut -d ' ' -f 1,3-
}

last_date=
last_date_count=
buf=

flush() {
  if [ -z "${last_date}" ]; then
    return
  fi
  day_of_week="$(date -j -f%Y-%m-%d "${last_date}" +%a)"
  echo "${day_of_week} ${last_date} (${last_date_count})"
  echo -e "${buf}"
}

# group groups lines in the standard input by date.
#
# The log messages must have the following format:
#
#   * DATE <suffix>
#
# for example:
#
#   * 2026-01-01 abc123 commit message
group() {
  while read prefix date suffix; do
    if [ "${last_date}" != "${date}" ]; then
      flush
      last_date="${date}"
      last_date_count=0
      buf=
    fi
    last_date_count=$((last_date_count + 1))
    buf="${buf}${buf:+\n}${prefix} ${suffix}"
  done
  flush
}

main() {
  # GITGROUP environment variable has preference to control grouping.
  #
  case "$GITGROUP" in
    [Nn][Oo] | [Ff][Aa][Ll][Ss][Ee])
      nogroup
      ;;
    [Yy][Ee][Ss] | [Tt][Rr][Uu][Ee])
      group
      ;;
    *)
      echo >&2 "invalid GITGROUP value '$GITGROUP' - must be yes/no or true/false"
      exit 1
      ;;
  esac
}

# Disable grouping if standard output is piped unless forced to group by
# GITGROUP environment variable.
if ! [ -t 1 ]; then
  : ${GITGROUP:=no}
fi
: ${GITGROUP:=yes}

main | less -FR
