# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

default_install_hook_types: [pre-commit, commit-msg]
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: check-added-large-files
  - id: check-executables-have-shebangs
  - id: check-shebang-scripts-are-executable
  - id: check-yaml
  - id: end-of-file-fixer
    exclude: |
      (?x)^(
         .*/testdata/.*
        |.*\\.diff
        |.*\\.patch
      )$
  - id: trailing-whitespace
    exclude: |
      (?x)^(
         .*/testdata/.*
        |.*\\.diff
        |.*\\.patch
      )$

- repo: local
  hooks:

  # Bazel
  - id: bzl-fmt
    name: "Bazel format"
    description: "format Bazel files"
    entry: buildifier
    language: system
    types_or: [bazel]
    args:
    - "-mode=fix"
    - "-lint=fix"
  - id: bzl-lint
    name: "Bazel lint"
    description: "lint Bazel files"
    entry: buildifier
    language: system
    types_or: [bazel]
    args:
    - "-mode=diff"
    - "-lint=warn"

  # C++
  - id: cc-fmt
    name: "C++ format"
    description: "format C/C++ files with clang-format"
    entry: clang-format21 -i
    language: system
    types_or: [c++, c]
    args: ["-style=file"]
    exclude: |
      (?x)^(
        nvim/plugin/lab-skeleton/share/.*
      )$
  - id: cc-tidy
    name: "C++ tidy"
    description: "tidy C/C++ files with clang-tidy"
    entry: clang-tidy21
    language: system
    types_or: [c++, c]
    args: ["--fix"]
    exclude: |
      (?x)^(
        nvim/plugin/lab-skeleton/share/.*
      )$

  # Go
  - id: go-fmt
    name: "Go format"
    description: "format Go files"
    entry: goimports
    language: system
    types_or: [go]
    exclude: |
      (?x)^(
         .*\.pb\.go
        |nvim/plugin/lab-skeleton/share/new.*
      )$
    args: ["-w"]
  - id: go-doc
    name: "Go doc"
    description: "Go entities must have documentation"
    entry: check-godoc
    language: system
    types_or: [go]
    pass_filenames: true
    exclude: |
      (?x)^(
         .*/testdata/.*
        |nvim/plugin/lab-skeleton/share/new.*
      )$
  - id: go-fix
    name: "Go fix"
    description: "fix Go code with static analysis"
    entry: ./check/go-fix
    language: system
    types_or: [go]
    exclude: |
      (?x)^(
         .*\.pb\.go
        |nvim/plugin/lab-skeleton/share/new.*
      )$
  - id: go-vet
    name: "Go vet"
    description: "static analysis of Go code"
    entry: ./check/go-vet
    language: system
    types_or: [go]
    exclude: |
      (?x)^(
         .*\.pb\.go
        |nvim/plugin/lab-skeleton/share/new.*
      )$
  - id: go-staticcheck
    name: "Go staticcheck"
    description: "static analysis of Go code using github.com/dominikh/go-tools"
    entry: ./check/go-staticcheck
    language: system
    types_or: [go]
    exclude: |
      (?x)^(
         .*\.pb\.go
        |nvim/plugin/lab-skeleton/share/new.*
      )$
  - id: go-fieldalignment
    name: "Go align fields"
    description: "align structure fields to take less memory x/tools/go/analysis/passes/fieldalignment"
    entry: ./check/go-fieldalignment
    language: system
    types_or: [go]
    exclude: |
      (?x)^(
         .*\.pb\.go
        |.*_test\.go
        |nvim/plugin/lab-skeleton/share/new.*
      )$
  - id: go-test
    name: "Go test"
    description: "run Go tests for changes packages"
    entry: env CHECKGOTESTPARALLEL=yes check-go-test
    language: system
    types_or: [go]
    pass_filenames: true
    exclude: |
      (?x)^(
        nvim/plugin/lab-skeleton/share/new.*
      )$
    verbose: true

  # HTML
  - id: html-fmt
    name: "HTML format"
    description: "format HTML files"
    entry: prettier
    language: system
    types_or: [html, json]
    args: ["-w"]

  # Lua
  - id: lua-fmt
    name: "Lua format"
    description: "format Lua files"
    entry: stylua
    language: system
    types_or: [lua]
  - id: lua-lint
    name: "Lua lint"
    description: "lint Lua files"
    entry: luacheck
    language: system
    types_or: [lua]

  # Makefiles
  - id: make-lint
    name: "Make lint"
    description: "lint Makefiles on FreeBSD"
    entry: ./check/make-lint
    language: system
    types_or: [makefile]
    exclude: |
      (?x)^(
        book/ostep/.*/Makefile
      )$

  # Markdown
  - id: md-fmt
    name: "Markdown format"
    description: "format Markdown files"
    entry: markdownfmt
    language: system
    types_or: [markdown]
    args:
    - "-soft-wraps"
    - "-w"

  # Protocol buffers
  - id: proto-fmt
    name: "Proto format"
    description: "format Proto files"
    entry: clang-format21 -i
    language: system
    types_or: [proto]
    args: ["-style=file"]
  - id: proto-doc
    name: "Proto documentation"
    description: "Proto entities must have documentation"
    entry: check-pbdoc
    language: system
    types_or: [proto]
  - id: proto-nextid
    name: "Proto next id"
    description: "validate next-id comment in Proto messages if set"
    entry: check-nextid
    language: system
    types_or: [proto]
  - id: txtpb-fmt
    name: "Proto text format"
    description: "format text Proto files"
    entry: txtpbfmt
    language: system
    types: [textproto]
    exclude: "testdata"
    args: ["-skip_all_colons"]

  # Shell
  - id: sh-fmt
    name: "Shell format"
    entry: shfmt
    language: system
    types_or: [shell]
    exclude_types: [csh, tcsh]
    args:
    # keep-sorted start
    - "--binary-next-line"
    - "--case-indent"
    - "--indent=2"
    - "--posix"
    - "--write"
    # keep-sorted end
  - id: sh-noext
    name: "Shell exec no ext"
    description: "no extension in shell executables"
    entry: "shell executable should not have extension"
    language: fail
    types: [shell, executable]
    files: |
      (?x)^(
        .*\\.\\w*sh
      )$

  # YAML
  - id: yaml-fmt
    name: "YAML format"
    description: "format YAML files"
    entry: yamlfmt
    language: system
    types_or: [yaml]

  # ... everything else
  - id: issue
    name: "Issue"
    description: "a commit message must have an issue set"
    entry: check-issue
    language: system
    stages: [commit-msg]
  - id: license
    name: "License"
    description: "a file must have a license block"
    entry: ./check/cmd/check-license/check_license
    language: system
    stages: [pre-commit]
    exclude_types: [json]
    exclude: |
      (?x)^(
         MODULE\\.bazel\\.lock
        |go\.(mod|sum)
        |.*/(test)?data/.*
        |.*_string\.go
        |.*\\.pb\\.go
        |.*\\.diff
        |.*\\.patch
        |home/vim/templates/skel.*
        |nvim/plugin/lab-skeleton/share/new.*
      )$
  - id: nosubmit
    name: "No-submit"
    description: "NOSUMIT should not be set"
    entry: check-nosubmit
    language: system
  - id: todo
    name: "Todo lint"
    description: "a TODO comment must include an issue"
    entry: check-todo
    language: system
    exclude: |
      (?x)^(
         .*\\.diff
        |.*\\.patch
      )$
  - id: keep-sorted
    name: "Keep sorted"
    description: "keep lines sorted"
    entry: keep-sorted
    language: system
  - id: no-binary
    name: "No binaries"
    description: "binaries are not allowed"
    entry: "binaries are not allowed"
    language: fail
    types_or: [binary]
  - id: typos
    name: "Typos"
    description: "check typos"
    entry: typos
    language: system
    types: [text]
    exclude: |
      (?x)^(
         .*\\.diff
        |infra/net\\.lab.*\\.conf
      )$
