#!/bin/sh
#
# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

bazel run :gazelle

{
  compdb //iq/... //x/abseil/... \
    | sed \
      -e 's,"/usr/bin/clang-21","/usr/local/bin/clang21",' \
      -e 's,"/usr/lib/llvm-21","/usr/local/llvm21",' \
      -e "s,\"external/abseil-cpp+\",\"$(readlink ./external/abseil-cpp+)\","
} >compile_commands.json
