// Code generated by "stringer -type=Action"; DO NOT EDIT.

package test

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ActionUnspecified-0]
	_ = x[ActionStart-1]
	_ = x[ActionRun-2]
	_ = x[ActionPause-3]
	_ = x[ActionContinue-4]
	_ = x[ActionPass-5]
	_ = x[ActionBenchmark-6]
	_ = x[ActionFail-7]
	_ = x[ActionOutput-8]
	_ = x[ActionSkip-9]
}

const _Action_name = "ActionUnspecifiedActionStartActionRunActionPauseActionContinueActionPassActionBenchmarkActionFailActionOutputActionSkip"

var _Action_index = [...]uint8{0, 17, 28, 37, 48, 62, 72, 87, 97, 109, 119}

func (i Action) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Action_index)-1 {
		return "Action(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Action_name[_Action_index[idx]:_Action_index[idx+1]]
}
