# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
- name: Make homedir for users
  ansible.builtin.include_tasks: "_mkhomedir.yml"
  loop: "{{ zfs_mkhomedir_users }}"
  loop_control:
    loop_var: _user
