// Code generated by "stringer -type AllocateMode -linecomment"; DO NOT EDIT.

package heap

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AllocateModeFirstFit-1]
	_ = x[AllocateModeBestFit-2]
	_ = x[AllocateMostWorstFit-3]
}

const _AllocateMode_name = "first-fitbest-fitworst-fit"

var _AllocateMode_index = [...]uint8{0, 9, 17, 26}

func (i AllocateMode) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_AllocateMode_index)-1 {
		return "AllocateMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AllocateMode_name[_AllocateMode_index[idx]:_AllocateMode_index[idx+1]]
}
