// Code generated by "stringer -type CoalesceMode -linecomment"; DO NOT EDIT.

package heap

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CoalesceModeNoop-1]
	_ = x[CoalesceModeForward-2]
	_ = x[CoalesceModeBackward-3]
	_ = x[CoalesceModeBidirectional-4]
}

const _CoalesceMode_name = "noopforwardbackwardbidi"

var _CoalesceMode_index = [...]uint8{0, 4, 11, 19, 23}

func (i CoalesceMode) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_CoalesceMode_index)-1 {
		return "CoalesceMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CoalesceMode_name[_CoalesceMode_index[idx]:_CoalesceMode_index[idx+1]]
}
