" Copyright 2025 Samvel Khalatyan. All rights reserved.

" -- BASIC
syntax on
set number"

" -- COLORS
set bg=dark
set colorcolumn=80
set cursorline
colorscheme lab

" -- SPACING
set tabstop=2
set softtabstop=2
set shiftwidth=2
set smartindent
set autoindent
set expandtab
au FileType go,make setlocal noexpandtab

" -- SEARCH
set hlsearch
set incsearch

" -- INVISIBLES
set listchars=eol:¬,extends:›,precedes:‹,space:░,tab:«–»,trail:•
nmap <leader>l <esc>:set list!<cr>

" -- SPELL CHECKER
au FileType markdown setlocal spell

filetype plugin on

for f in split(glob($HOME . '/.vimrc.d/*.vim'), '\n')
  execute 'source ' . f
endfor
