# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
# keep-sorted start
ansible_jexec_over_ssh_jail_name: ldap
openldap_server_addr: 10.0.0.3
openssl_gen_common_name: ldap.lab.net
openssl_gen_crt: "/usr/local/etc/openldap/ssl/ldap.crt"
openssl_gen_group: ldap
openssl_gen_owner: ldap
ssh_listen_addresses:
  - 10.0.0.3
# keep-sorted end
