# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
openldap_server_entries:
  - name: root node
    dn: dc=lab,dc=net
    dc: lab
    objectClass:
      - dcObject
      - organization
    description: Research & Development lab
    o: Research Lab
  - name: people tree
    dn: ou=people,dc=lab,dc=net
    ou: people
    objectClass: organizationalUnit
    description: people in the lab
  - name: groups tree
    dn: ou=groups,dc=lab,dc=net
    ou: groups
    objectClass: organizationalUnit
    description: groups in the lab
  - name: op group
    dn: cn=op,ou=groups,dc=lab,dc=net
    cn: op
    objectClass:
      - top
      - posixGroup
    gidNumber: 1001
    memberUid: op
  - name: op user
    dn: uid=op,ou=people,dc=lab,dc=net
    cn: op
    objectClass:
      - top
      - account
      - posixAccount
    uid: op
    uidNumber: 1001
    gidNumber: 1001
    homeDirectory: /home/op
    loginShell: /bin/tcsh
    gecos: Operator
    description: Operator
  - name: skhalatyan group
    dn: cn=skhalatyan,ou=groups,dc=lab,dc=net
    cn: skhalatyan
    objectClass:
      - top
      - posixGroup
    gidNumber: 10001
    memberUid: skhalatyan
  - name: skhalatyan user
    dn: uid=skhalatyan,ou=people,dc=lab,dc=net
    cn: skhalatyan
    objectClass:
      - top
      - account
      - posixAccount
    uid: skhalatyan
    uidNumber: 10001
    gidNumber: 10001
    homeDirectory: /home/skhalatyan
    loginShell: /bin/tcsh
    description: Samvel Khalatyan account
