# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
base_vars:
  # keep-sorted start
  pkg:
    aliases:
      # keep-sorted start
      - name: outdated
        value: "version -vL="
      - name: vital
        value: 'query -e \"%V=1\" %n'
      # keep-sorted end
  users:
    # keep-sorted start
    - name: op
    - name: root
      group: wheel
      home: /root
    # keep-sorted end
  # keep-sorted end
