# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
# base_hostname sets the hostname
base_hostname: ""

# base_network_defaultrouter is the IPv4 address for the default route.
base_network_defaultrouter: ""

# base_users is a list of users to configure with tcsh(1). Each user has the
# foolowing structure:
#
#   name  string  user name
#   group string  (optional) user group (default: <name>)
#   home  string  (optional) user home folder (default /home/<name>)
base_users:
  # keep-sorted start
  - name: op
  - name: root
    group: wheel
    home: /root
  # keep-sorted end
