#!/bin/sh
#
# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

# Rsync pulls cluster configurations.
#
# SYNOPSIS
#
#   ./rsync [-h|-n] path
#
# DESCRIPTION
#
# Rsync pulls configuration files for each node that has `rsync.files-from`
# file, with a list of files to pull. The last component of the path's dirname
# identifies the host starting with top-level domain, e.g. nat.lab.bsd.
#
# OPTIONS
#
#   -h  print help and exit
#   -n  dry-run, print commands but do not run them

# keep-sorted start
FIND_PATH=./
NOOP=/usr/bin/false
# keep-sorted end

usage() {
  local cmd=${0##*/}
  cat <<EOF
usage: ${cmd} [options] [path]

options:
  -h    print help and exit
  -n    dry-run, print commands but do not run them

arguments:
  path  path to search for rsync.files-from
        default: ${FIND_PATH}
EOF
}

run() {
  echo ".. $@"
  if ${NOOP}; then
    return
  fi
  eval "$@"
}

run_rsync() {
  (
    path=${f%/*}
    cd ${path}

    remote=${PWD##*/}
    echo -- rsync ${remote}
    case "${remote}" in
      # keep-sorted start
      "laptop") # macOS
        src=/
        ;;
      "net.lab.nuc") # server
        src=op@nuc.lab.net:/
        ;;
      # keep-sorted end
      *) # jail
        jid=${remote##*.}
        src=op@nuc.lab.net:/usr/jail/${jid}/
        ;;
    esac

    run rsync -arvz --files-from=./${rsync_files_from} ${src} ./
  )
}

while getopts "hn" opt; do
  case "$opt" in
    h)
      usage
      exit
      ;;
    n)
      NOOP=/usr/bin/true
      ;;
    *)
      usage
      exit 1
      ;;
  esac
done
shift $((OPTIND - 1))

find_path=${1:-${FIND_PATH}}
rsync_files_from="rsync.files-from"
find ${find_path} -type f -name ${rsync_files_from} -maxdepth 2 \
  | sort \
  | {
    while read f; do
      run_rsync "$f"
    done
  }
