#!/bin/sh
#
# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

# Rsync pulls cluster configurations.
#
# SYNOPSIS
#
#   ./rsync [-h|-n] path
#
# DESCRIPTION
#
# Rsync pulls configuration files for each node that has `rsync.files-from`
# file, with a list of files to pull. The last component of the path's dirname
# identifies the host starting with top-level domain, e.g. nat.lab.bsd.
#
# OPTIONS
#
#   -h  print help and exit
#   -n  dry-run, print commands but do not run them

NOOP=false

# usage prints help message.
usage() {
  local cmd=${0##*/}
  cat <<EOF
usage: ${cmd} [options] [path]

options:
  -h    print help and exit
  -n    dry-run, print commands but do not run them

arguments:
  path  path to search for rsync.files-from
EOF
}

# execve executes the command using exec. If NOOP environment variable is set
# to true, then it prints the command to be executed but does not run it.
execve() {
  if command -p "${NOOP}"; then
    echo ".. $@"
    return
  fi
  exec "$@"
}

# handle_rsync_files_from handles a file rsync.files-from. It expects the file
# to be located in a folder, named after the cluster node, e.g.
#   .../net.lab.dns/rsync.files-from
handle_rsync_files_from() {
  local file=${1:?'handle_rsync_files_from: missing file'}
  local path=${file%/*}
  local remote=${path##*/}
  local jid src
  case "${remote}" in
    # keep-sorted start
    "laptop") # macOS
      src=/
      ;;
    "net.lab.nuc") # server
      src=op@nuc.lab.net:/
      ;;
    # keep-sorted end
    *) # jail
      jid=${remote##*.}
      src=op@nuc.lab.net:/usr/jail/${jid}/
      ;;
  esac

  echo "-- rsync ${remote}"
  execve rsync -arvz --files-from="${file}" "${src}" ${path}/
}

# handle_path searches for rsync.files-from at path and runs rsync if the
# file is found.
handle_path() {
  local path=${1:?'handle_path: missing path'}
  find "${path}" -type f -name rsync.files-from -maxdepth 2 \
    | sort \
    | {
      while read f; do
        handle_rsync_files_from "$f"
      done
    }
}

# main handles command options and runs path handler for every provided path
# or ./ if no path is set.
main() {
  local opt
  while getopts "hn" opt; do
    case "$opt" in
      h)
        usage
        exit 1
        ;;
      n)
        NOOP=true
        export NOOP
        ;;
      *)
        usage
        exit 1
        ;;
    esac
  done
  shift $((OPTIND - 1))

  if [ $# -eq 0 ]; then
    set -- "$PWD"
  fi

  local p seen=""
  for p; do
    case "$seen" in
      *":$p:"*)
        echo >&2 "skip duplicate path $p"
        continue
        ;;
    esac
    seen=":$p:$seen"
    handle_path "$p"
  done
}

main "$@"
