# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
# noqa name[template]
- name: >-
    User {{ user.name }} - set shell to {{ user.shell }}
    {%- if user_chroot != "" %} in {{ user_chroot }}{% endif %}
  ansible.builtin.command:
    cmd: >-
      {% if user_chroot != "" %}chroot {{ user_chroot }}{% endif %}
      chsh -s {{ user.shell }} {{ user.name }}
  register: user_chsh
  changed_when: user_chsh.rc == 0

# noqa name[template]
- name: >-
    User {{ user.name }} - copy skeleton
    {%- if user_chroot != "" %} in {{ user_chroot }}{% endif %}
  ansible.builtin.include_tasks: "copy.yml"
  vars:
    src: "{{ file }}"
    dst: >-
      {% if user_chroot != "" %}{{ user_chroot }}{% endif -%}
      {{ user.home }}/{{ file | basename | regex_replace('^dot', '', count=1) }}
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: u=rw,g=r,o=r
  loop: >-
    {{ query('fileglob', role_path ~ '/files/' ~ user.home ~ '/dot.*') | sort }}
  loop_control:
    loop_var: file
