# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
# noqa name[template]
- name: "User {{ _copy.user }} - copy {{ _copy.src | basename }}"
  ansible.builtin.copy:
    src: "{{ _copy.src }}"
    dest: "{{ _copy.dst }}"
    owner: "{{ _copy.owner }}"
    group: "{{ _copy.group }}"
    mode: "{{ _copy.mode }}"
