# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
# noqa name[template]
- name: "User {{ user.name }} - copy {{ src | basename }}"
  ansible.builtin.copy:
    src: "{{ src }}"
    dest: "{{ dst }}"
    owner: "{{ owner }}"
    group: "{{ group }}"
    mode: "{{ mode }}"
