// Copyright 2026 Samvel Khalatyan. All rights reserved.
//
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package sim

import (
	"fmt"
	"iter"
	"sort"

	"github.com/skhal/lab/book/ostep/cpu/cmd/scheduler/internal/job"
	"github.com/skhal/lab/book/ostep/cpu/cmd/scheduler/internal/scheduler"
)

// Scheduler manages jobs.
type Scheduler interface {
	// Add introduces the job to the scheduler.
	Add(scheduler.Job)

	// Next retrieves the next job to run for one cycle. The second return =
	// parameter indicates whether the scheduler was able to pick up a job.
	Next() (scheduler.Job, bool)
}

// Simulator runs a simulation of running multiple jobs with a scheduler.
type Simulator struct {
	cycler *scheduler.Cycler
	sched  Scheduler

	jobs    []*job.Job
	pending []*job.Job
}

// New creates a [Simulator] ready to run.
func New(jobs []job.Spec, s Scheduler) *Simulator {
	c := new(scheduler.Cycler)
	jj := make([]*job.Job, 0, len(jobs))
	sort.Slice(jobs, func(i, j int) bool {
		return jobs[i].Arrival < jobs[j].Arrival
	})
	for i, spec := range jobs {
		j := &job.Job{
			ID: i + 1,
			Spec: job.Spec{
				Arrival:  spec.Arrival,
				Duration: spec.Duration,
			},
		}
		jj = append(jj, j)
	}
	return &Simulator{
		cycler:  c,
		sched:   s,
		jobs:    jj,
		pending: append(([]*job.Job)(nil), jj...),
	}
}

// Stats returns average job statistics including the response, turnaround, and
// wait times.
func (s *Simulator) Stats() job.Stat {
	var avg job.Stat
	add := func(js job.Stat) {
		avg.Response += js.Response
		avg.Turnaround += js.Turnaround
		avg.Wait += js.Wait
	}
	finalize := func() {
		n := len(s.jobs)
		avg.Response /= n
		avg.Turnaround /= n
		avg.Wait /= n
	}
	for _, j := range s.jobs {
		add(j.Stat())
	}
	finalize()
	return avg
}

// Cycle emulates a CPU cycle.
type Cycle struct {
	// Num is the cycle number.
	Num int

	// Job is the job scheduled to run in this cycle.
	Job *job.Job
}

// Jobs gives access to the jobs generated by simulator.
func (s *Simulator) Jobs() []*job.Job {
	return s.jobs
}

// Run executes the simulator.
func (s *Simulator) Run() iter.Seq[Cycle] {
	return func(yield func(Cycle) bool) {
		for {
			s.addJobs()
			next, ok := s.sched.Next()
			if !ok && len(s.pending) == 0 {
				break
			}
			j := next.(*job.Job)
			j.Run()
			if !yield(Cycle{Num: s.cycler.Cycle(), Job: j}) {
				break
			}
			s.cycler.Next()
		}
	}
}

func (s *Simulator) addJobs() {
	var (
		cycle     = s.cycler.Cycle()
		lastAdded = -1
	)
	for idx, job := range s.pending {
		if n := job.Spec.Arrival; n < cycle {
			panic(fmt.Errorf("got a job with arrival %d before cycle %d", job.Spec.Arrival, cycle))
		} else if n == cycle {
			job.Init(s.cycler)
			s.sched.Add(job)
			lastAdded = idx
		} else {
			break
		}
	}
	if lastAdded >= 0 {
		s.pending = s.pending[lastAdded+1:]
	}
}
