# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
- name: Write {{ _conf_file }}
  become: true
  ansible.builtin.template:
    src: "{{ _conf_file | trim('/') }}.j2"
    dest: "{{ _conf_file }}"
    owner: root
    group: wheel
    mode: u=rw,g=r,o=r
