# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
- name: Configure pkg repositories
  vars:
    _conf_path: /usr/local/etc/pkg/repos
    _conf_files:
      - freebsd-ports.conf
      - freebsd-kmods.conf
      - freebsd-base.conf
  block:
    - name: Create {{ _conf_path }}
      become: true
      ansible.builtin.file:
        path: "{{ _conf_path }}"
        state: directory
        owner: root
        group: wheel
        mode: u=rwx,g=rx,o=rx

    - name: Write configs
      ansible.builtin.include_tasks: _configure_repo.yml
      loop: "{{ _conf_files }}"
      vars:
        _conf_file: "{{ (_conf_path, item) | path_join }}"
