# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
- name: Install nginx
  become: true
  community.general.pkgng:
    name: nginx
    state: present

- name: Configure service
  vars:
    _rc_file: /usr/local/etc/rc.conf.d/nginx
  block:
    - name: Create {{ _rc_file | dirname }}
      become: true
      ansible.builtin.file:
        path: "{{ _rc_file | dirname }}"
        state: directory
        owner: root
        group: wheel
        mode: u=rwx,g=rx,o=rx

    - name: Enable nginx
      become: true
      notify: local_pkg_start_nginx
      community.general.sysrc:
        path: "{{ _rc_file }}"
        name: nginx_enable
        value: true

- name: Configure nginx
  vars:
    _conf_file: /usr/local/etc/nginx/nginx.conf
  block:
    - name: Create {{ _conf_file }}
      become: true
      notify: local_pkg_restart_nginx
      ansible.builtin.template:
        src: usr/local/etc/nginx/nginx.conf.j2
        dest: "{{ _conf_file }}"
        owner: root
        group: wheel
        mode: u=rw,g=r,o=r
        validate: nginx -t -c %s

- name: Configure newsyslog
  vars:
    _files:
      - /var/log/nginx/access.log
      - /var/log/nginx/error.log
    _conf_file: /usr/local/etc/newsyslog.conf.d/nginx.conf
  block:
    - name: Create {{ _conf_file | dirname }}
      become: true
      ansible.builtin.file:
        path: "{{ _conf_file | dirname }}"
        state: directory
        owner: root
        group: wheel
        mode: u=rwx,g=rx,o=rx

    - name: Configure rotations
      become: true
      ansible.builtin.copy:
        src: usr/local/etc/newsyslog.conf.d/nginx.conf
        dest: "{{ _conf_file }}"
        owner: root
        group: wheel
        mode: u=rw,g=r,o=r
