# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
# user_migrate_users is a list of user names to migrate from the remote node to
# chrooted environment.
user_migrate_users:
  -

# user_migrate_rootdir is an alternate root directory for pw to operate, i.e.
# analogous to chroot (see pw(8)).
user_migrate_rootdir: ""
