# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
- name: "Add pkg alias {{ alias.name }}"
  ansible.builtin.lineinfile:
    path: "{{ pkg_conf_path }}"
    insertafter: "^ALIAS {"
    line: '    {{ alias.name }} = "{{ alias.value }}";'
