# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
- name: "Use latest branch"
  ansible.builtin.copy:
    src: usr/local/etc/pkg/repos/FreeBSD.conf
    dest: /usr/local/etc/pkg/repos/FreeBSD.conf
    owner: root
    group: wheel
    mode: u=rw,g=r,o=r
  notify: "upgrade_packages"

- name: "Add pkg aliases"
  ansible.builtin.include_tasks: "alias.yml"
  loop: "{{ pkg_aliases }}"
  loop_control:
    loop_var: _alias

- name: "Install packages {{ pkg_install }}"
  community.general.pkgng:
    name: "{{ pkg_install }}"
    state: latest
  when: pkg_install | length > 0
