# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
# sysrc_migrate defines an rc-variable to migrate from /etc/rc.conf. It expects
# the following structure:
#
#   name    string  rc-variable name
#   value   string  the value to set
#   path    string  destination rc.conf file to put the rc-variable.
#   notify  string? notification to send
sysrc_migrate: {}
