# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
# keep-sorted start
# opessl_ca_common_name is the CA identifier, use FQDN.
openssl_ca_common_name: ""
# openssl_ca_organization sets CA organization
openssl_ca_organization: ""
# openssl_ca_passphrase protects CA private key.
openssl_ca_passphrase: ""
# keep-sorted end

# sign_csr.yml variables
# keep-sorted start
# openssl_ca_sign_crt_base64 encoded certificate if any
openssl_ca_sign_crt_base64: "{{ undef(hint='base64 encoded certificate') }}"
# openssl_ca_sign_csr is the certificate sining request (CSR)
openssl_ca_sign_csr: ""
# openssl_ca_sign_host is the hostname of the CA to sign CSRs.
openssl_ca_sign_host: ""
# openssl_ca_sign_register is the name of the registered variable.
openssl_ca_sign_register: ""
# keep-sorted end
