# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
# keep-sorted start
# opessl_ca_common_name is the CA identifier, use FQDN.
openssl_ca_common_name: ""
# openssl_ca_organization sets CA organization
openssl_ca_organization: ""
# openssl_ca_passphrase protects CA private key.
openssl_ca_passphrase: ""
# keep-sorted end
