# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
# keep-sorted start
# jail_allow_chflags adds allow.chflags to the jail configuration when enabled.
jail_allow_chflags: false
# jail_bridge is the jails bridge.
jail_bridge: ""
# jail_cidr is the IP with network marsk.
jail_cidr: ""
# jail_defaultrouter sets the IP for default route.
jail_defaultrouter: ""
# jail_depend is a list of jail names that this jail depends on (see jail(8)).
jail_depend: []
# jail_mounts lists mount points to add to the jail (see mount in jail(8)).
# Each mount has the following structure:
#   path  string  absolute path to mount, e.g. "/home/op"
#   perm  string? mount permissions, e.g. "rw" (default: rw)
jail_mounts: []
# jail_name is the jail name.
jail_name: ""
# keep-sorted end
