# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
- name: "Migrate users"
  ansible.builtin.include_tasks: "migrate.yml"
  loop: "{{ user_migrate_users }}"
  loop_control:
    loop_var: user_migrate_name
