# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
- name: "Migrate users"
  migrate:
    name: "{{ item }}"
    rootdir: "{{ user_migrate_rootdir }}"
  loop: "{{ user_migrate_users }}"
