# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
- name: "Get user info for {{ user_migrate_name }}"
  # can't use ansible.builtin.user because it will create a user if the name
  # is invalid.
  ansible.builtin.command:
    cmd: "pw usershow {{ user_migrate_name }}"
  register: user_migrate_pw_usershow_job
  changed_when: false

- name: "Parse user info"
  ansible.builtin.set_fact:
    user_migrate_user:
      name: "{{ item[idx_name] }}"
      uid: "{{ item[idx_uid] }}"
      gid: "{{ item[idx_gid] }}"
      home: "{{ item[idx_home] }}"
      shell: "{{ item[idx_shell] }}"
  vars:
    # there should be only one line of the output, pick the first line of
    # stdout.
    item: >-
      {{
        user_migrate_pw_usershow_job.stdout_lines
          | first
          | split(':')
      }}
    # format: https://github.com/freebsd/freebsd-src/blob/2a4b8fd1dc070e71fbaab6f12c1c9e4452652aa7/lib/libutil/pw_util.c#L400-L403
    idx_name: 0
    idx_uid: 2
    idx_gid: 3
    idx_home: 8
    idx_shell: 9

- name: "Get supplemental groups for {{ user_migrate_user.name }}"
  ansible.builtin.command:
    cmd: "id -G {{ user_migrate_user.uid }}"
  register: user_migrate_id_groups_job
  changed_when: false

- name: "Parse supplemental groups"
  ansible.builtin.set_fact:
    user_migrate_supplemental_groups:
      # there should be only one line of the output, pick the first line of
      # stdout.
      # The output lists all groups, including primary and supplemental groups.
      # Filter out primary group using reject() to only keep supplemental
      # groups.
      supplemental_gids: >-
        {{
          user_migrate_id_groups_job.stdout_lines
            | first
            | split
            | reject('equalto', user_migrate_user.gid)
        }}

# add supplemental groups to the user info.
- name: "Set user info"
  ansible.builtin.set_fact:
    user_migrate_user: >-
      {{
        user_migrate_user
          | combine(user_migrate_supplemental_groups)
      }}

- name: "Get groups at /etc/groups"
  ansible.builtin.include_tasks: "get_groups.yml"

- name: "User groups"
  ansible.builtin.set_fact:
    user_migrate_groups: >-
      {{ user_migrate_groups | default({}) | combine({item.key: item.value}) }}
  loop: "{{ user_migrate_get_groups_result | dict2items }}"
  when: item.key in user_groups
  vars:
    user_groups: >-
      {{ [user_migrate_user.gid]
            + user_migrate_user.supplemental_gids | default([]) }}

# noqa name[template]
- name: "Get groups at {{ user_migrate_rootdir }}/etc/groups"
  ansible.builtin.include_tasks: "get_groups.yml"
  vars:
    user_migrate_get_groups_rootdir: "{{ user_migrate_rootdir }}"

- name: "Validate existing groups at {{ user_migrate_rootdir }}/etc/groups" # noqa name[template]
  ansible.builtin.assert:
    that: >-
      item.value == user_group_name
    fail_msg: "Group {{ item.key }} has name {{ item.value }}; want {{ user_group_name }}"
    quiet: true
  loop: "{{ user_migrate_get_groups_result | dict2items }}"
  when: item.key in user_groups
  vars:
    user_groups: >-
      {{ [user_migrate_user.gid]
            + user_migrate_user.supplemental_gids | default([]) }}
    user_group_name: "{{ user_migrate_groups[item.key] }}"

- name: "Validate user {{ user_migrate_user.name }} at {{ user_migrate_rootdir }}" # noqa name[template]
  ansible.builtin.command:
    cmd: "pw -R {{ user_migrate_rootdir }} usershow {{ user_migrate_user.name }}"
  register: user_migrate_check_user_job
  ignore_errors: true
  changed_when: false

- name: "Create user and groups"
  when: user_migrate_check_user_job is failed
  block:
    - name: "Create groups at {{ user_migrate_rootdir }}"
      ansible.builtin.command:
        cmd: pw -R {{ user_migrate_rootdir }} groupadd -n {{ group_name }} -g {{ group_id }}
      loop: "{{ user_groups }}"
      when: item not in user_migrate_get_groups_result.keys()
      vars:
        user_groups: >-
          {{ [user_migrate_user.gid]
                + user_migrate_user.supplemental_gids | default([]) }}
        group_id: "{{ item }}"
        group_name: "{{ user_migrate_groups[item] }}"
      register: user_migrate_create_group_job
      changed_when: user_migrate_create_group_job is succeeded

    # noqa name[template]
    - name: "Create user {{ user_migrate_user.name }} at {{ user_migrate_rootdir }}"
      ansible.builtin.command:
        cmd: >-
          pw -R {{ user_migrate_rootdir }}
            useradd
            -n {{ user_migrate_user.name }}
            -u {{ user_migrate_user.uid }}
            -g {{ user_migrate_user.gid }}
            -G {{ user_migrate_user.supplemental_gids | join(',') }}
            -d {{ user_migrate_user.home }}
            -s {{ user_migrate_user.shell }}
      register: user_migrate_create_user_job
      changed_when: user_migrate_create_user_job is succeeded
