// Copyright 2026 Samvel Khalatyan. All rights reserved.
//
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.5
// source: market.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Market struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Records *[]*Record             `protobuf:"bytes,1,rep,name=records"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Market) Reset() {
	*x = Market{}
	mi := &file_market_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Market) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Market) ProtoMessage() {}

func (x *Market) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Market) GetRecords() []*Record {
	if x != nil {
		if x.xxx_hidden_Records != nil {
			return *x.xxx_hidden_Records
		}
	}
	return nil
}

func (x *Market) SetRecords(v []*Record) {
	x.xxx_hidden_Records = &v
}

type Market_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Records []*Record
}

func (b0 Market_builder) Build() *Market {
	m0 := &Market{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Records = &b.Records
	return m0
}

type Record struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Date  *Date                  `protobuf:"bytes,1,opt,name=date"`
	xxx_hidden_Quote *Quote                 `protobuf:"bytes,2,opt,name=quote"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Record) Reset() {
	*x = Record{}
	mi := &file_market_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Record) GetDate() *Date {
	if x != nil {
		return x.xxx_hidden_Date
	}
	return nil
}

func (x *Record) GetQuote() *Quote {
	if x != nil {
		return x.xxx_hidden_Quote
	}
	return nil
}

func (x *Record) SetDate(v *Date) {
	x.xxx_hidden_Date = v
}

func (x *Record) SetQuote(v *Quote) {
	x.xxx_hidden_Quote = v
}

func (x *Record) HasDate() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Date != nil
}

func (x *Record) HasQuote() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Quote != nil
}

func (x *Record) ClearDate() {
	x.xxx_hidden_Date = nil
}

func (x *Record) ClearQuote() {
	x.xxx_hidden_Quote = nil
}

type Record_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Date  *Date
	Quote *Quote
}

func (b0 Record_builder) Build() *Record {
	m0 := &Record{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Date = b.Date
	x.xxx_hidden_Quote = b.Quote
	return m0
}

type Date struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Year        int32                  `protobuf:"varint,1,opt,name=year"`
	xxx_hidden_Month       int32                  `protobuf:"varint,2,opt,name=month"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Date) Reset() {
	*x = Date{}
	mi := &file_market_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Date) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Date) ProtoMessage() {}

func (x *Date) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Date) GetYear() int32 {
	if x != nil {
		return x.xxx_hidden_Year
	}
	return 0
}

func (x *Date) GetMonth() int32 {
	if x != nil {
		return x.xxx_hidden_Month
	}
	return 0
}

func (x *Date) SetYear(v int32) {
	x.xxx_hidden_Year = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *Date) SetMonth(v int32) {
	x.xxx_hidden_Month = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *Date) HasYear() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Date) HasMonth() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Date) ClearYear() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Year = 0
}

func (x *Date) ClearMonth() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Month = 0
}

type Date_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Year  *int32
	Month *int32
}

func (b0 Date_builder) Build() *Date {
	m0 := &Date{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Year != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Year = *b.Year
	}
	if b.Month != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Month = *b.Month
	}
	return m0
}

type Quote struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_SpComposite *Cents                 `protobuf:"bytes,1,opt,name=sp_composite,json=spComposite"`
	xxx_hidden_Dividend    *Cents                 `protobuf:"bytes,2,opt,name=dividend"`
	xxx_hidden_Earnings    *Cents                 `protobuf:"bytes,3,opt,name=earnings"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Quote) Reset() {
	*x = Quote{}
	mi := &file_market_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Quote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Quote) ProtoMessage() {}

func (x *Quote) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Quote) GetSpComposite() *Cents {
	if x != nil {
		return x.xxx_hidden_SpComposite
	}
	return nil
}

func (x *Quote) GetDividend() *Cents {
	if x != nil {
		return x.xxx_hidden_Dividend
	}
	return nil
}

func (x *Quote) GetEarnings() *Cents {
	if x != nil {
		return x.xxx_hidden_Earnings
	}
	return nil
}

func (x *Quote) SetSpComposite(v *Cents) {
	x.xxx_hidden_SpComposite = v
}

func (x *Quote) SetDividend(v *Cents) {
	x.xxx_hidden_Dividend = v
}

func (x *Quote) SetEarnings(v *Cents) {
	x.xxx_hidden_Earnings = v
}

func (x *Quote) HasSpComposite() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_SpComposite != nil
}

func (x *Quote) HasDividend() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Dividend != nil
}

func (x *Quote) HasEarnings() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Earnings != nil
}

func (x *Quote) ClearSpComposite() {
	x.xxx_hidden_SpComposite = nil
}

func (x *Quote) ClearDividend() {
	x.xxx_hidden_Dividend = nil
}

func (x *Quote) ClearEarnings() {
	x.xxx_hidden_Earnings = nil
}

type Quote_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	SpComposite *Cents
	Dividend    *Cents
	Earnings    *Cents
}

func (b0 Quote_builder) Build() *Quote {
	m0 := &Quote{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_SpComposite = b.SpComposite
	x.xxx_hidden_Dividend = b.Dividend
	x.xxx_hidden_Earnings = b.Earnings
	return m0
}

type Cents struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Cents       int32                  `protobuf:"varint,1,opt,name=cents"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Cents) Reset() {
	*x = Cents{}
	mi := &file_market_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cents) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cents) ProtoMessage() {}

func (x *Cents) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Cents) GetCents() int32 {
	if x != nil {
		return x.xxx_hidden_Cents
	}
	return 0
}

func (x *Cents) SetCents(v int32) {
	x.xxx_hidden_Cents = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *Cents) HasCents() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Cents) ClearCents() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Cents = 0
}

type Cents_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Cents *int32
}

func (b0 Cents_builder) Build() *Cents {
	m0 := &Cents{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Cents != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Cents = *b.Cents
	}
	return m0
}

var File_market_proto protoreflect.FileDescriptor

const file_market_proto_rawDesc = "" +
	"\n" +
	"\fmarket.proto\x12\x0ex.fin.internal\x1a!google/protobuf/go_features.proto\":\n" +
	"\x06Market\x120\n" +
	"\arecords\x18\x01 \x03(\v2\x16.x.fin.internal.RecordR\arecords\"_\n" +
	"\x06Record\x12(\n" +
	"\x04date\x18\x01 \x01(\v2\x14.x.fin.internal.DateR\x04date\x12+\n" +
	"\x05quote\x18\x02 \x01(\v2\x15.x.fin.internal.QuoteR\x05quote\"0\n" +
	"\x04Date\x12\x12\n" +
	"\x04year\x18\x01 \x01(\x05R\x04year\x12\x14\n" +
	"\x05month\x18\x02 \x01(\x05R\x05month\"\xa7\x01\n" +
	"\x05Quote\x128\n" +
	"\fsp_composite\x18\x01 \x01(\v2\x15.x.fin.internal.CentsR\vspComposite\x121\n" +
	"\bdividend\x18\x02 \x01(\v2\x15.x.fin.internal.CentsR\bdividend\x121\n" +
	"\bearnings\x18\x03 \x01(\v2\x15.x.fin.internal.CentsR\bearnings\"\x1d\n" +
	"\x05Cents\x12\x14\n" +
	"\x05cents\x18\x01 \x01(\x05R\x05centsB0Z&github.com/skhal/lab/x/fin/internal/pb\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_market_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_market_proto_goTypes = []any{
	(*Market)(nil), // 0: x.fin.internal.Market
	(*Record)(nil), // 1: x.fin.internal.Record
	(*Date)(nil),   // 2: x.fin.internal.Date
	(*Quote)(nil),  // 3: x.fin.internal.Quote
	(*Cents)(nil),  // 4: x.fin.internal.Cents
}
var file_market_proto_depIdxs = []int32{
	1, // 0: x.fin.internal.Market.records:type_name -> x.fin.internal.Record
	2, // 1: x.fin.internal.Record.date:type_name -> x.fin.internal.Date
	3, // 2: x.fin.internal.Record.quote:type_name -> x.fin.internal.Quote
	4, // 3: x.fin.internal.Quote.sp_composite:type_name -> x.fin.internal.Cents
	4, // 4: x.fin.internal.Quote.dividend:type_name -> x.fin.internal.Cents
	4, // 5: x.fin.internal.Quote.earnings:type_name -> x.fin.internal.Cents
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_market_proto_init() }
func file_market_proto_init() {
	if File_market_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_market_proto_rawDesc), len(file_market_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_market_proto_goTypes,
		DependencyIndexes: file_market_proto_depIdxs,
		MessageInfos:      file_market_proto_msgTypes,
	}.Build()
	File_market_proto = out.File
	file_market_proto_goTypes = nil
	file_market_proto_depIdxs = nil
}
