// Code generated by "stringer -type=Instruction -linecomment"; DO NOT EDIT.

package scheduler

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[InstructionCPU-1]
	_ = x[InstructionIO-2]
	_ = x[InstructionIODone-3]
}

const _Instruction_name = "cpuioiod"

var _Instruction_index = [...]uint8{0, 3, 5, 8}

func (i Instruction) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_Instruction_index)-1 {
		return "Instruction(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Instruction_name[_Instruction_index[idx]:_Instruction_index[idx+1]]
}
