// Code generated by "stringer -type=ProcessState -linecomment"; DO NOT EDIT.

package scheduler

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ProcessStateBlocked-1]
	_ = x[ProcessStateInitial-2]
	_ = x[ProcessStateReady-3]
	_ = x[ProcessStateRunning-4]
	_ = x[ProcessStateZombie-5]
}

const _ProcessState_name = "blkinirdyrunok"

var _ProcessState_index = [...]uint8{0, 3, 6, 9, 12, 14}

func (i ProcessState) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_ProcessState_index)-1 {
		return "ProcessState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ProcessState_name[_ProcessState_index[idx]:_ProcessState_index[idx+1]]
}
