// Code generated by "stringer -type=kind -linecomment"; DO NOT EDIT.

package check

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[kindConst-1]
	_ = x[kindField-2]
	_ = x[kindFunc-3]
	_ = x[kindMethod-4]
	_ = x[kindType-5]
	_ = x[kindVar-6]
}

const _kind_name = "constfieldfuncmethodtypevar"

var _kind_index = [...]uint8{0, 5, 10, 14, 20, 24, 27}

func (i kind) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_kind_index)-1 {
		return "kind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _kind_name[_kind_index[idx]:_kind_index[idx+1]]
}
