# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
# timezone_name is the name of the timezonek, e.g. America/Chicago.
timezone_name: ""
