# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

# VARIABLES
#
# bridge struct {
#   // name is the bridge name, e.g. bridge0.
#   name string
#
#   // cidr is the bridge ip with sub-network, e.g. 1.2.3.4/24
#   cidr string
#
#   // memb is the member interface to add to the bridge (optional).
#   memb
#
#   // desc is the bridge description (optional).
#   desc
# }
---
- name: "Update /etc/rc.conf.d/network - add {{ bridge.name }}"
  community.general.sysrc:
    path: /etc/rc.conf.d/network
    name: cloned_interfaces
    state: value_present
    value: "{{ bridge.name }}"
  notify: "restart_network"

- name: "Update /etc/rc.conf.d/network - configure {{ bridge.name }}"
  community.general.sysrc:
    path: /etc/rc.conf.d/network
    name: "ifconfig_{{ bridge.name }}"
    # noqa jinja[spacing]
    value: >-
      inet {{ bridge.cidr }}
      {%- for m in bridge.get('addm', []) %} addm {{ m }}{% endfor %}
      up
      {%- if 'desc' in bridge %} desc {{ bridge.desc }}{% endif %}
  notify: "restart_network"
