# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
- name: "Add {{ base_bridge.name }}"
  community.general.sysrc:
    path: /etc/rc.conf.d/network
    name: cloned_interfaces
    state: value_present
    value: "{{ base_bridge.name }}"
  notify: "restart network"

- name: "Configure {{ base_bridge.name }}"
  community.general.sysrc:
    path: /etc/rc.conf.d/network
    name: "ifconfig_{{ base_bridge.name }}"
    value: "inet {{ base_bridge.ip }} addm {{ base_bridge.member_iface }} up descr {{ base_bridge.description }}"
  notify: "restart network"
