# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
- name: Use latest packages
  ansible.builtin.import_tasks: "pkg_latest.yml"

- name: Add pkg alias
  ansible.builtin.import_tasks: "pkg_alias.yml"
  vars:
    base_pkg:
      alias:
        name: outdated
        value: "version -vL="

- name: Add pkg alias
  ansible.builtin.import_tasks: "pkg_alias.yml"
  vars:
    base_pkg:
      alias:
        name: vital
        value: 'query -e \"%V=1\" %n'

- name: Install NeoVim
  community.general.pkgng:
    name: neovim
    state: latest
