# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
- name: Send daily logs to /var/log/daily.log
  community.general.sysrc:
    path: /etc/periodic.conf
    name: daily_output
    value: /var/log/daily.log
