# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
- name: Migrate sshd_enable
  ansible.builtin.import_tasks: "sysrc_migrate.yml"
  vars:
    base_sysrc:
      migrate:
        name: sshd_enable
        path: /etc/rc.conf.d/sshd

- name: Update configuration
  block:
    - name: Listen on bridge interfaces
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        line: "ListenAddress={{ ansible_facts[item].ipv4 | map(attribute='address') | flatten | first }}"
      loop: "{{ ansible_facts.interfaces | select('match', '^bridge') }}"
      notify: "restart sshd"

    - name: Allow op
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        line: "AllowUsers=op"
      notify: "restart sshd"
