# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
- name: "Migrate syslogd_flags"
  ansible.builtin.import_tasks: "sysrc_migrate.yml"
  vars:
    migrate:
      name: syslogd_flags
      path: /etc/rc.conf.d/syslogd

- name: "Enable console logs"
  ansible.builtin.lineinfile:
    path: /etc/syslog.conf
    regexp: "^#(console.info.*)$"
    line: "\\1"
    backrefs: true
  notify: "restart syslogd"
