# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
- name: Remove defaultrouter
  community.general.sysrc:
    name: defaultrouter
    state: absent

- name: Add defaultrouter
  community.general.sysrc:
    path: /etc/rc.conf.d/routing
    name: defaultrouter
    value: "{{ base_routing.router_ip }}"
  notify: "restart routing"
