# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
- name: Configure users
  ansible.builtin.import_tasks: "sub_users.yml"
  tags: users

- name: Configure autoboot
  ansible.builtin.import_tasks: "sub_autoboot.yml"
  tags: autoboot

- name: Configure dumpdev
  ansible.builtin.import_tasks: "sub_dumpdev.yml"
  tags: dumpdev

- name: Configure moused
  ansible.builtin.import_tasks: "sub_moused.yml"
  tags: moused

- name: Configure powerd
  ansible.builtin.import_tasks: "sub_powerd.yml"
  tags: powerd

- name: Configure zfs
  ansible.builtin.import_tasks: "sub_zfs.yml"
  tags: zfs
