# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
- name: Remove moused_nondefault_enable
  community.general.sysrc:
    name: moused_nondefault_enable
    state: absent

- name: Add moused_nondefault_enable
  community.general.sysrc:
    path: /etc/rc.conf.d/moused
    name: moused_nondefault_enable
    value: false
