# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
- name: Configure autoboot
  ansible.builtin.import_tasks: "main_autoboot.yml"
  tags: autoboot

- name: Configure hostname
  ansible.builtin.import_tasks: "main_hostname.yml"
  tags: hostname

- name: Configure moused
  ansible.builtin.import_tasks: "main_moused.yml"
  tags: moused

- name: Configure powerd
  ansible.builtin.import_tasks: "main_powerd.yml"
  tags: powerd

- name: Configure routing
  ansible.builtin.import_tasks: "main_routing.yml"
  tags: routing

- name: Configure packages
  ansible.builtin.import_tasks: "main_pkg.yml"
  tags: pkg

- name: Configure syslog
  ansible.builtin.import_tasks: "main_syslog.yml"
  tags: syslog

- name: Configure NTP
  ansible.builtin.import_tasks: "main_ntp.yml"
  tags: ntp

- name: Configure SSH
  ansible.builtin.import_tasks: "main_ssh.yml"
  tags: ssh

- name: Configure periorid
  ansible.builtin.import_tasks: "main_periodic.yml"
  tags: periodic

- name: Configure periorid
  ansible.builtin.import_tasks: "main_zfs.yml"
  tags: zfs

- name: Configure packet filter
  ansible.builtin.import_tasks: "main_pf.yml"
  tags: pf
