# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
- name: Configure users
  ansible.builtin.include_tasks: "user_config.yml"
  loop:
    - name: root
      group: wheel
      home: /root
    - name: op
  vars:
    user:
      name: "{{ item.name }}"
      group: "{{ item.group is defined | ternary(item.group, item.name) }}"
      home: "{{ item.home is defined | ternary(item.home, '/home/' + item.name) }}"
