# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
- name: "Use latest branch"
  ansible.builtin.copy:
    src: ./files/usr/local/etc/pkg/repos/FreeBSD.conf
    dest: /usr/local/etc/pkg/repos/FreeBSD.conf
    owner: root
    group: wheel
    mode: u=rw,g=r,o=r
  notify: "upgrade packages"
