# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
- name: "Add alias - {{ base_pkg.alias.name }}"
  ansible.builtin.lineinfile:
    path: /usr/local/etc/pkg.conf
    insertafter: "^ALIAS {"
    line: '    {{ base_pkg.alias.name }} = "{{ base_pkg.alias.value }}";'
