# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

# VARIABLES
#
# alias struct {
#   // name is the alias name.
#   name string
#
#   // value is the alias expansion (aka arguments in `pkg alias`).
#   value string
# }
---
- name: "Add alias {{ alias.name }}"
  ansible.builtin.lineinfile:
    path: /usr/local/etc/pkg.conf
    insertafter: "^ALIAS {"
    line: '    {{ alias.name }} = "{{ alias.value }}";'
