# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
- name: "Clean /etc/rc.conf - remove ifconfig_{{ base_network_ethernet_if }}"
  community.general.sysrc:
    name: "ifconfig_{{ base_network_ethernet_if }}"
    state: absent

- name: "Update /etc/rc.conf.d/network - add ifconfig_{{ base_network_ethernet_if }}"
  community.general.sysrc:
    path: /etc/rc.conf.d/network
    name: "ifconfig_{{ base_network_ethernet_if }}"
    value: up
  notify: "restart_network"

- name: Configure bridges
  ansible.builtin.include_tasks: "ifconfig_bridge.yml"
  loop: "{{ base_network_bridges }}"
  loop_control:
    loop_var: bridge
