# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

# VARIABLES
#
# base_vars struct {
#   // users is a list of users to configure on the system.
#   users []struct {
#     // name is the user name.
#     name string
#
#     // group is the user group. Defaults to user.name if not set.
#     group string?
#
#     // home is the user home folder. Default to "/home/<user.name>" if not
#     // set.
#     home string?
#   }
# }
---
- name: "Configure users"
  ansible.builtin.include_tasks: "user_config.yml"
  loop: "{{ base_vars.users }}"
  vars:
    user:
      name: "{{ item.name }}"
      group: "{{ item.group is defined | ternary(item.group, item.name) }}"
      home: "{{ item.home is defined | ternary(item.home, '/home/' + item.name) }}"
