# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
- name: "Update rc-config"
  block:
    - name: "Migrate ntpd_enable"
      ansible.builtin.include_tasks: "sysrc_migrate.yml"
      vars:
        migrate:
          name: ntpd_enable
          value: true
          path: /etc/rc.conf.d/ntpd

    - name: "Migrate ntpd_sync_on_start"
      ansible.builtin.include_tasks: "sysrc_migrate.yml"
      vars:
        migrate:
          name: ntpd_sync_on_start
          value: true
          path: /etc/rc.conf.d/ntpd

- name: "Update configuration"
  block:
    - name: "NTP config - ignore wildcard interface"
      ansible.builtin.lineinfile:
        path: /etc/ntp.conf
        line: interface ignore wildcard
      notify: "restart_ntpd"

    - name: "NTP config - listen on loopback"
      ansible.builtin.lineinfile:
        path: /etc/ntp.conf
        line: interface listen 127.0.0.1
      notify: "restart_ntpd"
