# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
- name: "Enable gateway"
  community.general.sysrc:
    path: /etc/rc.conf.d/routing
    name: gateway_enable
    value: true
  notify: "restart_routing"

- name: "Enable pflog"
  community.general.sysrc:
    path: /etc/rc.conf.d/pflog
    name: pflog_enable
    value: true
  notify: "start_pflog"

- name: "Enable pf"
  community.general.sysrc:
    path: /etc/rc.conf.d/pf
    name: pf_enable
    value: true
  notify: "start_pf"
