# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
- name: "Migrate ifconfig_{{ base_network_ethernet_if }}"
  ansible.builtin.include_tasks: "sysrc_migrate.yml"
  vars:
    migrate:
      name: "ifconfig_{{ base_network_ethernet_if }}"
      value: up
      path: /etc/rc.conf.d/network
      notify: "restart_network"

- name: Configure bridges
  ansible.builtin.include_tasks: "ifconfig_bridge.yml"
  loop: "{{ base_network_bridges }}"
  loop_control:
    loop_var: bridge
