# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

# VARIABLES
#
# router struct {
#   // ip is the default router's IP address.
#   ip string
# }
---
- name: "Remove defaultrouter from /etc/rc.conf"
  community.general.sysrc:
    name: defaultrouter
    state: absent

- name: Set defaultrouter to {{ router.ip }}
  community.general.sysrc:
    path: /etc/rc.conf.d/routing
    name: defaultrouter
    value: "{{ router.ip }}"
  notify: "restart_routing"
