# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

# VARIABLES
#
# network struct {
#   // ethernet_iface is the interface name of ethernet card, e.g. igc0.
#   ethernet_iface string
#
#   // bridges is a list of bridges to setup. See ifconfig_bridge.yml for
#   // the bridge structure schema.
#   bridges []struct
# }
---
- name: "Remove ifconfig_{{ network.ethernet_iface }}"
  community.general.sysrc:
    name: "ifconfig_{{ network.ethernet_iface }}"
    state: absent

- name: "Add ifconfig_{{ network.ethernet_iface }}"
  community.general.sysrc:
    path: /etc/rc.conf.d/network
    name: "ifconfig_{{ network.ethernet_iface }}"
    value: up
  notify: "restart_network"

- name: Configure bridges
  ansible.builtin.include_tasks: "ifconfig_bridge.yml"
  vars:
    bridge:
      name: "{{ item.name }}"
      ip: "{{ item.ip }}"
      member: "{{ item.member_iface }}"
      descr: "{{ item.description }}"
  loop: "{{ network.bridges }}"
