# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
- name: "Migrate moused_nondefault_enable"
  ansible.builtin.include_tasks: "sysrc_migrate.yml"
  vars:
    migrate:
      name: moused_nondefault_enable
      path: /etc/rc.conf.d/moused
      value: false
