# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
- name: "Migrate defaultrouter"
  ansible.builtin.include_tasks: "sysrc_migrate.yml"
  vars:
    migrate:
      name: defaultrouter
      value: "{{ base_network_defaultrouter }}"
      path: /etc/rc.conf.d/routing
      notify: "restart_routing"
