# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

# VARIABLES
#
# migrate struct {
#   // name is the rc-variable name to migrate.
#   name string
#
#   // value is the rc-variable value to set.
#   value string
#
#   // path is the destination rc.conf file to place the variable to.
#   path string
#
#   // notify is the optional notification to send.
#   notify string?
# }
---
- name: "Migrate rc-var"
  block:
    - name: "Update /etc/rc.conf - remove {{ migrate.name }}"
      community.general.sysrc:
        name: "{{ migrate.name }}"
        state: absent

    # noqa: name[template]
    - name: "Update {{ migrate.path }} - set {{ migrate.name }}"
      community.general.sysrc:
        name: "{{ migrate.name }}"
        value: "{{ migrate.value }}"
        path: "{{ migrate.path }}"
      notify: "{{ migrate.notify | default(omit) }}"
