# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

# VARIABLES
#
# migrate struct {
#   // name is the rc-variable name to migrate.
#   name string
#
#   // path is the destination rc.conf file to place the variable to.
#   path string
# }
---
- name: "Migrate rc-vars"
  block:
    # noqa: var-naming[no-role-prefix] name[template]
    - name: "Retrieve {{ migrate.name }} from /etc/rc.conf"
      ansible.builtin.command:
        cmd: "sysrc -n {{ migrate.name }}"
      register: migrate_value
      changed_when: false
      check_mode: false

    - name: "Remove {{ migrate.name }} from /etc/rc.conf"
      community.general.sysrc:
        name: "{{ migrate.name }}"
        state: absent

    # noqa: name[template]
    - name: "Store {{ migrate.name }} in {{ migrate.path }}"
      community.general.sysrc:
        name: "{{ migrate.name }}"
        value: "{{ migrate_value.stdout }}"
        path: "{{ migrate.path }}"
      when: migrate_value is succeeded
