# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

# VARIABLES
#
# user struct {
#   // name is the files' user ownership.
#   name string
#
#   // group is the files' group ownership.
#   group string
#
#   // home is the user home folder.
#   home string
# }
---
- name: "Setup users with tcsh"
  block:
    - name: "Change shell to tcsh for {{ user.name }}"
      ansible.builtin.user:
        name: "{{ user.name }}"
        shell: /bin/tcsh

    - name: "Copy cshrc for {{ user.name }}"
      ansible.builtin.copy:
        src: ./files/{{ user.home }}/dot.cshrc
        dest: "{{ user.home }}/.cshrc"
        owner: "{{ user.name }}"
        group: "{{ user.group }}"
        mode: u=rw,g=r,o=r
