# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
- name: "Update {{ _rc_var.name }}"
  become: true
  community.general.sysrc:
    name: "{{ _rc_var.name }}"
    value: "{{ _rc_var.value }}"
    path: "{{ _rc_var.path | default(omit) }}"
