# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
- name: "Configure users"
  ansible.builtin.include_tasks: "configure.yml"
  vars:
    _user_default:
      group: "{{ item_user.name }}"
      home: "/home/{{ item_user.name }}"
      shell: "{{ user_default_shell }}"
    _user: "{{ _user_default | combine(item_user) }}"
  loop: "{{ user_list }}"
  loop_control:
    loop_var: item_user
