# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
pkg_install:
  # keep-sorted start
  - FreeBSD-audit-dev # incall bsm/audit.h for go-delve
  - FreeBSD-bmake # install make(1)
  - FreeBSD-clibs-dev # install C libraries for Go cgo.
  - FreeBSD-runtime-dev # install libutil.h for go-delve
  - FreeBSD-toolchain # install default C compiler to enable Go cgo.
  - FreeBSD-utilities-dev # install libprocstat.h for go-delve
  - git
  - go126
  - llvm21
  - lua-language-server
  - protobuf
  - protobuf-go
  - py312-black
  - py312-isort
  - py312-poetry
  - tmux
  - tree
  - typescript-go
  - unzip
  # keep-sorted end
