# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
- name: "Start local_unbound"
  listen: local_unbound_start
  ansible.builtin.service:
    name: local_unbound
    state: started

- name: "Restart local_unbound"
  listen: local_unbound_restart
  ansible.builtin.service:
    name: local_unbound
    state: restarted
