# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
# user_list holds users to configure. Each user has the foolowing structure:
#
#   name  string  user name
#   group string  (optional) user group (default: <name>)
#   home  string  (optional) user home folder (default /home/<name>)
#   shell string  (optional) user shell (default: <user_default_shell>)
user_list:
  -

# user_default_shell is the default shell to set for users.
user_default_shell: /bin/sh
