// Copyright 2026 Samvel Khalatyan. All rights reserved.
//
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Package scanner provides tools to access market quotes from CSV data in
// Protobuf format.
//
//	r *csv.Reader = getReader()
//	sc := scanner.NewScanner(r)
//	for sc.Next() {
//		quote := sc.Quote()
//		// handle quote
//	}
//	if err := sc.Err(); err != nil {
//		// handle error
//	}
package scanner

import (
	"encoding/csv"
	"errors"
	"fmt"
	"io"

	"github.com/skhal/lab/book/irex/csvimport/internal/parser"
	"github.com/skhal/lab/book/irex/pb"
)

var (
	// ErrSkipLines means either skip lines value is invalid or there is an
	// error in the skipped lines, e.g. inconsistent number of fields in the
	// record, i.e. cells in the row.
	ErrSkipLines = errors.New("skip lines fail")

	// ErrScan means scanning encountered error.
	ErrScan = errors.New("scan fail")
)

// Scanner provides an interface to read quotes from CSV data. It supports
// skipping first lines. Scanning stops upon the first error or EOF.
type Scanner struct {
	err   error // last error generated by Next()
	r     *csv.Reader
	quote *pb.Quote // last quote successfully parsed by Next()

	// SkipLines forces scanner to skip the first lines.
	SkipLines int

	// ScanLines is the total number of lines to scan
	ScanLines int

	lineNum int // last line number processed by Next()
}

// New creates a scanner for a csv reader. Once created,
func New(r *csv.Reader) *Scanner {
	return &Scanner{r: r}
}

// Err returns the last encountered error.
func (sc *Scanner) Err() error {
	return sc.err
}

// Next attempts to scan the next record. It skips header lines if set by
// [Scanner.SkipLines] and tries to parse the next record as a quote. It
// returns a boolean flag to indicate whether the scan was successful.
//
// If scanning encounters an error, it turns scanner into no-op state, i.e.
// further calls to Next return false.
func (sc *Scanner) Next() bool {
	if sc.err != nil {
		return false
	}
	return sc.next()
}

func (sc *Scanner) next() bool {
	if sc.lineNum == 0 {
		err := sc.skipFirstLines()
		if err == io.EOF {
			return false
		}
		if err != nil {
			if sc.lineNum == 0 {
				sc.err = fmt.Errorf("%w: %s", ErrScan, err)
			} else {
				sc.err = fmt.Errorf("%w:%d: %s", ErrScan, sc.lineNum, err)
			}
			return false
		}
	}
	if sc.ScanLines > 0 && sc.lineNum >= sc.ScanLines {
		return false
	}
	rec, err := sc.read()
	if err != nil {
		if err == io.EOF {
			return false
		}
		sc.err = fmt.Errorf("%w:%d: %s", ErrScan, sc.lineNum, err)
		return false
	}
	quote, err := parser.ParseQuote(rec)
	if err != nil {
		sc.err = fmt.Errorf("%w:%d: %w", ErrScan, sc.lineNum, err)
		return false
	}
	sc.quote = quote
	return true
}

func (sc *Scanner) skipFirstLines() error {
	if sc.SkipLines < 0 {
		return fmt.Errorf("negative skip lines %d", sc.SkipLines)
	}
	for range sc.SkipLines {
		_, err := sc.read()
		if err != nil {
			return err
		}
	}
	return nil
}

func (sc *Scanner) read() ([]string, error) {
	sc.lineNum += 1
	return sc.r.Read()
}

// Quote returns last successfully parsed quote.
func (sc *Scanner) Quote() *pb.Quote {
	return sc.quote
}
