# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
base_pkg_alias:
  name: ""
  value: ""

base_sysrc:
  migrate:
    path: ""
    name: ""

base_routing:
  router_ip: "192.168.10.1"
