# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
base_pkg_alias:
  name: ""
  value: ""

base_sysrc:
  migrate:
    path: ""
    name: ""

base_bridge:
  name: "" # bridge0
  ip: "" # 1.2.3.4/24
  member_iface: "" # igc0
  description: "" # text

base_network:
  defaultrouter_ip: "" # 1.2.3.1
  ethernet_iface: "" # igc0
  bridges:
    - name: "" # bridge0
      ip: "" # 1.2.3.4/24
      member_iface: "" # igc0
      description: "" # text
