# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
base_vars:
  network:
    defaultrouter_ip: 192.168.10.1
    ethernet_iface: igc0
    bridges:
      - name: bridge0
        ip: 192.168.10.101/24
        member_iface: igc0
        description: jail:ext
  users:
    - name: root
      group: wheel
      home: /root
    - name: op
  pkg:
    aliases:
      - name: outdated
        value: "version -vL="
      - name: vital
        value: 'query -e \"%V=1\" %n'
