// Code generated by "stringer -type=TokenKind -linecomment"; DO NOT EDIT.

package lex

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TokComm-1]
	_ = x[TokDef-2]
	_ = x[TokDiv-3]
	_ = x[TokExt-4]
	_ = x[TokIdent-5]
	_ = x[TokMinus-6]
	_ = x[TokMul-7]
	_ = x[TokNum-8]
	_ = x[TokPlus-9]
}

const _TokenKind_name = "commentdefinitiondivideexternidentifierminusmultiplynumberplus"

var _TokenKind_index = [...]uint8{0, 7, 17, 23, 29, 39, 44, 52, 58, 62}

func (i TokenKind) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_TokenKind_index)-1 {
		return "TokenKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenKind_name[_TokenKind_index[idx]:_TokenKind_index[idx+1]]
}
