// Code generated by "stringer -type=TokenKind -linecomment"; DO NOT EDIT.

package lex

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TokComm-1]
	_ = x[TokComma-2]
	_ = x[TokDef-3]
	_ = x[TokDiv-4]
	_ = x[TokExt-5]
	_ = x[TokIdent-6]
	_ = x[TokLpar-7]
	_ = x[TokMinus-8]
	_ = x[TokMul-9]
	_ = x[TokNum-10]
	_ = x[TokPlus-11]
	_ = x[TokRpar-12]
}

const _TokenKind_name = "commentcommadefinitiondivideexternidentifierleft-parenthesisminusmultiplynumberplusright-parenthesis"

var _TokenKind_index = [...]uint8{0, 7, 12, 22, 28, 34, 44, 60, 65, 73, 79, 83, 100}

func (i TokenKind) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_TokenKind_index)-1 {
		return "TokenKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenKind_name[_TokenKind_index[idx]:_TokenKind_index[idx+1]]
}
