// Copyright 2026 Samvel Khalatyan. All rights reserved.
//
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Package parse generates an Abstract Syntax Tree (AST) from a sequence of
// tokens, generated by lexer.
//
// # Context Free Grammar
//
// statement = expression
//
// expression = number
package parse
