// Copyright 2026 Samvel Khalatyan. All rights reserved.
//
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Package parse generates an Abstract Syntax Tree (AST) from a sequence of
// tokens, generated by lexer.
//
// # Context Free Grammar
//
// Goal = Expr | Func
//
// Func       = "def" Identifier "(" ")" Expr
// Identifier = Letter { ( Letter | Digit ) }
// Letter     = "a" .. "z" | "A" .. "Z"
//
// Expr = Operand | BinExpr
//
// Operand = Number | Call
//
// BinExpr = Expr Op Expr
// Op      = AddOp | MulOp
// AddOp   = "+" | "-"
// MulOp   = "*" | "/"
//
// Call = Ident "(" [ Args ] ")"
// Args = Expr { "," Expr }
package parse
