// Copyright 2026 Samvel Khalatyan. All rights reserved.
//
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Package parse generates an Abstract Syntax Tree (AST) from a sequence of
// tokens, generated by lexer.
//
// # CONTEXT FREE GRAMMAR
//
// Goal = Expr | Func | Var
//
// Func       = "def" Identifier "(" [ Params ] ")" Expr
// Identifier = Letter { ( Letter | Digit ) }
// Letter     = "a" .. "z" | "A" .. "Z"
// Digit      = "0" .. "9"
// Params     = Identifier { "," Identifier }
//
// Var = Identifier "=" Expr
//
// Expr = Operand | BinExpr
//
// Operand = Number | Call | Group
// Number  = Digit [ "." { Digit } ] | "." Digit
// Call    = Ident "(" [ Args ] ")"
// Args    = Expr { "," Expr }
// Group   = "(" Expr ")"
//
// BinExpr = Expr Op Expr
// Op      = AddOp | MulOp
// AddOp   = "+" | "-"
// MulOp   = "*" | "/"
//
// EXAMPLE
//
//	var n = 5
//
//	# comment
//	def fib(x)
//		if x < 3 then
//			1
//		else
//			fib(x-1)+fib(x-2)
//
//	fib(10)
package parse
