// Copyright 2026 Samvel Khalatyan. All rights reserved.
//
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package slices

// MapFunc transforms every item in the sequence to a new sequence of items
// generated by function f.
func MapFunc[E1, E2 any](s []E1, f func(E1) E2) []E2 {
	if s == nil {
		return nil
	}
	res := make([]E2, 0, len(s))
	for _, v := range s {
		res = append(res, f(v))
	}
	return res
}
