// Copyright 2026 Samvel Khalatyan. All rights reserved.
//
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package slices

import "iter"

// MapFunc transforms every item in the sequence to a new sequence of items
// generated by function f.
func MapFunc[E1, E2 any](seq iter.Seq[E1], f func(E1) E2) iter.Seq[E2] {
	return func(yield func(E2) bool) {
		for v := range seq {
			if !yield(f(v)) {
				break
			}
		}
	}
}
