// Copyright 2026 Samvel Khalatyan. All rights reserved.
//
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.5
// source: fooer.proto

package pb

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Fooer_Foo_FullMethodName = "/x.proto.Fooer/Foo"
)

// FooerClient is the client API for Fooer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FooerClient interface {
	Foo(ctx context.Context, in *FooRequest, opts ...grpc.CallOption) (*FooResponse, error)
}

type fooerClient struct {
	cc grpc.ClientConnInterface
}

func NewFooerClient(cc grpc.ClientConnInterface) FooerClient {
	return &fooerClient{cc}
}

func (c *fooerClient) Foo(ctx context.Context, in *FooRequest, opts ...grpc.CallOption) (*FooResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FooResponse)
	err := c.cc.Invoke(ctx, Fooer_Foo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FooerServer is the server API for Fooer service.
// All implementations must embed UnimplementedFooerServer
// for forward compatibility.
type FooerServer interface {
	Foo(context.Context, *FooRequest) (*FooResponse, error)
	mustEmbedUnimplementedFooerServer()
}

// UnimplementedFooerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFooerServer struct{}

func (UnimplementedFooerServer) Foo(context.Context, *FooRequest) (*FooResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Foo not implemented")
}
func (UnimplementedFooerServer) mustEmbedUnimplementedFooerServer() {}
func (UnimplementedFooerServer) testEmbeddedByValue()               {}

// UnsafeFooerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FooerServer will
// result in compilation errors.
type UnsafeFooerServer interface {
	mustEmbedUnimplementedFooerServer()
}

func RegisterFooerServer(s grpc.ServiceRegistrar, srv FooerServer) {
	// If the following call pancis, it indicates UnimplementedFooerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Fooer_ServiceDesc, srv)
}

func _Fooer_Foo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FooRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FooerServer).Foo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Fooer_Foo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FooerServer).Foo(ctx, req.(*FooRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Fooer_ServiceDesc is the grpc.ServiceDesc for Fooer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Fooer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "x.proto.Fooer",
	HandlerType: (*FooerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Foo",
			Handler:    _Fooer_Foo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fooer.proto",
}
