# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
servers:
  hosts:
    nuc.lab.net:
jails:
  hosts:
    # keep-sorted start
    bsd.lab.net:
    dns.lab.net:
    ldap.lab.net:
    ssl.lab.net:
    # keep-sorted end
infra:
  hosts:
    # keep-sorted start
    dns.lab.net:
    ldap.lab.net:
    ssl.lab.net:
    # keep-sorted end
dev:
  hosts:
    bsd.lab.net:
