# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
lab:
  hosts: nuc.lab.net
  vars:
    # keep-sorted start
    # ansible_async_dir is the location to store async job ids for async_status
    # to check for the job status. It is usually per-user and async jobs that
    # where run with `become_method: doas` go under root-user even if
    # become_user is not set. In result, an async_status can't find the async
    # jid unless it is run with "become_user: root".
    # To solve the issue, we place .ansible_async somewhere on the file system,
    # in user-independent location, that persists across reboots (see hier(7)).
    # https://github.com/skhal/lab/issues/325#issuecomment-4791597578
    ansible_async_dir: /var/tmp/.ansible_async
    ansible_python_interpreter: /usr/local/bin/python3
    ansible_user: op
    # keep-sorted end

    # keep-sorted start
    hostname_name: "nuc.lab.net"
    netif_clones:
      - name: bridge0
        cidr: 192.168.10.101/24
        addm:
          - igc0
        desc: jail:ext
      - name: bridge1
        cidr: 10.0.0.1/24
        desc: jail:int
    netif_ethernet_if: igc0
    pkg_install:
      - neovim
    routing_defaultrouter: 192.168.10.1
    ssh_allow_users:
      - op
    # keep-sorted end
