# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
- name: Create DNS jail
  hosts: nuc.lab.net

  gather_facts: false

  become: true
  become_method: community.general.doas

  vars:
    # keep-sorted start
    jail_bridge: bridge1
    jail_cidr: 10.0.0.2/24
    jail_defaultrouter: 10.0.0.1
    jail_name: dns
    # keep-sorted end

  roles:
    - role: jail
      tags: jail

- name: Bootstrap DNS jail
  hosts: dns.lab.net

  connection: jexec_over_ssh
  vars:
    ansible_ssh_host: nuc.lab.net
    ansible_jexec_over_ssh_jail_name: dns
    ansible_jexec_over_ssh_escalator: doas

  gather_facts: false

  become: true
  become_method: community.general.doas

  roles:
    - role: ssh
      tags: ssh

    - role: syslog
      tags: syslog

    - role: user
      tags: user

    - role: pkg
      tags: pkg

# Configure DNS server ina separate play to ensure that changes to the resolver
# do not affect handlers run by previous roles, e.g. pkg handlers upgrade
# packages but fails if bind and local_unbound roles mess up with DNS settings.
# The separate plays guarantee that the roles run independently.
- name: Configure DNS server
  hosts: dns.lab.net

  connection: jexec_over_ssh
  vars:
    ansible_ssh_host: nuc.lab.net
    ansible_jexec_over_ssh_jail_name: dns
    ansible_jexec_over_ssh_escalator: doas

  gather_facts: false

  become: true
  become_method: community.general.doas

  roles:
    - role: bind
      tags: bind

    - role: local_unbound
      tags: local_unbound
