# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
- name: Create LDAP jail
  hosts: nuc.lab.net

  gather_facts: false

  become: true
  become_method: community.general.doas

  vars:
    # keep-sorted start
    jail_bridge: bridge1
    jail_cidr: 10.0.0.3/24
    jail_defaultrouter: 10.0.0.1
    jail_name: ldap
    # keep-sorted end

  roles:
    - role: jail
      tags: jail

- name: Bootstrap LDAP jail
  hosts: ldap.lab.net

  gather_facts: false

  become: true
  become_method: community.general.doas

  roles:
    - role: ssh
      tags: ssh

    - role: syslog
      tags: syslog

    - role: user
      tags: user

    - role: pkg
      tags: pkg

- name: Configure DNS server
  hosts: ldap.lab.net

  gather_facts: false

  become: true
  become_method: community.general.doas

  roles:
    - role: local_unbound
      tags: local_unbound

- name: Configure LDAP server
  hosts: ldap.lab.net

  gather_facts: false

  become: true
  become_method: community.general.doas

  roles:
    - role: openldap
      tags: openldap
