# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
- name: Create SSL jail
  hosts: nuc.lab.net

  gather_facts: false

  become: true
  become_method: community.general.doas

  vars:
    # keep-sorted start
    jail_bridge: bridge1
    jail_cidr: 10.0.0.4/24
    jail_defaultrouter: 10.0.0.1
    jail_name: ssl
    # keep-sorted end

  roles:
    - role: jail
      tags: jail

- name: Bootstrap SSL jail
  hosts: ssl.lab.net

  gather_facts: false

  become: true
  become_method: community.general.doas

  roles:
    - role: ssh
      tags: ssh

    - role: syslog
      tags: syslog

    - role: user
      tags: user

    - role: pkg
      tags: pkg

- name: Configure DNS server
  hosts: ssl.lab.net

  gather_facts: false

  become: true
  become_method: community.general.doas

  roles:
    - role: local_unbound
      tags: local_unbound

- name: Setup Central Authority
  hosts: ssl.lab.net

  gather_facts: false

  become: true
  become_method: community.general.doas

  tasks:
    - name: Generate CA
      ansible.builtin.include_role:
        name: openssl_ca
        tasks_from: generate_ca
      tags:
        - generate-ca
        - never

- name: Fetch CA
  hosts: nuc.lab.net

  gather_facts: false

  become: true
  become_method: community.general.doas

  roles:
    - role: openssl_ca
