# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
- name: Bootstrap NUC
  hosts: nuc.lab.net

  gather_facts: false

  become: true
  become_method: community.general.doas

  tags: bootstrap

  roles:
    - role: rc
    - role: syslog
    - role: user
    - role: pkg
    - role: ntp
    - role: hostname
    - role: periodic
    - role: zfs

- name: Configure network
  hosts: nuc.lab.net

  gather_facts: false

  become: true
  become_method: community.general.doas

  tags: network

  roles:
    - role: routing
    - role: netif

- name: Configure firewall
  hosts: nuc.lab.net

  gather_facts: false

  become: true
  become_method: community.general.doas

  tags: pf

  roles:
    - role: pflog
    - role: pf

- name: Configure Services
  hosts: nuc.lab.net

  gather_facts: false

  become: true
  become_method: community.general.doas

  tags: services

  roles:
    - role: ssh
    - role: local_unbound
