# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
- name: Configure NUC
  hosts: nuc.lab.net

  gather_facts: true
  gather_subset:
    - network

  become: true
  become_method: community.general.doas

  roles:
    - role: base
      vars:
        base_network:
          defaultrouter_ip: 192.168.10.1
          ethernet_iface: igc0
          bridges:
            - name: bridge0
              ip: 192.168.10.101/24
              member_iface: igc0
              description: jail:ext
