# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
- name: Configure NUC
  hosts: nuc.lab.net

  gather_facts: false

  become: true
  become_method: community.general.doas

  roles:
    - role: rc
      tags: rc

    - role: routing
      tags: routing

    - role: netif
      tags: netif

    - role: pflog
      tags: pflog

    - role: pf
      tags: pf

    - role: syslog
      tags: syslog

    - role: ntp
      tags: ntp

    - role: hostname
      tags: hostname

    - role: periodic
      tags: periodic

    - role: user
      tags: user

    - role: zfs
      tags: zfs

    - role: ssh
      tags: ssh

    - role: pkg
      tags: pkg
