# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
- name: Import SSL jail
  ansible.builtin.import_playbook: "playbooks/jail_ssl.yml"

- name: Import DNS jail
  ansible.builtin.import_playbook: "playbooks/jail_dns.yml"

- name: Import LDAP jail
  ansible.builtin.import_playbook: "playbooks/jail_ldap.yml"
