# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

# NAME
#   setup-lab • master playbook to setup Lab cluster.
#
# SYNOPSIS
#   ansible-playbook ./setup-lab.yml
#
# DESCRIPTION
#   setup-lab configures Lab cluster, starting with the host node (a NUC
#   machine), and then proceed to virtual machines setup.
#
#   It lists plays in the expected order of execution, i.e. the N-th play
#   expects upstream plays, 0 to N-1, to be run before.
#
#   Every play has a tag with name matching the imported play name without .yml
#   suffix.
---
# bootstrap-nuc runs minimal configuration of the NUC with bare FreeBSD OS.
- name: Bootstrap NUC
  tags: bootstrap-nuc
  ansible.builtin.import_playbook: playbooks/bootstrap-nuc.yml

# create-jails creates jail skeleton and adds bare thick jails with FreeBSD
# environment.
- name: Create jails
  tags: create-jails
  ansible.builtin.import_playbook: playbooks/create-jails.yml

# bootstrap-jails runs minimal configuration of bare jails.
- name: Bootstrap jails
  tags: bootstrap-jails
  ansible.builtin.import_playbook: playbooks/bootstrap-jails.yml

# create-ca creates a local Central Authority to sign certificates.
- name: Create Certificate Authority
  tags: create-ca
  ansible.builtin.import_playbook: playbooks/create-ca.yml
