ssl {
  host.hostname = "${name}.lab.net";
  path = "/usr/jail/${name}";

  vnet;
  allow.raw_sockets;

  mount.devfs;
  devfs_ruleset = 5;

  enforce_statfs = 1;

  exec.clean;
  exec.consolelog = "/var/log/jail_${name}.log";

  exec.start    = "/bin/sh /etc/rc";
  exec.stop     = "/bin/sh /etc/rc.shutdown";
}
