// Copyright 2026 Samvel Khalatyan. All rights reserved.
//
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.5
// source: feed.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Kind lists supported feed types.
//
// Next ID: 2
type Source_Kind int32

const (
	Source_KIND_UNSPECIFIED Source_Kind = 0
	Source_KIND_RSS         Source_Kind = 1
)

// Enum value maps for Source_Kind.
var (
	Source_Kind_name = map[int32]string{
		0: "KIND_UNSPECIFIED",
		1: "KIND_RSS",
	}
	Source_Kind_value = map[string]int32{
		"KIND_UNSPECIFIED": 0,
		"KIND_RSS":         1,
	}
)

func (x Source_Kind) Enum() *Source_Kind {
	p := new(Source_Kind)
	*p = x
	return p
}

func (x Source_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Source_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_feed_proto_enumTypes[0].Descriptor()
}

func (Source_Kind) Type() protoreflect.EnumType {
	return &file_feed_proto_enumTypes[0]
}

func (x Source_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// FeedSet contains feed definitions.
//
// Next ID: 2
type FeedSet struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Feeds *[]*Feed               `protobuf:"bytes,1,rep,name=feeds"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *FeedSet) Reset() {
	*x = FeedSet{}
	mi := &file_feed_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeedSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedSet) ProtoMessage() {}

func (x *FeedSet) ProtoReflect() protoreflect.Message {
	mi := &file_feed_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *FeedSet) GetFeeds() []*Feed {
	if x != nil {
		if x.xxx_hidden_Feeds != nil {
			return *x.xxx_hidden_Feeds
		}
	}
	return nil
}

func (x *FeedSet) SetFeeds(v []*Feed) {
	x.xxx_hidden_Feeds = &v
}

type FeedSet_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Feeds []*Feed
}

func (b0 FeedSet_builder) Build() *FeedSet {
	m0 := &FeedSet{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Feeds = &b.Feeds
	return m0
}

// Feed describes an rss feed.
//
// Next ID: 2
type Feed struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Source *Source                `protobuf:"bytes,1,opt,name=source"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Feed) Reset() {
	*x = Feed{}
	mi := &file_feed_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Feed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Feed) ProtoMessage() {}

func (x *Feed) ProtoReflect() protoreflect.Message {
	mi := &file_feed_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Feed) GetSource() *Source {
	if x != nil {
		return x.xxx_hidden_Source
	}
	return nil
}

func (x *Feed) SetSource(v *Source) {
	x.xxx_hidden_Source = v
}

func (x *Feed) HasSource() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Source != nil
}

func (x *Feed) ClearSource() {
	x.xxx_hidden_Source = nil
}

type Feed_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Source *Source
}

func (b0 Feed_builder) Build() *Feed {
	m0 := &Feed{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Source = b.Source
	return m0
}

// Source definesa local or remote feed.
//
// Next ID: 4
type Source struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Source      isSource_Source        `protobuf_oneof:"source"`
	xxx_hidden_Kind        Source_Kind            `protobuf:"varint,3,opt,name=kind,enum=x.rss.cmd.rssreader.internal.Source_Kind"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Source) Reset() {
	*x = Source{}
	mi := &file_feed_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Source) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Source) ProtoMessage() {}

func (x *Source) ProtoReflect() protoreflect.Message {
	mi := &file_feed_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Source) GetFile() string {
	if x != nil {
		if x, ok := x.xxx_hidden_Source.(*source_File); ok {
			return x.File
		}
	}
	return ""
}

func (x *Source) GetUrl() string {
	if x != nil {
		if x, ok := x.xxx_hidden_Source.(*source_Url); ok {
			return x.Url
		}
	}
	return ""
}

func (x *Source) GetKind() Source_Kind {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 1) {
			return x.xxx_hidden_Kind
		}
	}
	return Source_KIND_UNSPECIFIED
}

func (x *Source) SetFile(v string) {
	x.xxx_hidden_Source = &source_File{v}
}

func (x *Source) SetUrl(v string) {
	x.xxx_hidden_Source = &source_Url{v}
}

func (x *Source) SetKind(v Source_Kind) {
	x.xxx_hidden_Kind = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *Source) HasSource() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Source != nil
}

func (x *Source) HasFile() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Source.(*source_File)
	return ok
}

func (x *Source) HasUrl() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Source.(*source_Url)
	return ok
}

func (x *Source) HasKind() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Source) ClearSource() {
	x.xxx_hidden_Source = nil
}

func (x *Source) ClearFile() {
	if _, ok := x.xxx_hidden_Source.(*source_File); ok {
		x.xxx_hidden_Source = nil
	}
}

func (x *Source) ClearUrl() {
	if _, ok := x.xxx_hidden_Source.(*source_Url); ok {
		x.xxx_hidden_Source = nil
	}
}

func (x *Source) ClearKind() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Kind = Source_KIND_UNSPECIFIED
}

const Source_Source_not_set_case case_Source_Source = 0
const Source_File_case case_Source_Source = 1
const Source_Url_case case_Source_Source = 2

func (x *Source) WhichSource() case_Source_Source {
	if x == nil {
		return Source_Source_not_set_case
	}
	switch x.xxx_hidden_Source.(type) {
	case *source_File:
		return Source_File_case
	case *source_Url:
		return Source_Url_case
	default:
		return Source_Source_not_set_case
	}
}

type Source_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Source
	//
	// Next ID: 3

	// Fields of oneof xxx_hidden_Source:
	// File defines a local feed, stored in a file.
	File *string
	// Url defines a remote feed.
	Url *string
	// -- end of xxx_hidden_Source
	// Kind defines the type of the source.
	Kind *Source_Kind
}

func (b0 Source_builder) Build() *Source {
	m0 := &Source{}
	b, x := &b0, m0
	_, _ = b, x
	if b.File != nil {
		x.xxx_hidden_Source = &source_File{*b.File}
	}
	if b.Url != nil {
		x.xxx_hidden_Source = &source_Url{*b.Url}
	}
	if b.Kind != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Kind = *b.Kind
	}
	return m0
}

type case_Source_Source protoreflect.FieldNumber

func (x case_Source_Source) String() string {
	md := file_feed_proto_msgTypes[2].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isSource_Source interface {
	isSource_Source()
}

type source_File struct {
	// File defines a local feed, stored in a file.
	File string `protobuf:"bytes,1,opt,name=file,oneof"`
}

type source_Url struct {
	// Url defines a remote feed.
	Url string `protobuf:"bytes,2,opt,name=url,oneof"`
}

func (*source_File) isSource_Source() {}

func (*source_Url) isSource_Source() {}

var File_feed_proto protoreflect.FileDescriptor

const file_feed_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"feed.proto\x12\x1cx.rss.cmd.rssreader.internal\x1a!google/protobuf/go_features.proto\"C\n" +
	"\aFeedSet\x128\n" +
	"\x05feeds\x18\x01 \x03(\v2\".x.rss.cmd.rssreader.internal.FeedR\x05feeds\"D\n" +
	"\x04Feed\x12<\n" +
	"\x06source\x18\x01 \x01(\v2$.x.rss.cmd.rssreader.internal.SourceR\x06source\"\xa7\x01\n" +
	"\x06Source\x12\x14\n" +
	"\x04file\x18\x01 \x01(\tH\x00R\x04file\x12\x12\n" +
	"\x03url\x18\x02 \x01(\tH\x00R\x03url\x12=\n" +
	"\x04kind\x18\x03 \x01(\x0e2).x.rss.cmd.rssreader.internal.Source.KindR\x04kind\"*\n" +
	"\x04Kind\x12\x14\n" +
	"\x10KIND_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bKIND_RSS\x10\x01B\b\n" +
	"\x06sourceB>Z4github.com/skhal/lab/x/rss/cmd/rssreader/internal/pb\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_feed_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_feed_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_feed_proto_goTypes = []any{
	(Source_Kind)(0), // 0: x.rss.cmd.rssreader.internal.Source.Kind
	(*FeedSet)(nil),  // 1: x.rss.cmd.rssreader.internal.FeedSet
	(*Feed)(nil),     // 2: x.rss.cmd.rssreader.internal.Feed
	(*Source)(nil),   // 3: x.rss.cmd.rssreader.internal.Source
}
var file_feed_proto_depIdxs = []int32{
	2, // 0: x.rss.cmd.rssreader.internal.FeedSet.feeds:type_name -> x.rss.cmd.rssreader.internal.Feed
	3, // 1: x.rss.cmd.rssreader.internal.Feed.source:type_name -> x.rss.cmd.rssreader.internal.Source
	0, // 2: x.rss.cmd.rssreader.internal.Source.kind:type_name -> x.rss.cmd.rssreader.internal.Source.Kind
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_feed_proto_init() }
func file_feed_proto_init() {
	if File_feed_proto != nil {
		return
	}
	file_feed_proto_msgTypes[2].OneofWrappers = []any{
		(*source_File)(nil),
		(*source_Url)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_feed_proto_rawDesc), len(file_feed_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_feed_proto_goTypes,
		DependencyIndexes: file_feed_proto_depIdxs,
		EnumInfos:         file_feed_proto_enumTypes,
		MessageInfos:      file_feed_proto_msgTypes,
	}.Build()
	File_feed_proto = out.File
	file_feed_proto_goTypes = nil
	file_feed_proto_depIdxs = nil
}
