# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

# Flavor: FreeBSD

install: .PHONY
	@./build

watch: .NOTMAIN .PHONY
	@./build -w
