# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
- name: "Migrate zfs_enable"
  ansible.builtin.include_role:
    name: sysrc
  vars:
    sysrc_migrate:
      name: zfs_enable
      value: true
      path: /etc/rc.conf.d/zfs

- name: "Update periodic"
  vars:
    _rc_file: /etc/periodic.conf
  block:
    - name: "Update {{ _rc_file }} - enable zfs scrubs"
      become: true
      community.general.sysrc:
        path: "{{ _rc_file }}"
        name: daily_scrub_zfs_enable
        value: true

    # noqa name[template]
    - name: "Update {{ _rc_file }} - set zfs scrub threshold to {{ zfs_scrub_days }} days"
      become: true
      community.general.sysrc:
        path: "{{ _rc_file }}"
        name: daily_scrub_zfs_default_threshold
        value: "{{ zfs_scrub_days }}"
