# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
- name: "Enable pflog"
  community.general.sysrc:
    path: /etc/rc.conf.d/pflog
    name: pflog_enable
    value: true
  when: pflog_enable
  notify: "start_pflog"
