# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
- name: "Install DNS server"
  block:
    - name: "Install DNS server {{ bind_package }}"
      community.general.pkgng:
        name: "{{ bind_package }}"

- name: "Enable service"
  notify: "bind_start"
  vars:
    _rc_file: /usr/local/etc/rc.conf.d/named
  block:
    - name: "Create {{ _rc_file | dirname }}"
      ansible.builtin.file:
        path: "{{ _rc_file | dirname }}"
        state: directory
        owner: root
        group: wheel
        mode: u=rwx,g=rx,o=rx

    - name: "Enable DNS server in {{ _rc_file }}"
      community.general.sysrc:
        path: "{{ _rc_file }}"
        name: named_enable
        value: true

- name: "Update configuration"
  notify: "bind_restart"
  block:
    - name: "Copy zone files"
      ansible.builtin.include_tasks: "copy_zone.yml"
      loop: "{{ bind_zones }}"
      loop_control:
        loop_var: _zone

    - name: "Configure service"
      ansible.builtin.template:
        src: usr/local/etc/namedb/named.conf.j2
        dest: /usr/local/etc/namedb/named.conf
        owner: bind
        group: bind
        mode: u=rw,g=r,o=r
        validate: named-checkconf %s
