# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

ext_if = "igc0"
int_if = "bridge0"

tcp_services = "{ domain, http, https, ntp, ssh }"
udp_services = "{ domain, ntp}"

icmp_types = "{ echoreq, unreach }"

# -- Options
# Don't filter on the loopback interface
set skip on lo0

# -- Translation
# Jails to ext_if
nat on $ext_if inet from $int_if:network to any -> ($ext_if)

# -- Packet Filter
# Scrub incoming packets
match in all scrub (no-df)

# Deny all traffic unless explicitly allowed
block log all

# Activate spoofing protection for all interfaces
block in quick from urpf-failed

# Allow traffic on int_if
pass quick on $int_if all

# Allow outbound traffic from int_if to ext_if
pass out on $ext_if from $int_if:network to any

# Allow connections created by the system, retain the state.
pass out proto tcp to any port $tcp_services
pass     proto udp to any port $udp_services

# Debugging traffic
pass inet proto icmp all icmp-type $icmp_types

# Secure shell
pass in inet proto tcp to $ext_if port ssh
pass in inet proto tcp to $int_if port ssh
