// Code generated by "stringer -type=Policy -linecomment"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PolicyFIFO-1]
	_ = x[PolicySJF-2]
	_ = x[PolicySTCF-3]
}

const _Policy_name = "fifosjfstcf"

var _Policy_index = [...]uint8{0, 4, 7, 11}

func (i Policy) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_Policy_index)-1 {
		return "Policy(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Policy_name[_Policy_index[idx]:_Policy_index[idx+1]]
}
