// Code generated by "stringer -type=BinOp -linecomment"; DO NOT EDIT.

package vm

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BinOpDivide-1]
	_ = x[BinOpMinus-2]
	_ = x[BinOpMultiply-3]
	_ = x[BinOpPlus-4]
}

const _BinOp_name = "dividieminusmultiplyplus"

var _BinOp_index = [...]uint8{0, 7, 12, 20, 24}

func (i BinOp) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_BinOp_index)-1 {
		return "BinOp(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BinOp_name[_BinOp_index[idx]:_BinOp_index[idx+1]]
}
