// Code generated by "stringer -type=Function -linecomment"; DO NOT EDIT.

package vm

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FuncSum-1]
}

const _Function_name = "SUM"

var _Function_index = [...]uint8{0, 3}

func (i Function) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_Function_index)-1 {
		return "Function(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Function_name[_Function_index[idx]:_Function_index[idx+1]]
}
