// Code generated by "stringer -type=InstType -linecomment"; DO NOT EDIT.

package vm

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[InstTypeBinOp-1]
	_ = x[InstTypeCall-2]
	_ = x[InstTypeNumber-3]
	_ = x[InstTypeRef-4]
}

const _InstType_name = "operatorfunctionnumberreference"

var _InstType_index = [...]uint8{0, 8, 16, 22, 31}

func (i InstType) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_InstType_index)-1 {
		return "InstType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _InstType_name[_InstType_index[idx]:_InstType_index[idx+1]]
}
