// Code generated by "stringer -type=Operator -linecomment"; DO NOT EDIT.

package vm

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OpMinus-1]
	_ = x[OpPlus-2]
}

const _Operator_name = "minusplus"

var _Operator_index = [...]uint8{0, 5, 9}

func (i Operator) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_Operator_index)-1 {
		return "Operator(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Operator_name[_Operator_index[idx]:_Operator_index[idx+1]]
}
