// Code generated by "stringer -type=RelOp -linecomment"; DO NOT EDIT.

package vm

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RelOpEqual-1]
	_ = x[RelOpGreater-2]
	_ = x[RelOpGreaterOrEqual-3]
	_ = x[RelOpLess-4]
	_ = x[RelOpLessOrEqual-5]
	_ = x[RelOpNotEqual-6]
}

const _RelOp_name = "equalgreatergreaterorequallesslessorequalnotequal"

var _RelOp_index = [...]uint8{0, 5, 12, 26, 30, 41, 49}

func (i RelOp) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_RelOp_index)-1 {
		return "RelOp(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RelOp_name[_RelOp_index[idx]:_RelOp_index[idx+1]]
}
