---
# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

- name: Packet filter
  hosts: nuc.lab.net
  become: true
  become_method: community.general.doas

  tasks:
    - name: Enable gateway
      community.general.sysrc:
        path: /etc/rc.conf.d/routing
        name: gateway_enable
        value: true
      notify: "restart routing"

    - name: Enable pf
      community.general.sysrc:
        path: /etc/rc.conf.d/pf
        name: pf_enable
        value: true
      register: pf_enable
      notify: "start pf"

    - name: Enable pflog
      community.general.sysrc:
        path: /etc/rc.conf.d/pflog
        name: pflog_enable
        value: true
      notify: "start pflog"

    - name: Setup pf.conf
      ansible.builtin.template:
        src: templates/etc/pf.conf
        dest: /etc/pf.conf
        owner: root
        group: wheel
        mode: u=rw,g=r,o=r
        validate: /sbin/pfctl -nf %s
      notify: "reload pf.conf"

  handlers:
    - name: Start pf
      ansible.builtin.service:
        name: pf
        state: started
      listen: "start pf"

    - name: Reload pf.conf
      ansible.builtin.service:
        name: pf
        state: reloaded
      listen: "reload pf.conf"

    - name: Start pflog
      ansible.builtin.service:
        name: pflog
        state: started
      listen: "start pflog"

    - name: Restart routing
      ansible.builtin.service:
        name: routing
        state: restarted
      listen: "restart routing"
