# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
- name: "Enable routing gateway"
  ansible.builtin.include_role:
    name: routing
  vars:
    routing_enable_gateway: true

- name: "Enable pflog"
  ansible.builtin.include_role:
    name: pflog
  vars:
    pflog_enable: true

- name: "Create configuration"
  vars:
    _conf_file: "/etc/pf.conf"
  block:
    - name: "Stat {{ _conf_file }}"
      ansible.builtin.stat:
        path: "{{ _conf_file }}"
        get_checksum: false
      register: pf_stat_pf_conf_task

    - name: "Create /etc/pf.conf"
      become: true
      ansible.builtin.file:
        path: "{{ _conf_file }}"
        state: touch
        owner: root
        group: wheel
        mode: u=rw,g=r,o=r
      when: not pf_stat_pf_conf_task.stat.exists
      notify: "start_pf"

- name: "Enable pf"
  become: true
  community.general.sysrc:
    path: /etc/rc.conf.d/pf
    name: pf_enable
    value: true
  notify: "start_pf"

# Make sure pf "started" to let /etc/rc.d/pf load pf.ko for pfctl to work in
# the steps below.
- name: "Flush pf changes"
  ansible.builtin.meta: flush_handlers

# reset_connection is broken in handlers:
# https://github.com/ansible/ansible/issues/50306
- name: Reset connection
  ansible.builtin.meta: reset_connection

- name: "Check status"
  block:
    - name: "PF status"
      become: true
      ansible.builtin.raw: /sbin/pfctl -s Running
      register: pf_status_task
      changed_when: false

    - name: "PF must be running"
      ansible.builtin.assert:
        that:
          - "pf_status_task.rc == 0"
          - "'Enabled' in pf_status_task.stdout"
        fail_msg: "Firewall is disabled"
        success_msg: "Firewall is enabled"

- name: "Configure pf"
  become: true
  ansible.builtin.copy:
    src: etc/pf.conf
    dest: /etc/pf.conf
    owner: root
    group: wheel
    mode: u=rw,g=r,o=r
    validate: /sbin/pfctl -nf %s
  notify: "reload_pf_conf"
