// file: /usr/local/etc/namedb/zones.conf.d/lab.net.conf
zone "lab.net" IN {
  type master;
  file "/usr/local/etc/namedb/primary/lab.net.db";
  allow-update { none; };
};
zone "0.0.10.in-addr.arpa" IN {
  type master;
  file "/usr/local/etc/namedb/primary/0.0.10.in-addr.arpa";
  allow-update { none; };
};
zone "1.0.10.in-addr.arpa" IN {
  type master;
  file "/usr/local/etc/namedb/primary/1.0.10.in-addr.arpa";
  allow-update { none; };
};
