// Copyright 2026 Samvel Khalatyan. All rights reserved.
//
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.2
// source: book/irex/pb/intent.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Intent describes a query intent. There might be many different intents, e.g.
// calculate intent, plot intent, measure intent. The Intent is a container for
// these. It holds one of the specific intents, which implement using Protobuf
// extensions.
//
// Next ID: 1
type Intent struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	extensionFields protoimpl.ExtensionFields
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Intent) Reset() {
	*x = Intent{}
	mi := &file_book_irex_pb_intent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Intent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Intent) ProtoMessage() {}

func (x *Intent) ProtoReflect() protoreflect.Message {
	mi := &file_book_irex_pb_intent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type Intent_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 Intent_builder) Build() *Intent {
	m0 := &Intent{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

var File_book_irex_pb_intent_proto protoreflect.FileDescriptor

const file_book_irex_pb_intent_proto_rawDesc = "" +
	"\n" +
	"\x19book/irex/pb/intent.proto\x12\tbook.irex\x1a!google/protobuf/go_features.proto\"\x16\n" +
	"\x06Intent*\f\b\xc0\xba\xab\xfa\x01\x10\x80\x80\x80\x80\x02B+Z!github.com/skhal/lab/book/irex/pb\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe9\a"

var file_book_irex_pb_intent_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_book_irex_pb_intent_proto_goTypes = []any{
	(*Intent)(nil), // 0: book.irex.Intent
}
var file_book_irex_pb_intent_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_book_irex_pb_intent_proto_init() }
func file_book_irex_pb_intent_proto_init() {
	if File_book_irex_pb_intent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_book_irex_pb_intent_proto_rawDesc), len(file_book_irex_pb_intent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_book_irex_pb_intent_proto_goTypes,
		DependencyIndexes: file_book_irex_pb_intent_proto_depIdxs,
		MessageInfos:      file_book_irex_pb_intent_proto_msgTypes,
	}.Build()
	File_book_irex_pb_intent_proto = out.File
	file_book_irex_pb_intent_proto_goTypes = nil
	file_book_irex_pb_intent_proto_depIdxs = nil
}
