// Copyright 2026 Samvel Khalatyan. All rights reserved.
//
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.2
// source: book/irex/pb/market.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Market contains market data such as indices, dividends, etc.
//
// Next ID: 2
type Market struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Quotes *[]*Quote              `protobuf:"bytes,1,rep,name=quotes"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Market) Reset() {
	*x = Market{}
	mi := &file_book_irex_pb_market_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Market) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Market) ProtoMessage() {}

func (x *Market) ProtoReflect() protoreflect.Message {
	mi := &file_book_irex_pb_market_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Market) GetQuotes() []*Quote {
	if x != nil {
		if x.xxx_hidden_Quotes != nil {
			return *x.xxx_hidden_Quotes
		}
	}
	return nil
}

func (x *Market) SetQuotes(v []*Quote) {
	x.xxx_hidden_Quotes = &v
}

type Market_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Quotes is a list of market quotes, sorted by dates in ascending order.
	// There is one quote per date.
	Quotes []*Quote
}

func (b0 Market_builder) Build() *Market {
	m0 := &Market{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Quotes = &b.Quotes
	return m0
}

// Quote represents a market state as of a given date.
//
// Next ID: 5
type Quote struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Date *Date                  `protobuf:"bytes,1,opt,name=date"`
	xxx_hidden_Spx  *Cent                  `protobuf:"bytes,2,opt,name=spx"`
	xxx_hidden_Div  *Cent                  `protobuf:"bytes,3,opt,name=div"`
	xxx_hidden_Cpi  *Cent                  `protobuf:"bytes,4,opt,name=cpi"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Quote) Reset() {
	*x = Quote{}
	mi := &file_book_irex_pb_market_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Quote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Quote) ProtoMessage() {}

func (x *Quote) ProtoReflect() protoreflect.Message {
	mi := &file_book_irex_pb_market_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Quote) GetDate() *Date {
	if x != nil {
		return x.xxx_hidden_Date
	}
	return nil
}

func (x *Quote) GetSpx() *Cent {
	if x != nil {
		return x.xxx_hidden_Spx
	}
	return nil
}

func (x *Quote) GetDiv() *Cent {
	if x != nil {
		return x.xxx_hidden_Div
	}
	return nil
}

func (x *Quote) GetCpi() *Cent {
	if x != nil {
		return x.xxx_hidden_Cpi
	}
	return nil
}

func (x *Quote) SetDate(v *Date) {
	x.xxx_hidden_Date = v
}

func (x *Quote) SetSpx(v *Cent) {
	x.xxx_hidden_Spx = v
}

func (x *Quote) SetDiv(v *Cent) {
	x.xxx_hidden_Div = v
}

func (x *Quote) SetCpi(v *Cent) {
	x.xxx_hidden_Cpi = v
}

func (x *Quote) HasDate() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Date != nil
}

func (x *Quote) HasSpx() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Spx != nil
}

func (x *Quote) HasDiv() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Div != nil
}

func (x *Quote) HasCpi() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Cpi != nil
}

func (x *Quote) ClearDate() {
	x.xxx_hidden_Date = nil
}

func (x *Quote) ClearSpx() {
	x.xxx_hidden_Spx = nil
}

func (x *Quote) ClearDiv() {
	x.xxx_hidden_Div = nil
}

func (x *Quote) ClearCpi() {
	x.xxx_hidden_Cpi = nil
}

type Quote_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// date is the day of the year when the quote applies.
	Date *Date
	// spx is Standard & Poor Composite Index.
	Spx *Cent
	// div is dividends.
	Div *Cent
	// cpi is Consumer Price Index
	Cpi *Cent
}

func (b0 Quote_builder) Build() *Quote {
	m0 := &Quote{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Date = b.Date
	x.xxx_hidden_Spx = b.Spx
	x.xxx_hidden_Div = b.Div
	x.xxx_hidden_Cpi = b.Cpi
	return m0
}

// Date represents a calendar date with year, month, and day.
//
// Next ID: 4
type Date struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Year        int32                  `protobuf:"varint,1,opt,name=year"`
	xxx_hidden_Month       int32                  `protobuf:"varint,2,opt,name=month"`
	xxx_hidden_Day         int32                  `protobuf:"varint,3,opt,name=day"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Date) Reset() {
	*x = Date{}
	mi := &file_book_irex_pb_market_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Date) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Date) ProtoMessage() {}

func (x *Date) ProtoReflect() protoreflect.Message {
	mi := &file_book_irex_pb_market_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Date) GetYear() int32 {
	if x != nil {
		return x.xxx_hidden_Year
	}
	return 0
}

func (x *Date) GetMonth() int32 {
	if x != nil {
		return x.xxx_hidden_Month
	}
	return 0
}

func (x *Date) GetDay() int32 {
	if x != nil {
		return x.xxx_hidden_Day
	}
	return 0
}

func (x *Date) SetYear(v int32) {
	x.xxx_hidden_Year = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *Date) SetMonth(v int32) {
	x.xxx_hidden_Month = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *Date) SetDay(v int32) {
	x.xxx_hidden_Day = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *Date) HasYear() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Date) HasMonth() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Date) HasDay() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *Date) ClearYear() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Year = 0
}

func (x *Date) ClearMonth() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Month = 0
}

func (x *Date) ClearDay() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Day = 0
}

type Date_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Year is the date's year.
	Year *int32
	// Month is the date's month of the year.
	Month *int32
	// Day is is the date's day of the month.
	Day *int32
}

func (b0 Date_builder) Build() *Date {
	m0 := &Date{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Year != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_Year = *b.Year
	}
	if b.Month != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_Month = *b.Month
	}
	if b.Day != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_Day = *b.Day
	}
	return m0
}

// Cent is the amount in cents.
//
// Next ID: 2
type Cent struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Value       int32                  `protobuf:"varint,1,opt,name=value"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Cent) Reset() {
	*x = Cent{}
	mi := &file_book_irex_pb_market_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cent) ProtoMessage() {}

func (x *Cent) ProtoReflect() protoreflect.Message {
	mi := &file_book_irex_pb_market_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Cent) GetValue() int32 {
	if x != nil {
		return x.xxx_hidden_Value
	}
	return 0
}

func (x *Cent) SetValue(v int32) {
	x.xxx_hidden_Value = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *Cent) HasValue() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Cent) ClearValue() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Value = 0
}

type Cent_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Value is the number in cents.
	Value *int32
}

func (b0 Cent_builder) Build() *Cent {
	m0 := &Cent{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Value != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Value = *b.Value
	}
	return m0
}

var File_book_irex_pb_market_proto protoreflect.FileDescriptor

const file_book_irex_pb_market_proto_rawDesc = "" +
	"\n" +
	"\x19book/irex/pb/market.proto\x12\tbook.irex\x1a!google/protobuf/go_features.proto\"2\n" +
	"\x06Market\x12(\n" +
	"\x06quotes\x18\x01 \x03(\v2\x10.book.irex.QuoteR\x06quotes\"\x95\x01\n" +
	"\x05Quote\x12#\n" +
	"\x04date\x18\x01 \x01(\v2\x0f.book.irex.DateR\x04date\x12!\n" +
	"\x03spx\x18\x02 \x01(\v2\x0f.book.irex.CentR\x03spx\x12!\n" +
	"\x03div\x18\x03 \x01(\v2\x0f.book.irex.CentR\x03div\x12!\n" +
	"\x03cpi\x18\x04 \x01(\v2\x0f.book.irex.CentR\x03cpi\"B\n" +
	"\x04Date\x12\x12\n" +
	"\x04year\x18\x01 \x01(\x05R\x04year\x12\x14\n" +
	"\x05month\x18\x02 \x01(\x05R\x05month\x12\x10\n" +
	"\x03day\x18\x03 \x01(\x05R\x03day\"\x1c\n" +
	"\x04Cent\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x05R\x05valueB+Z!github.com/skhal/lab/book/irex/pb\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe9\a"

var file_book_irex_pb_market_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_book_irex_pb_market_proto_goTypes = []any{
	(*Market)(nil), // 0: book.irex.Market
	(*Quote)(nil),  // 1: book.irex.Quote
	(*Date)(nil),   // 2: book.irex.Date
	(*Cent)(nil),   // 3: book.irex.Cent
}
var file_book_irex_pb_market_proto_depIdxs = []int32{
	1, // 0: book.irex.Market.quotes:type_name -> book.irex.Quote
	2, // 1: book.irex.Quote.date:type_name -> book.irex.Date
	3, // 2: book.irex.Quote.spx:type_name -> book.irex.Cent
	3, // 3: book.irex.Quote.div:type_name -> book.irex.Cent
	3, // 4: book.irex.Quote.cpi:type_name -> book.irex.Cent
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_book_irex_pb_market_proto_init() }
func file_book_irex_pb_market_proto_init() {
	if File_book_irex_pb_market_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_book_irex_pb_market_proto_rawDesc), len(file_book_irex_pb_market_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_book_irex_pb_market_proto_goTypes,
		DependencyIndexes: file_book_irex_pb_market_proto_depIdxs,
		MessageInfos:      file_book_irex_pb_market_proto_msgTypes,
	}.Build()
	File_book_irex_pb_market_proto = out.File
	file_book_irex_pb_market_proto_goTypes = nil
	file_book_irex_pb_market_proto_depIdxs = nil
}
