// Copyright 2026 Samvel Khalatyan. All rights reserved.
//
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.2
// source: book/irex/pb/market_service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// QuoteRequest is the request to [MarketService.Quote] endpoint. It defines
// the symbol to get the market quotes for.
//
// Next ID: 2
type QuoteRequest struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Symbol *Symbol                `protobuf:"bytes,1,opt,name=symbol"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *QuoteRequest) Reset() {
	*x = QuoteRequest{}
	mi := &file_book_irex_pb_market_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuoteRequest) ProtoMessage() {}

func (x *QuoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_book_irex_pb_market_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *QuoteRequest) GetSymbol() *Symbol {
	if x != nil {
		return x.xxx_hidden_Symbol
	}
	return nil
}

func (x *QuoteRequest) SetSymbol(v *Symbol) {
	x.xxx_hidden_Symbol = v
}

func (x *QuoteRequest) HasSymbol() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Symbol != nil
}

func (x *QuoteRequest) ClearSymbol() {
	x.xxx_hidden_Symbol = nil
}

type QuoteRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// symbol identifies the market symbol to get the quotes for.
	Symbol *Symbol
}

func (b0 QuoteRequest_builder) Build() *QuoteRequest {
	m0 := &QuoteRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Symbol = b.Symbol
	return m0
}

// QuoteResponse is the response from [MarketService.Quote] endpoint. It
// holds market data for the requested symbol.
//
// Next ID: 2
type QuoteResponse struct {
	state             protoimpl.MessageState  `protogen:"opaque.v1"`
	xxx_hidden_Quotes *[]*QuoteResponse_Quote `protobuf:"bytes,1,rep,name=quotes"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *QuoteResponse) Reset() {
	*x = QuoteResponse{}
	mi := &file_book_irex_pb_market_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuoteResponse) ProtoMessage() {}

func (x *QuoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_book_irex_pb_market_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *QuoteResponse) GetQuotes() []*QuoteResponse_Quote {
	if x != nil {
		if x.xxx_hidden_Quotes != nil {
			return *x.xxx_hidden_Quotes
		}
	}
	return nil
}

func (x *QuoteResponse) SetQuotes(v []*QuoteResponse_Quote) {
	x.xxx_hidden_Quotes = &v
}

type QuoteResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// quotes is a date-ordered list of market values of the requested symbol.
	Quotes []*QuoteResponse_Quote
}

func (b0 QuoteResponse_builder) Build() *QuoteResponse {
	m0 := &QuoteResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Quotes = &b.Quotes
	return m0
}

// Quote is a single data point, one per date.
//
// Next ID: 3
type QuoteResponse_Quote struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Date *Date                  `protobuf:"bytes,1,opt,name=date"`
	xxx_hidden_Cent *Cent                  `protobuf:"bytes,2,opt,name=cent"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *QuoteResponse_Quote) Reset() {
	*x = QuoteResponse_Quote{}
	mi := &file_book_irex_pb_market_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuoteResponse_Quote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuoteResponse_Quote) ProtoMessage() {}

func (x *QuoteResponse_Quote) ProtoReflect() protoreflect.Message {
	mi := &file_book_irex_pb_market_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *QuoteResponse_Quote) GetDate() *Date {
	if x != nil {
		return x.xxx_hidden_Date
	}
	return nil
}

func (x *QuoteResponse_Quote) GetCent() *Cent {
	if x != nil {
		return x.xxx_hidden_Cent
	}
	return nil
}

func (x *QuoteResponse_Quote) SetDate(v *Date) {
	x.xxx_hidden_Date = v
}

func (x *QuoteResponse_Quote) SetCent(v *Cent) {
	x.xxx_hidden_Cent = v
}

func (x *QuoteResponse_Quote) HasDate() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Date != nil
}

func (x *QuoteResponse_Quote) HasCent() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Cent != nil
}

func (x *QuoteResponse_Quote) ClearDate() {
	x.xxx_hidden_Date = nil
}

func (x *QuoteResponse_Quote) ClearCent() {
	x.xxx_hidden_Cent = nil
}

type QuoteResponse_Quote_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// date is the calendar date when the quote is applicable.
	Date *Date
	// cent is the market value of the requested symbol on a given date.
	Cent *Cent
}

func (b0 QuoteResponse_Quote_builder) Build() *QuoteResponse_Quote {
	m0 := &QuoteResponse_Quote{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Date = b.Date
	x.xxx_hidden_Cent = b.Cent
	return m0
}

var File_book_irex_pb_market_service_proto protoreflect.FileDescriptor

const file_book_irex_pb_market_service_proto_rawDesc = "" +
	"\n" +
	"!book/irex/pb/market_service.proto\x12\tbook.irex\x1a!google/protobuf/go_features.proto\x1a\x19book/irex/pb/market.proto\x1a\x19book/irex/pb/symbol.proto\"9\n" +
	"\fQuoteRequest\x12)\n" +
	"\x06symbol\x18\x01 \x01(\v2\x11.book.irex.SymbolR\x06symbol\"\x9a\x01\n" +
	"\rQuoteResponse\x126\n" +
	"\x06quotes\x18\x01 \x03(\v2\x1e.book.irex.QuoteResponse.QuoteR\x06quotes\x1aQ\n" +
	"\x05Quote\x12#\n" +
	"\x04date\x18\x01 \x01(\v2\x0f.book.irex.DateR\x04date\x12#\n" +
	"\x04cent\x18\x02 \x01(\v2\x0f.book.irex.CentR\x04cent2M\n" +
	"\rMarketService\x12<\n" +
	"\x05Quote\x12\x17.book.irex.QuoteRequest\x1a\x18.book.irex.QuoteResponse\"\x00B+Z!github.com/skhal/lab/book/irex/pb\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe9\a"

var file_book_irex_pb_market_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_book_irex_pb_market_service_proto_goTypes = []any{
	(*QuoteRequest)(nil),        // 0: book.irex.QuoteRequest
	(*QuoteResponse)(nil),       // 1: book.irex.QuoteResponse
	(*QuoteResponse_Quote)(nil), // 2: book.irex.QuoteResponse.Quote
	(*Symbol)(nil),              // 3: book.irex.Symbol
	(*Date)(nil),                // 4: book.irex.Date
	(*Cent)(nil),                // 5: book.irex.Cent
}
var file_book_irex_pb_market_service_proto_depIdxs = []int32{
	3, // 0: book.irex.QuoteRequest.symbol:type_name -> book.irex.Symbol
	2, // 1: book.irex.QuoteResponse.quotes:type_name -> book.irex.QuoteResponse.Quote
	4, // 2: book.irex.QuoteResponse.Quote.date:type_name -> book.irex.Date
	5, // 3: book.irex.QuoteResponse.Quote.cent:type_name -> book.irex.Cent
	0, // 4: book.irex.MarketService.Quote:input_type -> book.irex.QuoteRequest
	1, // 5: book.irex.MarketService.Quote:output_type -> book.irex.QuoteResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_book_irex_pb_market_service_proto_init() }
func file_book_irex_pb_market_service_proto_init() {
	if File_book_irex_pb_market_service_proto != nil {
		return
	}
	file_book_irex_pb_market_proto_init()
	file_book_irex_pb_symbol_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_book_irex_pb_market_service_proto_rawDesc), len(file_book_irex_pb_market_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_book_irex_pb_market_service_proto_goTypes,
		DependencyIndexes: file_book_irex_pb_market_service_proto_depIdxs,
		MessageInfos:      file_book_irex_pb_market_service_proto_msgTypes,
	}.Build()
	File_book_irex_pb_market_service_proto = out.File
	file_book_irex_pb_market_service_proto_goTypes = nil
	file_book_irex_pb_market_service_proto_depIdxs = nil
}
