// Copyright 2026 Samvel Khalatyan. All rights reserved.
//
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.2
// source: book/irex/pb/page.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Page represents a finance results page with a list of served features.
//
// Next ID: 2
type Page struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Features *[]*Feature            `protobuf:"bytes,1,rep,name=features"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Page) Reset() {
	*x = Page{}
	mi := &file_book_irex_pb_page_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Page) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Page) ProtoMessage() {}

func (x *Page) ProtoReflect() protoreflect.Message {
	mi := &file_book_irex_pb_page_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Page) GetFeatures() []*Feature {
	if x != nil {
		if x.xxx_hidden_Features != nil {
			return *x.xxx_hidden_Features
		}
	}
	return nil
}

func (x *Page) SetFeatures(v []*Feature) {
	x.xxx_hidden_Features = &v
}

type Page_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// features is a list of fulfilled features, to be included on the final page.
	Features []*Feature
}

func (b0 Page_builder) Build() *Page {
	m0 := &Page{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Features = &b.Features
	return m0
}

var File_book_irex_pb_page_proto protoreflect.FileDescriptor

const file_book_irex_pb_page_proto_rawDesc = "" +
	"\n" +
	"\x17book/irex/pb/page.proto\x12\tbook.irex\x1a!google/protobuf/go_features.proto\x1a\x1abook/irex/pb/feature.proto\"6\n" +
	"\x04Page\x12.\n" +
	"\bfeatures\x18\x01 \x03(\v2\x12.book.irex.FeatureR\bfeaturesB+Z!github.com/skhal/lab/book/irex/pb\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe9\a"

var file_book_irex_pb_page_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_book_irex_pb_page_proto_goTypes = []any{
	(*Page)(nil),    // 0: book.irex.Page
	(*Feature)(nil), // 1: book.irex.Feature
}
var file_book_irex_pb_page_proto_depIdxs = []int32{
	1, // 0: book.irex.Page.features:type_name -> book.irex.Feature
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_book_irex_pb_page_proto_init() }
func file_book_irex_pb_page_proto_init() {
	if File_book_irex_pb_page_proto != nil {
		return
	}
	file_book_irex_pb_feature_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_book_irex_pb_page_proto_rawDesc), len(file_book_irex_pb_page_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_book_irex_pb_page_proto_goTypes,
		DependencyIndexes: file_book_irex_pb_page_proto_depIdxs,
		MessageInfos:      file_book_irex_pb_page_proto_msgTypes,
	}.Build()
	File_book_irex_pb_page_proto = out.File
	file_book_irex_pb_page_proto_goTypes = nil
	file_book_irex_pb_page_proto_depIdxs = nil
}
