// Copyright 2026 Samvel Khalatyan. All rights reserved.
//
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.2
// source: book/irex/pb/ping_intent.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PingIntent describes a user intent to ping the server.
//
// Next ID: 2
type PingIntent struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Message     *string                `protobuf:"bytes,1,opt,name=message"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *PingIntent) Reset() {
	*x = PingIntent{}
	mi := &file_book_irex_pb_ping_intent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingIntent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingIntent) ProtoMessage() {}

func (x *PingIntent) ProtoReflect() protoreflect.Message {
	mi := &file_book_irex_pb_ping_intent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PingIntent) GetMessage() string {
	if x != nil {
		if x.xxx_hidden_Message != nil {
			return *x.xxx_hidden_Message
		}
		return ""
	}
	return ""
}

func (x *PingIntent) SetMessage(v string) {
	x.xxx_hidden_Message = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *PingIntent) HasMessage() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *PingIntent) ClearMessage() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Message = nil
}

type PingIntent_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// message is the ping command pamaeters, e.g. "hello world" from
	// "&q=ping+hello+world".
	Message *string
}

func (b0 PingIntent_builder) Build() *PingIntent {
	m0 := &PingIntent{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Message != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Message = b.Message
	}
	return m0
}

var file_book_irex_pb_ping_intent_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*Intent)(nil),
		ExtensionType: (*PingIntent)(nil),
		Field:         525000002,
		Name:          "book.irex.PingIntent.ping_intent",
		Tag:           "bytes,525000002,opt,name=ping_intent",
		Filename:      "book/irex/pb/ping_intent.proto",
	},
}

// Extension fields to Intent.
var (
	// optional book.irex.PingIntent ping_intent = 525000002;
	E_PingIntent_PingIntent = &file_book_irex_pb_ping_intent_proto_extTypes[0]
)

var File_book_irex_pb_ping_intent_proto protoreflect.FileDescriptor

const file_book_irex_pb_ping_intent_proto_rawDesc = "" +
	"\n" +
	"\x1ebook/irex/pb/ping_intent.proto\x12\tbook.irex\x1a!google/protobuf/go_features.proto\x1a\x19book/irex/pb/intent.proto\"u\n" +
	"\n" +
	"PingIntent\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2M\n" +
	"\vping_intent\x12\x11.book.irex.Intent\x18º\xab\xfa\x01 \x01(\v2\x15.book.irex.PingIntentR\n" +
	"pingIntentB+Z!github.com/skhal/lab/book/irex/pb\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe9\a"

var file_book_irex_pb_ping_intent_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_book_irex_pb_ping_intent_proto_goTypes = []any{
	(*PingIntent)(nil), // 0: book.irex.PingIntent
	(*Intent)(nil),     // 1: book.irex.Intent
}
var file_book_irex_pb_ping_intent_proto_depIdxs = []int32{
	1, // 0: book.irex.PingIntent.ping_intent:extendee -> book.irex.Intent
	0, // 1: book.irex.PingIntent.ping_intent:type_name -> book.irex.PingIntent
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	1, // [1:2] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_book_irex_pb_ping_intent_proto_init() }
func file_book_irex_pb_ping_intent_proto_init() {
	if File_book_irex_pb_ping_intent_proto != nil {
		return
	}
	file_book_irex_pb_intent_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_book_irex_pb_ping_intent_proto_rawDesc), len(file_book_irex_pb_ping_intent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_book_irex_pb_ping_intent_proto_goTypes,
		DependencyIndexes: file_book_irex_pb_ping_intent_proto_depIdxs,
		MessageInfos:      file_book_irex_pb_ping_intent_proto_msgTypes,
		ExtensionInfos:    file_book_irex_pb_ping_intent_proto_extTypes,
	}.Build()
	File_book_irex_pb_ping_intent_proto = out.File
	file_book_irex_pb_ping_intent_proto_goTypes = nil
	file_book_irex_pb_ping_intent_proto_depIdxs = nil
}
