// Copyright 2026 Samvel Khalatyan. All rights reserved.
//
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.2
// source: book/irex/pb/ping_feature.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PingFeature pings the server.
//
// Next ID: 3
type PingFeature struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Ping        *string                `protobuf:"bytes,1,opt,name=ping"`
	xxx_hidden_Pong        *string                `protobuf:"bytes,2,opt,name=pong"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *PingFeature) Reset() {
	*x = PingFeature{}
	mi := &file_book_irex_pb_ping_feature_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingFeature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingFeature) ProtoMessage() {}

func (x *PingFeature) ProtoReflect() protoreflect.Message {
	mi := &file_book_irex_pb_ping_feature_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PingFeature) GetPing() string {
	if x != nil {
		if x.xxx_hidden_Ping != nil {
			return *x.xxx_hidden_Ping
		}
		return ""
	}
	return ""
}

func (x *PingFeature) GetPong() string {
	if x != nil {
		if x.xxx_hidden_Pong != nil {
			return *x.xxx_hidden_Pong
		}
		return ""
	}
	return ""
}

func (x *PingFeature) SetPing(v string) {
	x.xxx_hidden_Ping = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *PingFeature) SetPong(v string) {
	x.xxx_hidden_Pong = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *PingFeature) HasPing() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *PingFeature) HasPong() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *PingFeature) ClearPing() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Ping = nil
}

func (x *PingFeature) ClearPong() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Pong = nil
}

type PingFeature_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// pins is the incoming message.
	Ping *string
	// pong is the outgoind message.
	Pong *string
}

func (b0 PingFeature_builder) Build() *PingFeature {
	m0 := &PingFeature{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Ping != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Ping = b.Ping
	}
	if b.Pong != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Pong = b.Pong
	}
	return m0
}

var file_book_irex_pb_ping_feature_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*Feature)(nil),
		ExtensionType: (*PingFeature)(nil),
		Field:         525010002,
		Name:          "book.irex.PingFeature.ping_feature",
		Tag:           "bytes,525010002,opt,name=ping_feature",
		Filename:      "book/irex/pb/ping_feature.proto",
	},
}

// Extension fields to Feature.
var (
	// optional book.irex.PingFeature ping_feature = 525010002;
	E_PingFeature_PingFeature = &file_book_irex_pb_ping_feature_proto_extTypes[0]
)

var File_book_irex_pb_ping_feature_proto protoreflect.FileDescriptor

const file_book_irex_pb_ping_feature_proto_rawDesc = "" +
	"\n" +
	"\x1fbook/irex/pb/ping_feature.proto\x12\tbook.irex\x1a!google/protobuf/go_features.proto\x1a\x1abook/irex/pb/feature.proto\"\x88\x01\n" +
	"\vPingFeature\x12\x12\n" +
	"\x04ping\x18\x01 \x01(\tR\x04ping\x12\x12\n" +
	"\x04pong\x18\x02 \x01(\tR\x04pong2Q\n" +
	"\fping_feature\x12\x12.book.irex.Feature\x18҈\xac\xfa\x01 \x01(\v2\x16.book.irex.PingFeatureR\vpingFeatureB+Z!github.com/skhal/lab/book/irex/pb\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe9\a"

var file_book_irex_pb_ping_feature_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_book_irex_pb_ping_feature_proto_goTypes = []any{
	(*PingFeature)(nil), // 0: book.irex.PingFeature
	(*Feature)(nil),     // 1: book.irex.Feature
}
var file_book_irex_pb_ping_feature_proto_depIdxs = []int32{
	1, // 0: book.irex.PingFeature.ping_feature:extendee -> book.irex.Feature
	0, // 1: book.irex.PingFeature.ping_feature:type_name -> book.irex.PingFeature
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	1, // [1:2] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_book_irex_pb_ping_feature_proto_init() }
func file_book_irex_pb_ping_feature_proto_init() {
	if File_book_irex_pb_ping_feature_proto != nil {
		return
	}
	file_book_irex_pb_feature_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_book_irex_pb_ping_feature_proto_rawDesc), len(file_book_irex_pb_ping_feature_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_book_irex_pb_ping_feature_proto_goTypes,
		DependencyIndexes: file_book_irex_pb_ping_feature_proto_depIdxs,
		MessageInfos:      file_book_irex_pb_ping_feature_proto_msgTypes,
		ExtensionInfos:    file_book_irex_pb_ping_feature_proto_extTypes,
	}.Build()
	File_book_irex_pb_ping_feature_proto = out.File
	file_book_irex_pb_ping_feature_proto_goTypes = nil
	file_book_irex_pb_ping_feature_proto_depIdxs = nil
}
