// Copyright 2026 Samvel Khalatyan. All rights reserved.
//
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.2
// source: book/irex/pb/plot_intent.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PlotIntent describes a user intent to plot a symbol.
//
// Next ID: 2
type PlotIntent struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Symbol *Symbol                `protobuf:"bytes,1,opt,name=symbol"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PlotIntent) Reset() {
	*x = PlotIntent{}
	mi := &file_book_irex_pb_plot_intent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlotIntent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlotIntent) ProtoMessage() {}

func (x *PlotIntent) ProtoReflect() protoreflect.Message {
	mi := &file_book_irex_pb_plot_intent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PlotIntent) GetSymbol() *Symbol {
	if x != nil {
		return x.xxx_hidden_Symbol
	}
	return nil
}

func (x *PlotIntent) SetSymbol(v *Symbol) {
	x.xxx_hidden_Symbol = v
}

func (x *PlotIntent) HasSymbol() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Symbol != nil
}

func (x *PlotIntent) ClearSymbol() {
	x.xxx_hidden_Symbol = nil
}

type PlotIntent_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// symbol is the financial symbol to plot.
	Symbol *Symbol
}

func (b0 PlotIntent_builder) Build() *PlotIntent {
	m0 := &PlotIntent{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Symbol = b.Symbol
	return m0
}

var file_book_irex_pb_plot_intent_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*Intent)(nil),
		ExtensionType: (*PlotIntent)(nil),
		Field:         525000001,
		Name:          "book.irex.PlotIntent.plot_intent",
		Tag:           "bytes,525000001,opt,name=plot_intent",
		Filename:      "book/irex/pb/plot_intent.proto",
	},
}

// Extension fields to Intent.
var (
	// optional book.irex.PlotIntent plot_intent = 525000001;
	E_PlotIntent_PlotIntent = &file_book_irex_pb_plot_intent_proto_extTypes[0]
)

var File_book_irex_pb_plot_intent_proto protoreflect.FileDescriptor

const file_book_irex_pb_plot_intent_proto_rawDesc = "" +
	"\n" +
	"\x1ebook/irex/pb/plot_intent.proto\x12\tbook.irex\x1a!google/protobuf/go_features.proto\x1a\x19book/irex/pb/intent.proto\x1a\x19book/irex/pb/symbol.proto\"\x86\x01\n" +
	"\n" +
	"PlotIntent\x12)\n" +
	"\x06symbol\x18\x01 \x01(\v2\x11.book.irex.SymbolR\x06symbol2M\n" +
	"\vplot_intent\x12\x11.book.irex.Intent\x18\xc1\xba\xab\xfa\x01 \x01(\v2\x15.book.irex.PlotIntentR\n" +
	"plotIntentB+Z!github.com/skhal/lab/book/irex/pb\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe9\a"

var file_book_irex_pb_plot_intent_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_book_irex_pb_plot_intent_proto_goTypes = []any{
	(*PlotIntent)(nil), // 0: book.irex.PlotIntent
	(*Symbol)(nil),     // 1: book.irex.Symbol
	(*Intent)(nil),     // 2: book.irex.Intent
}
var file_book_irex_pb_plot_intent_proto_depIdxs = []int32{
	1, // 0: book.irex.PlotIntent.symbol:type_name -> book.irex.Symbol
	2, // 1: book.irex.PlotIntent.plot_intent:extendee -> book.irex.Intent
	0, // 2: book.irex.PlotIntent.plot_intent:type_name -> book.irex.PlotIntent
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	2, // [2:3] is the sub-list for extension type_name
	1, // [1:2] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_book_irex_pb_plot_intent_proto_init() }
func file_book_irex_pb_plot_intent_proto_init() {
	if File_book_irex_pb_plot_intent_proto != nil {
		return
	}
	file_book_irex_pb_intent_proto_init()
	file_book_irex_pb_symbol_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_book_irex_pb_plot_intent_proto_rawDesc), len(file_book_irex_pb_plot_intent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_book_irex_pb_plot_intent_proto_goTypes,
		DependencyIndexes: file_book_irex_pb_plot_intent_proto_depIdxs,
		MessageInfos:      file_book_irex_pb_plot_intent_proto_msgTypes,
		ExtensionInfos:    file_book_irex_pb_plot_intent_proto_extTypes,
	}.Build()
	File_book_irex_pb_plot_intent_proto = out.File
	file_book_irex_pb_plot_intent_proto_goTypes = nil
	file_book_irex_pb_plot_intent_proto_depIdxs = nil
}
