// Copyright 2026 Samvel Khalatyan. All rights reserved.
//
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.2
// source: book/irex/pb/plot_feature.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PlotFeature is a FRP entity to plot a financial symbol.
// Next ID: 3
type PlotFeature struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Symbol *Symbol                `protobuf:"bytes,1,opt,name=symbol"`
	xxx_hidden_Quotes *[]*PlotFeature_Quote  `protobuf:"bytes,2,rep,name=quotes"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PlotFeature) Reset() {
	*x = PlotFeature{}
	mi := &file_book_irex_pb_plot_feature_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlotFeature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlotFeature) ProtoMessage() {}

func (x *PlotFeature) ProtoReflect() protoreflect.Message {
	mi := &file_book_irex_pb_plot_feature_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PlotFeature) GetSymbol() *Symbol {
	if x != nil {
		return x.xxx_hidden_Symbol
	}
	return nil
}

func (x *PlotFeature) GetQuotes() []*PlotFeature_Quote {
	if x != nil {
		if x.xxx_hidden_Quotes != nil {
			return *x.xxx_hidden_Quotes
		}
	}
	return nil
}

func (x *PlotFeature) SetSymbol(v *Symbol) {
	x.xxx_hidden_Symbol = v
}

func (x *PlotFeature) SetQuotes(v []*PlotFeature_Quote) {
	x.xxx_hidden_Quotes = &v
}

func (x *PlotFeature) HasSymbol() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Symbol != nil
}

func (x *PlotFeature) ClearSymbol() {
	x.xxx_hidden_Symbol = nil
}

type PlotFeature_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// symbol describes a financial entity represented by the plot.
	Symbol *Symbol
	// quotes is a list of dated values of the symbol.
	Quotes []*PlotFeature_Quote
}

func (b0 PlotFeature_builder) Build() *PlotFeature {
	m0 := &PlotFeature{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Symbol = b.Symbol
	x.xxx_hidden_Quotes = &b.Quotes
	return m0
}

// Quote is a value of the symbol on a specific date.
// Next ID: 3
type PlotFeature_Quote struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Date *Date                  `protobuf:"bytes,1,opt,name=date"`
	xxx_hidden_Cent *Cent                  `protobuf:"bytes,2,opt,name=cent"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PlotFeature_Quote) Reset() {
	*x = PlotFeature_Quote{}
	mi := &file_book_irex_pb_plot_feature_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlotFeature_Quote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlotFeature_Quote) ProtoMessage() {}

func (x *PlotFeature_Quote) ProtoReflect() protoreflect.Message {
	mi := &file_book_irex_pb_plot_feature_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PlotFeature_Quote) GetDate() *Date {
	if x != nil {
		return x.xxx_hidden_Date
	}
	return nil
}

func (x *PlotFeature_Quote) GetCent() *Cent {
	if x != nil {
		return x.xxx_hidden_Cent
	}
	return nil
}

func (x *PlotFeature_Quote) SetDate(v *Date) {
	x.xxx_hidden_Date = v
}

func (x *PlotFeature_Quote) SetCent(v *Cent) {
	x.xxx_hidden_Cent = v
}

func (x *PlotFeature_Quote) HasDate() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Date != nil
}

func (x *PlotFeature_Quote) HasCent() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Cent != nil
}

func (x *PlotFeature_Quote) ClearDate() {
	x.xxx_hidden_Date = nil
}

func (x *PlotFeature_Quote) ClearCent() {
	x.xxx_hidden_Cent = nil
}

type PlotFeature_Quote_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// date is the calendar day of the quoted value.
	Date *Date
	// cent is the quote value in cents.
	Cent *Cent
}

func (b0 PlotFeature_Quote_builder) Build() *PlotFeature_Quote {
	m0 := &PlotFeature_Quote{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Date = b.Date
	x.xxx_hidden_Cent = b.Cent
	return m0
}

var file_book_irex_pb_plot_feature_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*Feature)(nil),
		ExtensionType: (*PlotFeature)(nil),
		Field:         525010001,
		Name:          "book.irex.PlotFeature.plot_feature",
		Tag:           "bytes,525010001,opt,name=plot_feature",
		Filename:      "book/irex/pb/plot_feature.proto",
	},
}

// Extension fields to Feature.
var (
	// optional book.irex.PlotFeature plot_feature = 525010001;
	E_PlotFeature_PlotFeature = &file_book_irex_pb_plot_feature_proto_extTypes[0]
)

var File_book_irex_pb_plot_feature_proto protoreflect.FileDescriptor

const file_book_irex_pb_plot_feature_proto_rawDesc = "" +
	"\n" +
	"\x1fbook/irex/pb/plot_feature.proto\x12\tbook.irex\x1a!google/protobuf/go_features.proto\x1a\x1abook/irex/pb/feature.proto\x1a\x19book/irex/pb/market.proto\x1a\x19book/irex/pb/symbol.proto\"\x94\x02\n" +
	"\vPlotFeature\x12)\n" +
	"\x06symbol\x18\x01 \x01(\v2\x11.book.irex.SymbolR\x06symbol\x124\n" +
	"\x06quotes\x18\x02 \x03(\v2\x1c.book.irex.PlotFeature.QuoteR\x06quotes\x1aQ\n" +
	"\x05Quote\x12#\n" +
	"\x04date\x18\x01 \x01(\v2\x0f.book.irex.DateR\x04date\x12#\n" +
	"\x04cent\x18\x02 \x01(\v2\x0f.book.irex.CentR\x04cent2Q\n" +
	"\fplot_feature\x12\x12.book.irex.Feature\x18ш\xac\xfa\x01 \x01(\v2\x16.book.irex.PlotFeatureR\vplotFeatureB+Z!github.com/skhal/lab/book/irex/pb\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe9\a"

var file_book_irex_pb_plot_feature_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_book_irex_pb_plot_feature_proto_goTypes = []any{
	(*PlotFeature)(nil),       // 0: book.irex.PlotFeature
	(*PlotFeature_Quote)(nil), // 1: book.irex.PlotFeature.Quote
	(*Symbol)(nil),            // 2: book.irex.Symbol
	(*Date)(nil),              // 3: book.irex.Date
	(*Cent)(nil),              // 4: book.irex.Cent
	(*Feature)(nil),           // 5: book.irex.Feature
}
var file_book_irex_pb_plot_feature_proto_depIdxs = []int32{
	2, // 0: book.irex.PlotFeature.symbol:type_name -> book.irex.Symbol
	1, // 1: book.irex.PlotFeature.quotes:type_name -> book.irex.PlotFeature.Quote
	3, // 2: book.irex.PlotFeature.Quote.date:type_name -> book.irex.Date
	4, // 3: book.irex.PlotFeature.Quote.cent:type_name -> book.irex.Cent
	5, // 4: book.irex.PlotFeature.plot_feature:extendee -> book.irex.Feature
	0, // 5: book.irex.PlotFeature.plot_feature:type_name -> book.irex.PlotFeature
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	5, // [5:6] is the sub-list for extension type_name
	4, // [4:5] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_book_irex_pb_plot_feature_proto_init() }
func file_book_irex_pb_plot_feature_proto_init() {
	if File_book_irex_pb_plot_feature_proto != nil {
		return
	}
	file_book_irex_pb_feature_proto_init()
	file_book_irex_pb_market_proto_init()
	file_book_irex_pb_symbol_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_book_irex_pb_plot_feature_proto_rawDesc), len(file_book_irex_pb_plot_feature_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_book_irex_pb_plot_feature_proto_goTypes,
		DependencyIndexes: file_book_irex_pb_plot_feature_proto_depIdxs,
		MessageInfos:      file_book_irex_pb_plot_feature_proto_msgTypes,
		ExtensionInfos:    file_book_irex_pb_plot_feature_proto_extTypes,
	}.Build()
	File_book_irex_pb_plot_feature_proto = out.File
	file_book_irex_pb_plot_feature_proto_goTypes = nil
	file_book_irex_pb_plot_feature_proto_depIdxs = nil
}
