// Copyright 2026 Samvel Khalatyan. All rights reserved.
//
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.2
// source: book/irex/pb/symbol.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Index is a market index, e.g. SPX for S&P500 composite index.
//
// Next ID: 2
type Symbol_Index int32

const (
	// IDX_UNSPECIFIED means the index is not set
	Symbol_IDX_UNSPECIFIED Symbol_Index = 0
	// IDX_SPX is S&P500 composite index
	Symbol_IDX_SPX Symbol_Index = 1
)

// Enum value maps for Symbol_Index.
var (
	Symbol_Index_name = map[int32]string{
		0: "IDX_UNSPECIFIED",
		1: "IDX_SPX",
	}
	Symbol_Index_value = map[string]int32{
		"IDX_UNSPECIFIED": 0,
		"IDX_SPX":         1,
	}
)

func (x Symbol_Index) Enum() *Symbol_Index {
	p := new(Symbol_Index)
	*p = x
	return p
}

func (x Symbol_Index) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Symbol_Index) Descriptor() protoreflect.EnumDescriptor {
	return file_book_irex_pb_symbol_proto_enumTypes[0].Descriptor()
}

func (Symbol_Index) Type() protoreflect.EnumType {
	return &file_book_irex_pb_symbol_proto_enumTypes[0]
}

func (x Symbol_Index) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Symbol represents one of the market symbols, e.g. index.
//
// Next ID: 2
type Symbol struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_SymbolOneof isSymbol_SymbolOneof   `protobuf_oneof:"symbol_oneof"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Symbol) Reset() {
	*x = Symbol{}
	mi := &file_book_irex_pb_symbol_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Symbol) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Symbol) ProtoMessage() {}

func (x *Symbol) ProtoReflect() protoreflect.Message {
	mi := &file_book_irex_pb_symbol_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Symbol) GetIndex() Symbol_Index {
	if x != nil {
		if x, ok := x.xxx_hidden_SymbolOneof.(*symbol_Index_); ok {
			return x.Index
		}
	}
	return Symbol_IDX_UNSPECIFIED
}

func (x *Symbol) SetIndex(v Symbol_Index) {
	x.xxx_hidden_SymbolOneof = &symbol_Index_{v}
}

func (x *Symbol) HasSymbolOneof() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_SymbolOneof != nil
}

func (x *Symbol) HasIndex() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_SymbolOneof.(*symbol_Index_)
	return ok
}

func (x *Symbol) ClearSymbolOneof() {
	x.xxx_hidden_SymbolOneof = nil
}

func (x *Symbol) ClearIndex() {
	if _, ok := x.xxx_hidden_SymbolOneof.(*symbol_Index_); ok {
		x.xxx_hidden_SymbolOneof = nil
	}
}

const Symbol_SymbolOneof_not_set_case case_Symbol_SymbolOneof = 0
const Symbol_Index_case case_Symbol_SymbolOneof = 1

func (x *Symbol) WhichSymbolOneof() case_Symbol_SymbolOneof {
	if x == nil {
		return Symbol_SymbolOneof_not_set_case
	}
	switch x.xxx_hidden_SymbolOneof.(type) {
	case *symbol_Index_:
		return Symbol_Index_case
	default:
		return Symbol_SymbolOneof_not_set_case
	}
}

type Symbol_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_SymbolOneof:
	Index *Symbol_Index
	// -- end of xxx_hidden_SymbolOneof
}

func (b0 Symbol_builder) Build() *Symbol {
	m0 := &Symbol{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Index != nil {
		x.xxx_hidden_SymbolOneof = &symbol_Index_{*b.Index}
	}
	return m0
}

type case_Symbol_SymbolOneof protoreflect.FieldNumber

func (x case_Symbol_SymbolOneof) String() string {
	md := file_book_irex_pb_symbol_proto_msgTypes[0].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isSymbol_SymbolOneof interface {
	isSymbol_SymbolOneof()
}

type symbol_Index_ struct {
	Index Symbol_Index `protobuf:"varint,1,opt,name=index,enum=book.irex.Symbol_Index,oneof"`
}

func (*symbol_Index_) isSymbol_SymbolOneof() {}

var File_book_irex_pb_symbol_proto protoreflect.FileDescriptor

const file_book_irex_pb_symbol_proto_rawDesc = "" +
	"\n" +
	"\x19book/irex/pb/symbol.proto\x12\tbook.irex\x1a!google/protobuf/go_features.proto\"t\n" +
	"\x06Symbol\x12/\n" +
	"\x05index\x18\x01 \x01(\x0e2\x17.book.irex.Symbol.IndexH\x00R\x05index\")\n" +
	"\x05Index\x12\x13\n" +
	"\x0fIDX_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aIDX_SPX\x10\x01B\x0e\n" +
	"\fsymbol_oneofB+Z!github.com/skhal/lab/book/irex/pb\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe9\a"

var file_book_irex_pb_symbol_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_book_irex_pb_symbol_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_book_irex_pb_symbol_proto_goTypes = []any{
	(Symbol_Index)(0), // 0: book.irex.Symbol.Index
	(*Symbol)(nil),    // 1: book.irex.Symbol
}
var file_book_irex_pb_symbol_proto_depIdxs = []int32{
	0, // 0: book.irex.Symbol.index:type_name -> book.irex.Symbol.Index
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_book_irex_pb_symbol_proto_init() }
func file_book_irex_pb_symbol_proto_init() {
	if File_book_irex_pb_symbol_proto != nil {
		return
	}
	file_book_irex_pb_symbol_proto_msgTypes[0].OneofWrappers = []any{
		(*symbol_Index_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_book_irex_pb_symbol_proto_rawDesc), len(file_book_irex_pb_symbol_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_book_irex_pb_symbol_proto_goTypes,
		DependencyIndexes: file_book_irex_pb_symbol_proto_depIdxs,
		EnumInfos:         file_book_irex_pb_symbol_proto_enumTypes,
		MessageInfos:      file_book_irex_pb_symbol_proto_msgTypes,
	}.Build()
	File_book_irex_pb_symbol_proto = out.File
	file_book_irex_pb_symbol_proto_goTypes = nil
	file_book_irex_pb_symbol_proto_depIdxs = nil
}
