# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
- name: "Migrate ifconfig_{{ netif_ethernet_if }}"
  ansible.builtin.include_role:
    name: sysrc
  vars:
    sysrc_migrate:
      name: "ifconfig_{{ netif_ethernet_if }}"
      value: up
      path: /etc/rc.conf.d/network
      notify: "restart_network"

- name: Configure interfaces
  ansible.builtin.include_tasks: "ifconfig.yml"
  loop: "{{ netif_clones }}"
  loop_control:
    loop_var: _iface
