# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
- name: Configure interfaces
  become: true
  notify: "restart_network"
  vars:
    _rc_file: /etc/rc.conf.d/network
  community.general.sysrc:
    path: "{{ _rc_file }}"
    name: "ifconfig_{{ _iface.name }}"
    value: >-
      inet {{ _iface.cidr }} up
      {% if 'desc' in _iface %}descr {{ _iface.desc }}{% endif %}
  loop: "{{ netif_ifaces }}"
  loop_control:
    label: "{{ _iface.name }}"
    loop_var: _iface

- name: Configure bridges
  ansible.builtin.include_tasks: "_ifconfig_bridge.yml"
  loop: "{{ netif_bridges }}"
  loop_control:
    label: "{{ _bridge.name }}"
    loop_var: _bridge
