# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
- name: Install packages
  become: true
  community.general.pkgng:
    name: pam_ldap

- name: Configure Pluggable Authentication Modules (PAM)
  vars:
    # This file has the same name as OpenLDAP client configuration but different
    # location, i.e. /usr/local/etc/openldap/ldap.conf.
    _ldap_conf_file: /usr/local/etc/ldap.conf
    _sshd_file: /etc/pam.d/sshd
  block:
    - name: Patch ldap.conf
      become: true
      ansible.posix.patch:
        src: usr/local/etc/ldap.conf.diff
        dest: "{{ _ldap_conf_file }}"
        backup: true
        ignore_whitespace: true

    - name: Patch sshd PAM configuration
      become: true
      ansible.posix.patch:
        src: etc/pam.d/sshd.diff
        dest: "{{ _sshd_file }}"
        backup: true
        ignore_whitespace: true
