# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
- name: "Enable routing gateway"
  ansible.builtin.include_role:
    name: routing
  vars:
    routing_enable_gateway: true

- name: "Enable pflog"
  ansible.builtin.include_role:
    name: pflog
  vars:
    pflog_enable: true

- name: "Stat /etc/pf.conf"
  ansible.builtin.file:
    path: /etc/pf.conf
    state: file
  register: pf_conf_stat
  ignore_errors: true

- name: "Create /etc/pf.conf"
  ansible.builtin.file:
    path: /etc/pf.conf
    state: touch
    owner: root
    group: wheel
    mode: u=rw,g=r,o=r
  when: pf_conf_stat is failed

- name: "Enable pf"
  community.general.sysrc:
    path: /etc/rc.conf.d/pf
    name: pf_enable
    value: true
  notify: "start_pf"

# pf must be enabled and "started" (/etc/rc.d/pf loads pf.ko) for pfctl to
# work
- name: "Flush pf changes"
  ansible.builtin.meta: flush_handlers

- name: "PF status"
  ansible.builtin.raw: pfctl -s Running
  register: pf_status
  changed_when: false

- name: "PF must be running"
  ansible.builtin.assert:
    that:
      - "pf_status.rc == 0"
      - "'Enabled' in pf_status.stdout"
    fail_msg: "Firewall is disabled"
    success_msg: "Firewall is enabled"

- name: "Configure pf"
  ansible.builtin.copy:
    src: etc/pf.conf
    dest: /etc/pf.conf
    owner: root
    group: wheel
    mode: u=rw,g=r,o=r
    validate: /sbin/pfctl -nf %s
  notify: "reload_pf_conf"
