// Copyright 2026 Samvel Khalatyan. All rights reserved.
//
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package sim

import "math/rand/v2"

type generator struct {
	ops int
	op  operation

	malloc   OpFunc
	free     OpFunc
	allocLen func() int
}

func newGenerator(n int, malloc, free OpFunc, allocLen func() int) *generator {
	return &generator{
		ops:      n,
		malloc:   malloc,
		free:     free,
		allocLen: allocLen,
	}
}

// Next generates a new operation. It returns false if no operations are left
// to generate, else true.
func (gen *generator) Next() bool {
	if gen.ops == 0 {
		return false
	}
	gen.op = gen.next()
	gen.ops--
	return true
}

func (gen *generator) next() operation {
	switch {
	case gen.allocLen() == 0:
		// no allocated addresses available for free, malloc only.
		return gen.randMalloc()
	default:
		return gen.randOp()
	}
}

func (gen *generator) randOp() operation {
	switch n := rand.IntN(ptsTotal); {
	case n < ptsMalloc:
		return gen.randMalloc()
	default:
		return gen.randFree()
	}
}

func (gen *generator) randMalloc() operation {
	sz := 1 + rand.IntN(mallocMaxSize) // +1 for at least one byte
	return gen.malloc(sz)
}

func (gen *generator) randFree() operation {
	i := rand.IntN(gen.allocLen())
	return gen.free(i)
}

// Op returns last operation generated by the call to [generator.Next].
func (gen *generator) Op() operation {
	return gen.op
}
