// Copyright 2026 Samvel Khalatyan. All rights reserved.
//
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package sim

import "math/rand/v2"

const mallocMaxSize = 1 << 10 // 1KB

const (
	// random points (weights) assignment to skew generation toward more
	// allocations than free.
	ptsMalloc = 6
	ptsFree   = 4

	ptsTotal = ptsMalloc + ptsFree
)

type generator struct {
	ops int
	op  operation

	malloc      OpFunc
	free        OpFunc
	allocations func() int
}

func newGenerator(n int, malloc, free OpFunc, allocations func() int) *generator {
	return &generator{
		ops:         n,
		malloc:      malloc,
		free:        free,
		allocations: allocations,
	}
}

// Next generates a new operation. It returns false if no operations are left
// to generate, else true.
func (gen *generator) Next() bool {
	if gen.ops == 0 {
		return false
	}
	gen.op = gen.next()
	gen.ops--
	return true
}

func (gen *generator) next() operation {
	if gen.allocations() == 0 {
		// no allocated addresses available for free, malloc only.
		return gen.nextMalloc()
	}
	switch n := rand.IntN(ptsTotal); {
	case n < ptsMalloc:
		return gen.nextMalloc()
	default:
		return gen.nextFree()
	}
}

func (gen *generator) nextMalloc() operation {
	sz := 1 + rand.IntN(mallocMaxSize) // +1 for at least one byte
	return gen.malloc(sz)
}

func (gen *generator) nextFree() operation {
	i := rand.IntN(gen.allocations())
	return gen.free(i)
}

// Op returns last operation generated by the call to [generator.Next].
func (gen *generator) Op() operation {
	return gen.op
}
