# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
- name: Install poudriere
  become: true
  community.general.pkgng:
    name:
      # keep-sorted start
      - FreeBSD-clibs-dev
      - FreeBSD-jail # for /usr/sbin/{jail,jls}
      - FreeBSD-runtime # for /sbin/sysctl
      - git
      - poudriere-devel # works better with jails than poudriere
      # keep-sorted end
    state: present

- name: Configure poudriere
  vars:
    _conf_file: /usr/local/etc/poudriere.conf
    _distfile_cache_path: /usr/ports/distfiles
  block:
    - name: Create distfiles cache
      become: true
      ansible.builtin.file:
        path: "{{ _distfile_cache_path }}"
        state: directory
        owner: root
        group: wheel
        mode: u=rwx,g=rx,o=rx

    - name: Generate RSA keys
      ansible.builtin.include_role:
        name: openssl_gen
        tasks_from: rsa

    - name: Configure
      become: true
      vars:
        _pkg_repo_signing_key: >-
          {{
            (
              openssl_gen_rsa.path | dirname,
              'private',
              openssl_gen_rsa.path | basename | splitext | first
            ) | path_join
          }}.key
      ansible.builtin.template:
        src: "{{ _conf_file | trim('/') }}.j2"
        dest: "{{ _conf_file }}"
        owner: root
        group: wheel
        mode: u=rw,g=r,o=r
