# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
# jail_skel_zfs_dataset is the jails' parent dataset.
jail_skel_zfs_dataset: zroot/usr/jail

jail_skel_template_name: 15.1
