# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
# keep-sorted start
# netif_bridges is the list of bridge interfaces to configure. Each iface has
# the following structure:
#   name  string  iface name
#   cidr  string  iface IP address with sub-net mask in CIDR format
#   addm  string? members interfaces to add (e.g. bridge)
#   desc  string? iface description
netif_bridges: []
# netif_ifaces lists insterfaces to configure. Each iface has the following
# structure:
#   name  string  iface name
#   cidr  string  iface IP address with sub-net mask in CIDR format
#   desc  string? iface description
netif_ifaces: []
# keep-sorted end
