# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

ext_if = "bridge0"

tcp_services = "{ domain, ntp, ssh }"
udp_services = "{ domain, ntp}"

icmp_types = "{ echoreq, unreach }"

# -- Options
# Don't filter on the loopback interface
set skip on lo0

# -- Translation

# -- Packet Filter
# Scrub incoming packets
match in all scrub (no-df)

# Deny all incoming traffic
block log all

# Activate spoofing protection for all interfaces
block in quick from urpf-failed

# Allow connections created by the system, retain the state.
pass out proto tcp to any port $tcp_services
pass     proto udp to any port $udp_services

# Debugging traffic
pass inet proto icmp all icmp-type $icmp_types

# Secure shell
pass in inet proto tcp to $ext_if port ssh
