# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

    location /freebsd/ports/ {
      rewrite ^/freebsd/ports/(.*)$ /$1 break;
      rewrite_log on;

      proxy_cache freebsd-ports;
      proxy_cache_revalidate on;     # conditional GET for outdated content.
      proxy_cache_lock on;           # concurrent MISS'es lock, first fetches.
      proxy_cache_lock_timeout 30s;  # first fetch must complete in 30 seconds.
      proxy_cache_valid 7d;          # cache validity for 200, 301, 302.

      proxy_pass  https://pkg.FreeBSD.org;

      add_header	X-Cache-Status $upstream_cache_status;
    }
