# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

{{ jail_name }} {
  vnet.interface = "e0b_${name}";

  mount += "/home/op $path/home/op nullfs rw 0 0";

  exec.prestart += "e0=\$(ifconfig epair create) && ifconfig \${e0} up name e0a_${name} && ifconfig \${e0%a}b up name e0b_${name}";
  exec.prestart += "ifconfig {{ jail_bridge }} addm e0a_${name}";
  exec.prestart += "ifconfig e0a_${name} description 'vnet0 host interface for ${name} jail'";

  exec.poststop += "ifconfig e0a_${name} destroy";
}
