# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
- name: Add {{ _entry.name }}
  community.general.ldap_entry:
    server_uri: "ldap://ldap.lab.net"
    bind_dn: "cn=op,dc=lab,dc=net"
    bind_pw: "{{ openldap_server_bind_pw }}"
    start_tls: true
    validate_certs: true
    dn: "{{ _entry.dn }}"
    objectClass: "{{ _entry.objectClass }}"
    attributes:
      # keep-sorted start
      cn: "{{ _entry.cn | default(omit) }}"
      dc: "{{ _entry.dc | default(omit) }}"
      description: "{{ _entry.description | default(omit) }}"
      gecos: "{{ _entry.gecos | default(omit) }}"
      gidNumber: "{{ _entry.gidNumber | default(omit) }}"
      homeDirectory: "{{ _entry.homeDirectory | default(omit) }}"
      loginShell: "{{ _entry.loginShell | default(omit) }}"
      memberUid: "{{ _entry.memberUid | default(omit) }}"
      o: "{{ _entry.o | default(omit) }}"
      ou: "{{ _entry.ou | default(omit) }}"
      uid: "{{ _entry.uid | default(omit) }}"
      uidNumber: "{{ _entry.uidNumber | default(omit) }}"
      # keep-sorted end
