# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
- name: Install packages
  vars:
    _pkg: openldap26-server
  block:
    - name: Install {{ _pkg | join(',') }}
      community.general.pkgng:
        name: "{{ _pkg }}"
        state: present

- name: Patch config
  vars:
    _cfg_file: /usr/local/etc/openldap/slapd.ldif
  block:
    - name: Create temp file
      ansible.builtin.tempfile:
        state: file
        suffix: .diff
        prefix: ansible.slapd.ldif.
      register: openldap_server_tempfile_task
      failed_when: openldap_server_tempfile_task.path is not defined

    - name: Create patch
      ansible.builtin.template:
        src: usr/local/etc/openldap/slapd.ldif.diff.j2
        dest: "{{ openldap_server_tempfile_task.path }}"
        mode: u=rw,g=r,o=r

    - name: Patch configuration
      ansible.posix.patch:
        src: "{{ openldap_server_tempfile_task.path }}"
        remote_src: true
        dest: "{{ _cfg_file }}"
        backup: true
        ignore_whitespace: true

    - name: Clean patch
      ansible.builtin.file:
        path: "{{ openldap_server_tempfile_task.path }}"
        state: absent
      when: openldap_server_tempfile_task.path is defined

- name: Create configuration database
  vars:
    _db_path: /usr/local/etc/openldap/slapd.d
    _cfg_file: /usr/local/etc/openldap/slapd.ldif
  block:
    - name: Check configuration database
      ansible.builtin.stat:
        path: "{{ _db_path }}"
      register: openldap_server_stat_db_task

    - name: Create config db
      when: not openldap_server_stat_db_task.stat.exists
      notify: "openldap_server_start"
      block:
        - name: Create database tree
          ansible.builtin.file:
            path: "{{ _path }}"
            state: directory
            owner: ldap
            group: ldap
            mode: u=rwx
          loop:
            - "{{ _db_path }}"
            - /var/db/openldap-data/lab.net
          loop_control:
            loop_var: _path

        - name: Import configuration database
          ansible.builtin.command:
            cmd: >-
              /usr/local/sbin/slapadd
                -n0
                -F {{ _db_path }}
                -l {{ _cfg_file }}
          register: openldap_server_slapadd_task
          changed_when: openldap_server_slapadd_task is succeeded

        - name: Fix database ownership
          ansible.builtin.file:
            path: "{{ _path }}"
            state: directory
            recurse: true
            owner: ldap
            group: ldap
            mode: u=rwx
          loop:
            - /var/db/openldap-data
            - "{{ _db_path }}"
          loop_control:
            loop_var: _path

- name: Configure service
  notify: "openldap_server_start"
  vars:
    _rc_file: /usr/local/etc/rc.conf.d/slapd
  block:
    - name: Create rc.conf.d folder
      ansible.builtin.file:
        path: "{{ _rc_file | dirname }}"
        state: directory
        owner: root
        group: wheel
        mode: u=rwx,g=rx,o=rx

    # Force slapd rc-script to fix the owner and permissions:
    # https://github.com/freebsd/freebsd-ports/blob/c2991243dbb2dfc9f932d1560af12061ed998cf2/net/openldap26-server/files/slapd.in#L153
    - name: Set socket
      community.general.sysrc:
        name: slapd_sockets
        value: /var/run/openldap/ldapi
        path: "{{ _rc_file }}"

    - name: Set flags
      community.general.sysrc:
        name: slapd_flags
        # noqa jinja[spacing]
        value: >-
          -h 'ldapi://%2Fvar%2Frun%2Fopenldap%2Fldapi
          {%- if openldap_server_addr %} ldap://{{ openldap_server_addr }}{% endif -%}
          ' -s 256
        path: "{{ _rc_file }}"

    - name: Set CN config
      community.general.sysrc:
        name: slapd_cn_config
        value: true
        path: "{{ _rc_file }}"

    - name: Enable slapd
      community.general.sysrc:
        name: slapd_enable
        value: true
        path: "{{ _rc_file }}"
