// Copyright 2026 Samvel Khalatyan. All rights reserved.
//
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.6
// source: dp/proto/options/pb/data.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Store is a data store.
//
// Next ID: 3
type Store struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Public      *string                `protobuf:"bytes,1,opt,name=public"`
	xxx_hidden_Private     *string                `protobuf:"bytes,2,opt,name=private"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Store) Reset() {
	*x = Store{}
	mi := &file_dp_proto_options_pb_data_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Store) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Store) ProtoMessage() {}

func (x *Store) ProtoReflect() protoreflect.Message {
	mi := &file_dp_proto_options_pb_data_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Store) GetPublic() string {
	if x != nil {
		if x.xxx_hidden_Public != nil {
			return *x.xxx_hidden_Public
		}
		return ""
	}
	return ""
}

func (x *Store) GetPrivate() string {
	if x != nil {
		if x.xxx_hidden_Private != nil {
			return *x.xxx_hidden_Private
		}
		return ""
	}
	return ""
}

func (x *Store) SetPublic(v string) {
	x.xxx_hidden_Public = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *Store) SetPrivate(v string) {
	x.xxx_hidden_Private = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *Store) HasPublic() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Store) HasPrivate() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Store) ClearPublic() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Public = nil
}

func (x *Store) ClearPrivate() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Private = nil
}

type Store_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// public holds data publicly available data. It is safe to share this data
	// with other applications.
	Public *string
	// private holds sensitive data that should be cleaned before the message is
	// stored or send over the wire.
	Private *string
}

func (b0 Store_builder) Build() *Store {
	m0 := &Store{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Public != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Public = b.Public
	}
	if b.Private != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Private = b.Private
	}
	return m0
}

var File_dp_proto_options_pb_data_proto protoreflect.FileDescriptor

const file_dp_proto_options_pb_data_proto_rawDesc = "" +
	"\n" +
	"\x1edp/proto/options/pb/data.proto\x12\x10dp.proto.options\x1a!google/protobuf/go_features.proto\x1a%dp/proto/options/pb/annotations.proto\"A\n" +
	"\x05Store\x12\x16\n" +
	"\x06public\x18\x01 \x01(\tR\x06public\x12 \n" +
	"\aprivate\x18\x02 \x01(\tB\x06\x82\xb5\x18\x02\b\x01R\aprivateB2Z(github.com/skhal/lab/dp/proto/options/pb\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_dp_proto_options_pb_data_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_dp_proto_options_pb_data_proto_goTypes = []any{
	(*Store)(nil), // 0: dp.proto.options.Store
}
var file_dp_proto_options_pb_data_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_dp_proto_options_pb_data_proto_init() }
func file_dp_proto_options_pb_data_proto_init() {
	if File_dp_proto_options_pb_data_proto != nil {
		return
	}
	file_dp_proto_options_pb_annotations_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dp_proto_options_pb_data_proto_rawDesc), len(file_dp_proto_options_pb_data_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dp_proto_options_pb_data_proto_goTypes,
		DependencyIndexes: file_dp_proto_options_pb_data_proto_depIdxs,
		MessageInfos:      file_dp_proto_options_pb_data_proto_msgTypes,
	}.Build()
	File_dp_proto_options_pb_data_proto = out.File
	file_dp_proto_options_pb_data_proto_goTypes = nil
	file_dp_proto_options_pb_data_proto_depIdxs = nil
}
