// Code generated by "stringer -type State -linecomment"; DO NOT EDIT.

package proc

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StateReady-1]
	_ = x[StateRunning-2]
	_ = x[StateBlocked-3]
	_ = x[StateZombie-4]
}

const _State_name = "readyrunningblockedzombie"

var _State_index = [...]uint8{0, 5, 12, 19, 25}

func (i State) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_State_index)-1 {
		return "State(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _State_name[_State_index[idx]:_State_index[idx+1]]
}
