# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
- name: "Update /etc/rc.conf - remove {{ _rc_var }}"
  community.general.sysrc:
    name: "{{ _rc_var }}"
    state: absent
