# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
# noqa name[template]
- name: "Update {{ var.path }} - set {{ var.name }}"
  community.general.sysrc:
    name: "{{ var.name }}"
    value: "{{ var.value }}"
    path: "{{ var.path | default(omit) }}"
