// Copyright 2026 Samvel Khalatyan. All rights reserved.
//
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.34.2
// source: infra/cmd/certval/pb/config.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Config lists certificates to validate and Slack configuration to send
// notifications to.
//
// Next ID: 3
type Config struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Slack       *Slack                 `protobuf:"bytes,1,opt,name=slack"`
	xxx_hidden_Certificate *[]*Certificate        `protobuf:"bytes,2,rep,name=certificate"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_infra_cmd_certval_pb_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_infra_cmd_certval_pb_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Config) GetSlack() *Slack {
	if x != nil {
		return x.xxx_hidden_Slack
	}
	return nil
}

func (x *Config) GetCertificate() []*Certificate {
	if x != nil {
		if x.xxx_hidden_Certificate != nil {
			return *x.xxx_hidden_Certificate
		}
	}
	return nil
}

func (x *Config) SetSlack(v *Slack) {
	x.xxx_hidden_Slack = v
}

func (x *Config) SetCertificate(v []*Certificate) {
	x.xxx_hidden_Certificate = &v
}

func (x *Config) HasSlack() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Slack != nil
}

func (x *Config) ClearSlack() {
	x.xxx_hidden_Slack = nil
}

type Config_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// slack holds Slack configuration parameters such as webhook, etc.
	Slack *Slack
	// certificate lists certificates to validate.
	Certificate []*Certificate
}

func (b0 Config_builder) Build() *Config {
	m0 := &Config{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Slack = b.Slack
	x.xxx_hidden_Certificate = &b.Certificate
	return m0
}

// Slack holds notification parameters such as application webhook, etc.
//
// Next ID: 2
type Slack struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Webhook     *string                `protobuf:"bytes,1,opt,name=webhook"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Slack) Reset() {
	*x = Slack{}
	mi := &file_infra_cmd_certval_pb_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Slack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Slack) ProtoMessage() {}

func (x *Slack) ProtoReflect() protoreflect.Message {
	mi := &file_infra_cmd_certval_pb_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Slack) GetWebhook() string {
	if x != nil {
		if x.xxx_hidden_Webhook != nil {
			return *x.xxx_hidden_Webhook
		}
		return ""
	}
	return ""
}

func (x *Slack) SetWebhook(v string) {
	x.xxx_hidden_Webhook = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *Slack) HasWebhook() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Slack) ClearWebhook() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Webhook = nil
}

type Slack_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// webook is the webhook to Slack application
	Webhook *string
}

func (b0 Slack_builder) Build() *Slack {
	m0 := &Slack{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Webhook != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Webhook = b.Webhook
	}
	return m0
}

// Certificate describes a single certificate to validate.
//
// Next ID: 4
type Certificate struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name        *string                `protobuf:"bytes,1,opt,name=name"`
	xxx_hidden_Path        *string                `protobuf:"bytes,2,opt,name=path"`
	xxx_hidden_Notify      *Certificate_Notify    `protobuf:"bytes,3,opt,name=notify"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Certificate) Reset() {
	*x = Certificate{}
	mi := &file_infra_cmd_certval_pb_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Certificate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Certificate) ProtoMessage() {}

func (x *Certificate) ProtoReflect() protoreflect.Message {
	mi := &file_infra_cmd_certval_pb_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Certificate) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *Certificate) GetPath() string {
	if x != nil {
		if x.xxx_hidden_Path != nil {
			return *x.xxx_hidden_Path
		}
		return ""
	}
	return ""
}

func (x *Certificate) GetNotify() *Certificate_Notify {
	if x != nil {
		return x.xxx_hidden_Notify
	}
	return nil
}

func (x *Certificate) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *Certificate) SetPath(v string) {
	x.xxx_hidden_Path = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *Certificate) SetNotify(v *Certificate_Notify) {
	x.xxx_hidden_Notify = v
}

func (x *Certificate) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Certificate) HasPath() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Certificate) HasNotify() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Notify != nil
}

func (x *Certificate) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Name = nil
}

func (x *Certificate) ClearPath() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Path = nil
}

func (x *Certificate) ClearNotify() {
	x.xxx_hidden_Notify = nil
}

type Certificate_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// name is the certificate name for logging purposes.
	Name *string
	// path is the absolute path to the certification location on the file system.
	Path *string
	// notify configures optional notification settings for the certificate.
	Notify *Certificate_Notify
}

func (b0 Certificate_builder) Build() *Certificate {
	m0 := &Certificate{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_Name = b.Name
	}
	if b.Path != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_Path = b.Path
	}
	x.xxx_hidden_Notify = b.Notify
	return m0
}

// Notify contains notification parameters.
//
// Next ID: 2
type Certificate_Notify struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ExpireDays  int32                  `protobuf:"varint,1,opt,name=expire_days,json=expireDays"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Certificate_Notify) Reset() {
	*x = Certificate_Notify{}
	mi := &file_infra_cmd_certval_pb_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Certificate_Notify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Certificate_Notify) ProtoMessage() {}

func (x *Certificate_Notify) ProtoReflect() protoreflect.Message {
	mi := &file_infra_cmd_certval_pb_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Certificate_Notify) GetExpireDays() int32 {
	if x != nil {
		return x.xxx_hidden_ExpireDays
	}
	return 0
}

func (x *Certificate_Notify) SetExpireDays(v int32) {
	x.xxx_hidden_ExpireDays = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *Certificate_Notify) HasExpireDays() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Certificate_Notify) ClearExpireDays() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_ExpireDays = 0
}

type Certificate_Notify_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// expire_days is the minimum number of days from now until certificate's
	// NotAfter below which the certificate is considered expiring.
	ExpireDays *int32
}

func (b0 Certificate_Notify_builder) Build() *Certificate_Notify {
	m0 := &Certificate_Notify{}
	b, x := &b0, m0
	_, _ = b, x
	if b.ExpireDays != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_ExpireDays = *b.ExpireDays
	}
	return m0
}

var File_infra_cmd_certval_pb_config_proto protoreflect.FileDescriptor

const file_infra_cmd_certval_pb_config_proto_rawDesc = "" +
	"\n" +
	"!infra/cmd/certval/pb/config.proto\x12\x11infra.cmd.certval\x1a!google/protobuf/go_features.proto\"z\n" +
	"\x06Config\x12.\n" +
	"\x05slack\x18\x01 \x01(\v2\x18.infra.cmd.certval.SlackR\x05slack\x12@\n" +
	"\vcertificate\x18\x02 \x03(\v2\x1e.infra.cmd.certval.CertificateR\vcertificate\"!\n" +
	"\x05Slack\x12\x18\n" +
	"\awebhook\x18\x01 \x01(\tR\awebhook\"\x9f\x01\n" +
	"\vCertificate\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12=\n" +
	"\x06notify\x18\x03 \x01(\v2%.infra.cmd.certval.Certificate.NotifyR\x06notify\x1a)\n" +
	"\x06Notify\x12\x1f\n" +
	"\vexpire_days\x18\x01 \x01(\x05R\n" +
	"expireDaysB3Z)github.com/skhal/lab/infra/cmd/certval/pb\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe9\a"

var file_infra_cmd_certval_pb_config_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_infra_cmd_certval_pb_config_proto_goTypes = []any{
	(*Config)(nil),             // 0: infra.cmd.certval.Config
	(*Slack)(nil),              // 1: infra.cmd.certval.Slack
	(*Certificate)(nil),        // 2: infra.cmd.certval.Certificate
	(*Certificate_Notify)(nil), // 3: infra.cmd.certval.Certificate.Notify
}
var file_infra_cmd_certval_pb_config_proto_depIdxs = []int32{
	1, // 0: infra.cmd.certval.Config.slack:type_name -> infra.cmd.certval.Slack
	2, // 1: infra.cmd.certval.Config.certificate:type_name -> infra.cmd.certval.Certificate
	3, // 2: infra.cmd.certval.Certificate.notify:type_name -> infra.cmd.certval.Certificate.Notify
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_infra_cmd_certval_pb_config_proto_init() }
func file_infra_cmd_certval_pb_config_proto_init() {
	if File_infra_cmd_certval_pb_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_infra_cmd_certval_pb_config_proto_rawDesc), len(file_infra_cmd_certval_pb_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_infra_cmd_certval_pb_config_proto_goTypes,
		DependencyIndexes: file_infra_cmd_certval_pb_config_proto_depIdxs,
		MessageInfos:      file_infra_cmd_certval_pb_config_proto_msgTypes,
	}.Build()
	File_infra_cmd_certval_pb_config_proto = out.File
	file_infra_cmd_certval_pb_config_proto_goTypes = nil
	file_infra_cmd_certval_pb_config_proto_depIdxs = nil
}
