# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

{{ jail_name }} {
  vnet.interface = "e0b_${name}";

{% for dep in jail_depend %}
{% if loop.first %}
  depend = "{{ dep }}";
{% else %}
  depend += "{{ dep }}";
{% endif %}
{% endfor %}

# keep-sorted start group_start_regex=["^.% if"]
{% if jail_children_max %}
  children.max = {{ jail_children_max }};
{% endif %}
{% if jail_enforce_statfs %}
  enforce_statfs = {{ jail_enforce_statfs }};
{% endif %}
# keep-sorted end

# The group_start_regex does not start '{' because it makes Jinja2 assume
# that it is the beginning of an if-expression.
#
# keep-sorted start group_start_regex=["^.% if"]
{% if jail_allow_chflags %}
  allow.chflags;
{% endif %}
{% if jail_allow_mlock %}
  allow.mlock;
{% endif %}
{% if jail_allow_mount %}
  allow.mount;
{% endif %}
{% if jail_allow_mount_devfs %}
  allow.mount.devfs;
{% endif %}
{% if jail_allow_mount_linprocfs %}
  allow.mount.linprocfs;
{% endif %}
{% if jail_allow_mount_nullfs %}
  allow.mount.nullfs;
{% endif %}
{% if jail_allow_mount_procfs %}
  allow.mount.procfs;
{% endif %}
{% if jail_allow_mount_tmpfs %}
  allow.mount.tmpfs;
{% endif %}
# keep-sorted end

  mount = "/home/op $path/home/op nullfs rw 0 0";
{% for mount in jail_mounts %}
  mount += "{{ mount.path }} $path{{ mount.path }} nullfs {{ mount.perm | default('rw') }} 0 0";
  exec.prepare += "[ -d $path{{ mount.path }} ] || mkdir -m 0755 $path{{ mount.path }}";
{% endfor %}

  exec.prestart += "e0=\$(ifconfig epair create) && ifconfig \${e0} up name e0a_${name} && ifconfig \${e0%a}b up name e0b_${name}";
  exec.prestart += "ifconfig {{ jail_bridge }} addm e0a_${name}";
  exec.prestart += "ifconfig e0a_${name} description 'vnet0 host interface for ${name} jail'";

  exec.poststop += "ifconfig e0a_${name} destroy";
}
