# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
- name: Configure PKG repos
  hosts: ldap.lab.net
  tags: pkg-repos
  tasks:
    - name: Fetch repo public key
      ansible.builtin.include_role:
        name: openssl_gen
        tasks_from: rsa_fetch

- name: Configure LDAP server
  hosts: ldap.lab.net
  tags: ldap
  roles:
    - role: openldap_server
    # generate certificate and let ldap:ldap own it. Run this after openldap
    # role, where openldap-package installation creates ldap:ldap user and
    # group.
    - role: openssl_gen
      tags: ldap_cert
    - role: openldap_client

- name: Fill LDAP entries
  hosts: ldap.lab.net
  tags: ldapadd
  tasks:
    - name: Add entries
      ansible.builtin.include_role:
        name: openldap_server
        tasks_from: add_entries

- name: Certificate validation
  hosts: ldap.lab.net
  tags: certval
  roles:
    - role: certval
