# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
- name: Configure PKG repos
  hosts: ssl.lab.net
  tags: pkg-repos
  tasks:
    - name: Add repos
      ansible.builtin.include_role:
        name: local_pkg
        tasks_from: configure_repos
    - name: Fetch repo public key
      ansible.builtin.include_role:
        name: openssl_gen
        tasks_from: rsa_fetch

- name: Bootstrap SSL jail
  hosts: ssl.lab.net
  tags: bootstrap
  roles:
    # keep-sorted start
    - role: doas
    - role: pkg
    - role: ssh
    - role: syslog
    - role: timezone
    - role: user
    # keep-sorted end

- name: Configure DNS server
  hosts: ssl.lab.net
  tags: dns
  roles:
    - role: local_unbound

- name: Setup Central Authority
  hosts: ssl.lab.net
  tags: ca
  tasks:
    - name: Generate CA
      ansible.builtin.include_role:
        name: openssl_ca
        tasks_from: generate_ca

- name: Fetch CA
  hosts: nuc.lab.net
  tags: ca
  roles:
    - role: openssl_ca

- name: Certificate validation
  hosts: ssl.lab.net
  tags: certval
  roles:
    - role: certval
