# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
- name: Create DNS jail
  hosts: nuc.lab.net
  tags: create
  vars:
    # keep-sorted start
    jail_bridge: bridge0
    jail_cidr: 10.0.0.2/24
    jail_defaultrouter: 10.0.0.1
    jail_name: dns
    # keep-sorted end
  roles:
    - role: jail

- name: Bootstrap DNS jail
  hosts: dns.lab.net
  tags: bootstrap
  roles:
    - role: ssh
    - role: syslog
    - role: user
    - role: pkg

- name: Configure certificate
  hosts: dns.lab.net
  tags: cert
  roles:
    - role: openssl_ca

# Configure DNS server in a separate play to ensure that changes to the resolver
# do not affect handlers run by previous roles, e.g. pkg handlers upgrade
# packages but fails if bind and local_unbound roles mess up with DNS settings.
# The separate plays guarantee that the roles run independently.
- name: Configure DNS server
  hosts: dns.lab.net
  tags: dns
  roles:
    - role: bind
    # bind installs the package and adds bind:bind user. This user owns
    # the certificate.
    - role: openssl_gen
    - role: local_unbound
