# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
- name: Configure PKG repos
  hosts: bsd.lab.net
  tags: pkg-repos
  tasks:
    - name: Fetch repo public key
      ansible.builtin.include_role:
        name: openssl_gen
        tasks_from: rsa_fetch

- name: Configure SSO
  hosts: bsd.lab.net
  tags: sso
  roles:
    - role: pam_ldap

- name: Setup development environment
  hosts: bsd.lab.net
  tags: devenv
  vars_files:
    - vars/dev.yml
  roles:
    - role: pkg
