# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
- name: Create LDAP jail
  hosts: nuc.lab.net
  tags: create
  vars:
    # keep-sorted start
    jail_bridge: bridge1
    jail_cidr: 10.0.0.3/24
    jail_defaultrouter: 10.0.0.1
    jail_depend:
      - dns
    jail_name: ldap
    # keep-sorted end
  roles:
    - role: jail

- name: Bootstrap LDAP jail
  hosts: ldap.lab.net
  tags: bootstrap
  roles:
    - role: ssh
    - role: syslog
    - role: user
    - role: pkg

- name: Configure DNS server
  hosts: ldap.lab.net
  tags: dns
  roles:
    - role: local_unbound

- name: Configure certificates
  hosts: ldap.lab.net
  tags: cert
  roles:
    - role: openssl_ca

- name: Configure LDAP server
  hosts: ldap.lab.net
  tags: ldap
  roles:
    - role: openldap_server
    # generate certificate and let ldap:ldap own it. Run this after openldap
    # role, where openldap-package installation creates ldap:ldap user and
    # group.
    - role: openssl_gen
    - role: openldap_client

- name: Fill LDAP entries
  hosts: ldap.lab.net
  tags: ldapadd
  tasks:
    - name: Add entries
      ansible.builtin.include_role:
        name: openldap_server
        tasks_from: add_entries
