# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
- name: Create SSL jail
  hosts: nuc.lab.net
  tags: create
  vars:
    # keep-sorted start
    jail_bridge: bridge0
    jail_cidr: 10.0.0.4/24
    jail_defaultrouter: 10.0.0.1
    jail_name: ssl
    # keep-sorted end
  roles:
    - role: jail

- name: Bootstrap SSL jail
  hosts: ssl.lab.net
  tags: bootstrap
  roles:
    - role: ssh
    - role: syslog
    - role: user
    - role: pkg
    - role: timezone

- name: Configure DNS server
  hosts: ssl.lab.net
  tags: dns
  roles:
    - role: local_unbound

- name: Setup Central Authority
  hosts: ssl.lab.net
  tags: ca
  tasks:
    - name: Generate CA
      ansible.builtin.include_role:
        name: openssl_ca
        tasks_from: generate_ca

- name: Fetch CA
  hosts: nuc.lab.net
  tags: ca
  roles:
    - role: openssl_ca
