# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
- name: Install nginx
  become: true
  community.general.pkgng:
    name: nginx
    state: present

- name: Configure service
  vars:
    _rc_file: /usr/local/etc/rc.conf.d/nginx
  block:
    - name: Create {{ _rc_file | dirname }}
      become: true
      ansible.builtin.file:
        path: "{{ _rc_file | dirname }}"
        state: directory
        owner: root
        group: wheel
        mode: u=rwx,g=rx,o=rx

    - name: Enable nginx
      become: true
      notify: local_pkg_start_nginx
      community.general.sysrc:
        path: "{{ _rc_file }}"
        name: nginx_enable
        value: true

- name: Configure nginx
  vars:
    _conf_files:
      - /usr/local/etc/nginx/nginx.conf
      - /usr/local/etc/nginx/conf.d/freebsd-ports.conf
  block:
    - name: Create configs
      loop: "{{ _conf_files }}"
      loop_control:
        loop_var: _conf_file
      ansible.builtin.include_tasks: "_create_conf.yml"

    - name: Copy configurations
      become: true
      notify: local_pkg_restart_nginx
      vars:
        _conf_d_path: /usr/local/etc/nginx/conf.d/
      ansible.builtin.copy:
        src: "{{ _conf_d_path | trim('/') }}/"
        dest: "{{ _conf_d_path }}"
        owner: root
        group: wheel
        mode: u=rw,g=r,o=r
        directory_mode: u=rwx,g=rx,o=rx

- name: Configure newsyslog
  vars:
    _conf_file: /usr/local/etc/newsyslog.conf.d/nginx.conf
  block:
    - name: Create {{ _conf_file | dirname }}
      become: true
      ansible.builtin.file:
        path: "{{ _conf_file | dirname }}"
        state: directory
        owner: root
        group: wheel
        mode: u=rwx,g=rx,o=rx

    - name: Rotate logs
      become: true
      ansible.builtin.copy:
        src: usr/local/etc/newsyslog.conf.d/nginx.conf
        dest: "{{ _conf_file }}"
        owner: root
        group: wheel
        mode: u=rw,g=r,o=r

- name: Setup cache
  vars:
    _cache_path: /var/cache/pkg.freebsd.ports
  block:
    - name: Create {{ _cache_path }}
      become: true
      ansible.builtin.file:
        path: "{{ _cache_path }}"
        state: directory
        owner: www
        group: www
        mode: u=rwx,g=rx,o=rx
