# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

  proxy_cache_path /var/cache/pkg.freebsd.base levels=1:2 use_temp_path=off
                   keys_zone=freebsd-base:10m inactive=30d;
