# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
- name: Create folders
  vars:
    _crt_dir: "{{ openssl_ca_crt_file | dirname }}"
  ansible.builtin.file:
    name: "{{ _crt_dir }}"
    state: directory
    owner: root
    group: wheel
    mode: u=rwx,g=rx,o=rx

- name: Load CA certificate
  ansible.builtin.slurp:
    src: "{{ openssl_ca_crt_file }}"
  register: openssl_ca_crt_task
  delegate_to: "{{ openssl_ca_host }}"

- name: Write CA certificate
  ansible.builtin.copy:
    dest: "{{ openssl_ca_crt_file }}"
    content: "{{ openssl_ca_crt_task.content | b64decode }}"
    owner: root
    group: wheel
    mode: u=rw,g=r,o=r
  notify: openssl_ca_rehash_certs
