# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
- name: Install packages
  become: true
  community.general.pkgng:
    name:
      - FreeBSD-certctl
      - FreeBSD-openssl
      - py312-cryptography
    state: present

- name: Fetch CA certificate
  ansible.builtin.include_tasks: "fetch_ca.yml"
