# Copyright 2026 Samvel Khalatyan. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
# local_pkg_listen_on is the IP4 address to listen on.
local_pkg_listen_on: ""
